version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - forbidigo
    - gocritic
    - godot
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noinlineerr
    - prealloc
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - testifylint
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl_v5
  settings:
    errcheck:
      exclude-functions:
        - (io.ReadCloser).Close
        - (io.WriteCloser).Close
        - (io.ReadWriteCloser).Close
        - (*os.File).Close
        - (*github.com/gorilla/websocket.Conn).Close
        - (*github.com/mdlayher/vsock.Listener).Close
        - os.Remove
        - (*compress/gzip.Writer).Close
    forbidigo:
      forbid:
        # Built-in bootstrapping functions.
        - pattern: ^print(ln)?$
        # slog without context
        - pattern: ^slog\.(Debug|Info|Warn|Error)$
          msg: Do not use slog without context
    gocritic:
      disable-all: true
      enabled-checks:
        - ruleguard
      settings:
        ruleguard:
          rules: ./scripts/lint/ruleguard/*.go
    misspell:
      ignore-rules:
        # Interface name formed from auth
        - auther
    revive:
      rules:
        # Disabled for now while we are rushing with the development of an initial version.
        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#exported
        # - name: exported
        #   arguments:
        #     - "checkPrivateReceivers"
        #     - "disableStutteringCheck"

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#import-shadowing
        - name: import-shadowing

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#unchecked-type-assertion
        - name: unchecked-type-assertion

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#var-naming
        - name: var-naming
          arguments: # The arguments here are quite odd looking. See the rule description.
            - []
            - []
            - - upperCaseConst: true

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#early-return
        - name: early-return

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#redundant-import-alias
        - name: redundant-import-alias

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#redefines-builtin-id
        - name: redefines-builtin-id

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#struct-tag
        - name: struct-tag

          # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#receiver-naming
        - name: receiver-naming

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#deep-exit
        - name: deep-exit

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#defer
        - name: defer

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#bool-literal-in-expr
        - name: bool-literal-in-expr

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#comment-spacings
        - name: comment-spacings

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#use-any
        - name: use-any

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#bare-return
        - name: bare-return

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#empty-block
        - name: empty-block

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#range-val-address
        - name: range-val-address

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#range-val-in-closure
        - name: range-val-in-closure

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#var-declaration
        - name: var-declaration

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#useless-break
        - name: useless-break

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#error-naming
        - name: error-naming

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#indent-error-flow
        - name: indent-error-flow

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#datarace
        - name: datarace

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#modifies-value-receiver
        - name: modifies-value-receiver

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#empty-lines
        - name: empty-lines

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#duplicated-imports
        - name: duplicated-imports

        # https://github.com/mgechev/revive/blob/2a1701aadbedfcc175cb92836a51407bec382652/RULES_DESCRIPTIONS.md#error-return
        - name: error-return
    sloglint:
      # Enforce using attributes only (overrides no-mixed-args, incompatible with kv-only).
      # https://github.com/go-simpler/sloglint?tab=readme-ov-file#attributes-only
      # Default: false
      attr-only: true
      # Enforce using static values for log messages.
      # https://github.com/go-simpler/sloglint?tab=readme-ov-file#static-messages
      # Default: false
      static-msg: true
      # Enforce a single key naming convention.
      # Values: snake, kebab, camel, pascal
      # https://github.com/go-simpler/sloglint?tab=readme-ov-file#key-naming-convention
      # Default: ""
      key-naming-case: snake
    staticcheck:
      checks:
        - '*'
        # Ignore requirement for package comments.
        - -ST1000
        # Incorrectly formatted error string.
        # https://staticcheck.dev/docs/checks/#ST1005
        # this has become an established standard in Incus and since we are building
        # on top of Incus, we inherit the same style of capitalized error messages.
        - -ST1005
    wsl_v5:
      case-max-lines: 1
      default: none
      enable:
        - err
        - leading-whitespace
        - trailing-whitespace
        - after-block
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        # generate-database expects to find declarations of the form //generate-database: in the entities package.
        source: '^//generate-database:mapper '
        text: comment-spacing
      - linters:
          - revive
        # generate-expr expects to find declarations of the form //generate-expr: in the inventory package.
        source: '^//generate-expr: '
        text: comment-spacing
      - linters:
          - revive
        paths:
          - internal/authn/tls
          - internal/maps
          - internal/version
        text: "var-naming: avoid package names that conflict with Go standard library package names"
      - linters:
          - revive
        # It's useful to have a sort and API package but revive disagrees.
        source: '^package (sort|api)$'
        text: var-naming
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/FuturFusion/operations-center)
    goimports:
      local-prefixes:
        - github.com/FuturFusion/operations-center
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
