// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/metrics/prometheus.gotmpl

package middleware

import (
	"context"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"

	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/shared/api"
)

// BMCServerClientPortWithPrometheus implements provisioning.BMCServerClientPort interface with all methods wrapped
// with Prometheus metrics.
type BMCServerClientPortWithPrometheus struct {
	base         provisioning.BMCServerClientPort
	instanceName string
}

var bmcserverClientPortDurationSummaryVec = promauto.NewSummaryVec(
	prometheus.SummaryOpts{
		Name:       "bmc_server_client_port_duration_seconds",
		Help:       "bmcserverClientPort runtime duration and result",
		MaxAge:     time.Minute,
		Objectives: map[float64]float64{0.5: 0.05, 0.9: 0.01, 0.99: 0.001},
	},
	[]string{"instance_name", "method", "result"},
)

// NewBMCServerClientPortWithPrometheus returns an instance of the provisioning.BMCServerClientPort decorated with prometheus summary metric.
func NewBMCServerClientPortWithPrometheus(base provisioning.BMCServerClientPort, instanceName string) BMCServerClientPortWithPrometheus {
	return BMCServerClientPortWithPrometheus{
		base:         base,
		instanceName: instanceName,
	}
}

// ApplyBIOSAttributes implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithPrometheus) ApplyBIOSAttributes(ctx context.Context, server provisioning.Server, attributes map[string]any) (bMCTaskMonitor *provisioning.BMCTaskMonitor, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		bmcserverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "ApplyBIOSAttributes", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.ApplyBIOSAttributes(ctx, server, attributes)
}

// ApplySecureBootCertificates implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithPrometheus) ApplySecureBootCertificates(ctx context.Context, server provisioning.Server, secureBoot api.BIOSSecureBoot) (b bool, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		bmcserverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "ApplySecureBootCertificates", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.ApplySecureBootCertificates(ctx, server, secureBoot)
}

// AttachMedia implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithPrometheus) AttachMedia(ctx context.Context, server provisioning.Server, virtualMediaID string, mediaURL string, setBootDevice bool) (bMCTaskMonitor *provisioning.BMCTaskMonitor, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		bmcserverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "AttachMedia", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.AttachMedia(ctx, server, virtualMediaID, mediaURL, setBootDevice)
}

// BIOSAttribute implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithPrometheus) BIOSAttribute(ctx context.Context, server provisioning.Server, attributeName string) (bIOSAttribute api.BIOSAttribute, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		bmcserverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "BIOSAttribute", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.BIOSAttribute(ctx, server, attributeName)
}

// BIOSAttributes implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithPrometheus) BIOSAttributes(ctx context.Context, server provisioning.Server) (bIOSAttributes []api.BIOSAttribute, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		bmcserverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "BIOSAttributes", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.BIOSAttributes(ctx, server)
}

// ConnectionTest implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithPrometheus) ConnectionTest(ctx context.Context, server provisioning.Server) (certificate string, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		bmcserverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "ConnectionTest", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.ConnectionTest(ctx, server)
}

// DetachMedia implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithPrometheus) DetachMedia(ctx context.Context, server provisioning.Server, virtualMediaID string) (bMCTaskMonitor *provisioning.BMCTaskMonitor, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		bmcserverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "DetachMedia", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.DetachMedia(ctx, server, virtualMediaID)
}

// Dump implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithPrometheus) Dump(ctx context.Context, server provisioning.Server, additionalEndpoints []string, skipPredefined bool, trace bool) (bMCDump api.BMCDump, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		bmcserverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "Dump", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Dump(ctx, server, additionalEndpoints, skipPredefined, trace)
}

// GetData implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithPrometheus) GetData(ctx context.Context, server provisioning.Server) (bMCData api.BMCData, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		bmcserverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "GetData", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetData(ctx, server)
}

// LogEntriesBySource implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithPrometheus) LogEntriesBySource(ctx context.Context, server provisioning.Server, logSource string) (bMCLogEvents []api.BMCLogEvent, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		bmcserverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "LogEntriesBySource", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.LogEntriesBySource(ctx, server, logSource)
}

// LogSources implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithPrometheus) LogSources(ctx context.Context, server provisioning.Server) (strings []string, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		bmcserverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "LogSources", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.LogSources(ctx, server)
}

// ResetSecureBootKeys implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithPrometheus) ResetSecureBootKeys(ctx context.Context, server provisioning.Server) (b bool, bMCTaskMonitor *provisioning.BMCTaskMonitor, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		bmcserverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "ResetSecureBootKeys", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.ResetSecureBootKeys(ctx, server)
}

// ServerPowerOff implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithPrometheus) ServerPowerOff(ctx context.Context, server provisioning.Server, force bool) (bMCTaskMonitor *provisioning.BMCTaskMonitor, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		bmcserverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "ServerPowerOff", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.ServerPowerOff(ctx, server, force)
}

// ServerPowerOn implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithPrometheus) ServerPowerOn(ctx context.Context, server provisioning.Server, force bool) (bMCTaskMonitor *provisioning.BMCTaskMonitor, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		bmcserverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "ServerPowerOn", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.ServerPowerOn(ctx, server, force)
}

// ServerRestart implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithPrometheus) ServerRestart(ctx context.Context, server provisioning.Server, force bool) (bMCTaskMonitor *provisioning.BMCTaskMonitor, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		bmcserverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "ServerRestart", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.ServerRestart(ctx, server, force)
}

// ServerSetLocationIndicator implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithPrometheus) ServerSetLocationIndicator(ctx context.Context, server provisioning.Server, active bool) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		bmcserverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "ServerSetLocationIndicator", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.ServerSetLocationIndicator(ctx, server, active)
}

// TaskState implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithPrometheus) TaskState(ctx context.Context, server provisioning.Server, taskMonitor *provisioning.BMCTaskMonitor) (bMCTaskState api.BMCTaskState, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		bmcserverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "TaskState", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.TaskState(ctx, server, taskMonitor)
}

// WaitForTask implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithPrometheus) WaitForTask(ctx context.Context, server provisioning.Server, taskMonitor *provisioning.BMCTaskMonitor) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		bmcserverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "WaitForTask", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.WaitForTask(ctx, server, taskMonitor)
}
