// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/util/logger/slog.gotmpl

package middleware

import (
	"context"

	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/shared/api"
)

// BMCServerClientPortWithErrorWrapper implements provisioning.BMCServerClientPort that wraps errors based custom logic.
type BMCServerClientPortWithErrorWrapper struct {
	_base        provisioning.BMCServerClientPort
	_wrapErrFunc func(error) error
}

// NewBMCServerClientPortWithErrorWrapper instruments an implementation of the provisioning.BMCServerClientPort with error wrapping.
func NewBMCServerClientPortWithErrorWrapper(base provisioning.BMCServerClientPort, wrapErrFunc func(error) error) BMCServerClientPortWithErrorWrapper {
	this := BMCServerClientPortWithErrorWrapper{
		_base:        base,
		_wrapErrFunc: wrapErrFunc,
	}

	return this
}

// ApplyBIOSAttributes implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithErrorWrapper) ApplyBIOSAttributes(ctx context.Context, server provisioning.Server, attributes map[string]any) (bMCTaskMonitor *provisioning.BMCTaskMonitor, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.ApplyBIOSAttributes(ctx, server, attributes)
}

// ApplySecureBootCertificates implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithErrorWrapper) ApplySecureBootCertificates(ctx context.Context, server provisioning.Server, secureBoot api.BIOSSecureBoot) (b bool, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.ApplySecureBootCertificates(ctx, server, secureBoot)
}

// AttachMedia implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithErrorWrapper) AttachMedia(ctx context.Context, server provisioning.Server, virtualMediaID string, mediaURL string, setBootDevice bool) (bMCTaskMonitor *provisioning.BMCTaskMonitor, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.AttachMedia(ctx, server, virtualMediaID, mediaURL, setBootDevice)
}

// BIOSAttribute implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithErrorWrapper) BIOSAttribute(ctx context.Context, server provisioning.Server, attributeName string) (bIOSAttribute api.BIOSAttribute, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.BIOSAttribute(ctx, server, attributeName)
}

// BIOSAttributes implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithErrorWrapper) BIOSAttributes(ctx context.Context, server provisioning.Server) (bIOSAttributes []api.BIOSAttribute, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.BIOSAttributes(ctx, server)
}

// ConnectionTest implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithErrorWrapper) ConnectionTest(ctx context.Context, server provisioning.Server) (certificate string, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.ConnectionTest(ctx, server)
}

// DetachMedia implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithErrorWrapper) DetachMedia(ctx context.Context, server provisioning.Server, virtualMediaID string) (bMCTaskMonitor *provisioning.BMCTaskMonitor, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.DetachMedia(ctx, server, virtualMediaID)
}

// Dump implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithErrorWrapper) Dump(ctx context.Context, server provisioning.Server, additionalEndpoints []string, skipPredefined bool, trace bool) (bMCDump api.BMCDump, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.Dump(ctx, server, additionalEndpoints, skipPredefined, trace)
}

// GetData implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithErrorWrapper) GetData(ctx context.Context, server provisioning.Server) (bMCData api.BMCData, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.GetData(ctx, server)
}

// LogEntriesBySource implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithErrorWrapper) LogEntriesBySource(ctx context.Context, server provisioning.Server, logSource string) (bMCLogEvents []api.BMCLogEvent, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.LogEntriesBySource(ctx, server, logSource)
}

// LogSources implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithErrorWrapper) LogSources(ctx context.Context, server provisioning.Server) (strings []string, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.LogSources(ctx, server)
}

// ResetSecureBootKeys implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithErrorWrapper) ResetSecureBootKeys(ctx context.Context, server provisioning.Server) (b bool, bMCTaskMonitor *provisioning.BMCTaskMonitor, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.ResetSecureBootKeys(ctx, server)
}

// ServerPowerOff implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithErrorWrapper) ServerPowerOff(ctx context.Context, server provisioning.Server, force bool) (bMCTaskMonitor *provisioning.BMCTaskMonitor, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.ServerPowerOff(ctx, server, force)
}

// ServerPowerOn implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithErrorWrapper) ServerPowerOn(ctx context.Context, server provisioning.Server, force bool) (bMCTaskMonitor *provisioning.BMCTaskMonitor, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.ServerPowerOn(ctx, server, force)
}

// ServerRestart implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithErrorWrapper) ServerRestart(ctx context.Context, server provisioning.Server, force bool) (bMCTaskMonitor *provisioning.BMCTaskMonitor, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.ServerRestart(ctx, server, force)
}

// ServerSetLocationIndicator implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithErrorWrapper) ServerSetLocationIndicator(ctx context.Context, server provisioning.Server, active bool) (err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.ServerSetLocationIndicator(ctx, server, active)
}

// TaskState implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithErrorWrapper) TaskState(ctx context.Context, server provisioning.Server, taskMonitor *provisioning.BMCTaskMonitor) (bMCTaskState api.BMCTaskState, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.TaskState(ctx, server, taskMonitor)
}

// WaitForTask implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithErrorWrapper) WaitForTask(ctx context.Context, server provisioning.Server, taskMonitor *provisioning.BMCTaskMonitor) (err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.WaitForTask(ctx, server, taskMonitor)
}
