// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/util/logger/slog.gotmpl

package middleware

import (
	"context"
	"log/slog"

	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/internal/util/logger"
	"github.com/FuturFusion/operations-center/shared/api"
)

// BMCServerClientPortWithSlog implements provisioning.BMCServerClientPort that is instrumented with slog logger.
type BMCServerClientPortWithSlog struct {
	_base                 provisioning.BMCServerClientPort
	_isInformativeErrFunc func(error) bool
}

type BMCServerClientPortWithSlogOption func(s *BMCServerClientPortWithSlog)

func BMCServerClientPortWithSlogWithInformativeErrFunc(isInformativeErrFunc func(error) bool) BMCServerClientPortWithSlogOption {
	return func(_base *BMCServerClientPortWithSlog) {
		_base._isInformativeErrFunc = isInformativeErrFunc
	}
}

// NewBMCServerClientPortWithSlog instruments an implementation of the provisioning.BMCServerClientPort with simple logging.
func NewBMCServerClientPortWithSlog(base provisioning.BMCServerClientPort, opts ...BMCServerClientPortWithSlogOption) BMCServerClientPortWithSlog {
	this := BMCServerClientPortWithSlog{
		_base:                 base,
		_isInformativeErrFunc: func(error) bool { return false },
	}

	for _, opt := range opts {
		opt(&this)
	}

	return this
}

// ApplyBIOSAttributes implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithSlog) ApplyBIOSAttributes(ctx context.Context, server provisioning.Server, attributes map[string]any) (bMCTaskMonitor *provisioning.BMCTaskMonitor, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.Any("attributes", attributes),
		)
	}
	log.DebugContext(ctx, "=> calling ApplyBIOSAttributes")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("bMCTaskMonitor", bMCTaskMonitor),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method ApplyBIOSAttributes returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method ApplyBIOSAttributes returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method ApplyBIOSAttributes finished")
		}
	}()
	return _d._base.ApplyBIOSAttributes(ctx, server, attributes)
}

// ApplySecureBootCertificates implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithSlog) ApplySecureBootCertificates(ctx context.Context, server provisioning.Server, secureBoot api.BIOSSecureBoot) (b bool, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.Any("secureBoot", secureBoot),
		)
	}
	log.DebugContext(ctx, "=> calling ApplySecureBootCertificates")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Bool("b", b),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method ApplySecureBootCertificates returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method ApplySecureBootCertificates returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method ApplySecureBootCertificates finished")
		}
	}()
	return _d._base.ApplySecureBootCertificates(ctx, server, secureBoot)
}

// AttachMedia implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithSlog) AttachMedia(ctx context.Context, server provisioning.Server, virtualMediaID string, mediaURL string, setBootDevice bool) (bMCTaskMonitor *provisioning.BMCTaskMonitor, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.String("virtualMediaID", virtualMediaID),
			slog.String("mediaURL", mediaURL),
			slog.Bool("setBootDevice", setBootDevice),
		)
	}
	log.DebugContext(ctx, "=> calling AttachMedia")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("bMCTaskMonitor", bMCTaskMonitor),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method AttachMedia returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method AttachMedia returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method AttachMedia finished")
		}
	}()
	return _d._base.AttachMedia(ctx, server, virtualMediaID, mediaURL, setBootDevice)
}

// BIOSAttribute implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithSlog) BIOSAttribute(ctx context.Context, server provisioning.Server, attributeName string) (bIOSAttribute api.BIOSAttribute, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.String("attributeName", attributeName),
		)
	}
	log.DebugContext(ctx, "=> calling BIOSAttribute")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("bIOSAttribute", bIOSAttribute),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method BIOSAttribute returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method BIOSAttribute returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method BIOSAttribute finished")
		}
	}()
	return _d._base.BIOSAttribute(ctx, server, attributeName)
}

// BIOSAttributes implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithSlog) BIOSAttributes(ctx context.Context, server provisioning.Server) (bIOSAttributes []api.BIOSAttribute, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
		)
	}
	log.DebugContext(ctx, "=> calling BIOSAttributes")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("bIOSAttributes", bIOSAttributes),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method BIOSAttributes returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method BIOSAttributes returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method BIOSAttributes finished")
		}
	}()
	return _d._base.BIOSAttributes(ctx, server)
}

// ConnectionTest implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithSlog) ConnectionTest(ctx context.Context, server provisioning.Server) (certificate string, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
		)
	}
	log.DebugContext(ctx, "=> calling ConnectionTest")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.String("certificate", certificate),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method ConnectionTest returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method ConnectionTest returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method ConnectionTest finished")
		}
	}()
	return _d._base.ConnectionTest(ctx, server)
}

// DetachMedia implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithSlog) DetachMedia(ctx context.Context, server provisioning.Server, virtualMediaID string) (bMCTaskMonitor *provisioning.BMCTaskMonitor, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.String("virtualMediaID", virtualMediaID),
		)
	}
	log.DebugContext(ctx, "=> calling DetachMedia")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("bMCTaskMonitor", bMCTaskMonitor),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method DetachMedia returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method DetachMedia returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method DetachMedia finished")
		}
	}()
	return _d._base.DetachMedia(ctx, server, virtualMediaID)
}

// Dump implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithSlog) Dump(ctx context.Context, server provisioning.Server, additionalEndpoints []string, skipPredefined bool, trace bool) (bMCDump api.BMCDump, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.Any("additionalEndpoints", additionalEndpoints),
			slog.Bool("skipPredefined", skipPredefined),
			slog.Bool("trace", trace),
		)
	}
	log.DebugContext(ctx, "=> calling Dump")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("bMCDump", bMCDump),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method Dump returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method Dump returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method Dump finished")
		}
	}()
	return _d._base.Dump(ctx, server, additionalEndpoints, skipPredefined, trace)
}

// GetData implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithSlog) GetData(ctx context.Context, server provisioning.Server) (bMCData api.BMCData, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
		)
	}
	log.DebugContext(ctx, "=> calling GetData")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("bMCData", bMCData),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetData returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetData returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetData finished")
		}
	}()
	return _d._base.GetData(ctx, server)
}

// LogEntriesBySource implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithSlog) LogEntriesBySource(ctx context.Context, server provisioning.Server, logSource string) (bMCLogEvents []api.BMCLogEvent, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.String("logSource", logSource),
		)
	}
	log.DebugContext(ctx, "=> calling LogEntriesBySource")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("bMCLogEvents", bMCLogEvents),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method LogEntriesBySource returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method LogEntriesBySource returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method LogEntriesBySource finished")
		}
	}()
	return _d._base.LogEntriesBySource(ctx, server, logSource)
}

// LogSources implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithSlog) LogSources(ctx context.Context, server provisioning.Server) (strings []string, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
		)
	}
	log.DebugContext(ctx, "=> calling LogSources")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("strings", strings),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method LogSources returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method LogSources returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method LogSources finished")
		}
	}()
	return _d._base.LogSources(ctx, server)
}

// ResetSecureBootKeys implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithSlog) ResetSecureBootKeys(ctx context.Context, server provisioning.Server) (b bool, bMCTaskMonitor *provisioning.BMCTaskMonitor, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
		)
	}
	log.DebugContext(ctx, "=> calling ResetSecureBootKeys")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Bool("b", b),
				slog.Any("bMCTaskMonitor", bMCTaskMonitor),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method ResetSecureBootKeys returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method ResetSecureBootKeys returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method ResetSecureBootKeys finished")
		}
	}()
	return _d._base.ResetSecureBootKeys(ctx, server)
}

// ServerPowerOff implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithSlog) ServerPowerOff(ctx context.Context, server provisioning.Server, force bool) (bMCTaskMonitor *provisioning.BMCTaskMonitor, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.Bool("force", force),
		)
	}
	log.DebugContext(ctx, "=> calling ServerPowerOff")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("bMCTaskMonitor", bMCTaskMonitor),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method ServerPowerOff returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method ServerPowerOff returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method ServerPowerOff finished")
		}
	}()
	return _d._base.ServerPowerOff(ctx, server, force)
}

// ServerPowerOn implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithSlog) ServerPowerOn(ctx context.Context, server provisioning.Server, force bool) (bMCTaskMonitor *provisioning.BMCTaskMonitor, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.Bool("force", force),
		)
	}
	log.DebugContext(ctx, "=> calling ServerPowerOn")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("bMCTaskMonitor", bMCTaskMonitor),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method ServerPowerOn returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method ServerPowerOn returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method ServerPowerOn finished")
		}
	}()
	return _d._base.ServerPowerOn(ctx, server, force)
}

// ServerRestart implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithSlog) ServerRestart(ctx context.Context, server provisioning.Server, force bool) (bMCTaskMonitor *provisioning.BMCTaskMonitor, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.Bool("force", force),
		)
	}
	log.DebugContext(ctx, "=> calling ServerRestart")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("bMCTaskMonitor", bMCTaskMonitor),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method ServerRestart returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method ServerRestart returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method ServerRestart finished")
		}
	}()
	return _d._base.ServerRestart(ctx, server, force)
}

// ServerSetLocationIndicator implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithSlog) ServerSetLocationIndicator(ctx context.Context, server provisioning.Server, active bool) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.Bool("active", active),
		)
	}
	log.DebugContext(ctx, "=> calling ServerSetLocationIndicator")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method ServerSetLocationIndicator returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method ServerSetLocationIndicator returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method ServerSetLocationIndicator finished")
		}
	}()
	return _d._base.ServerSetLocationIndicator(ctx, server, active)
}

// TaskState implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithSlog) TaskState(ctx context.Context, server provisioning.Server, taskMonitor *provisioning.BMCTaskMonitor) (bMCTaskState api.BMCTaskState, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.Any("taskMonitor", taskMonitor),
		)
	}
	log.DebugContext(ctx, "=> calling TaskState")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("bMCTaskState", bMCTaskState),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method TaskState returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method TaskState returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method TaskState finished")
		}
	}()
	return _d._base.TaskState(ctx, server, taskMonitor)
}

// WaitForTask implements provisioning.BMCServerClientPort.
func (_d BMCServerClientPortWithSlog) WaitForTask(ctx context.Context, server provisioning.Server, taskMonitor *provisioning.BMCTaskMonitor) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.Any("taskMonitor", taskMonitor),
		)
	}
	log.DebugContext(ctx, "=> calling WaitForTask")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method WaitForTask returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method WaitForTask returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method WaitForTask finished")
		}
	}()
	return _d._base.WaitForTask(ctx, server, taskMonitor)
}
