// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/util/logger/slog.gotmpl

package middleware

import (
	"context"
	"log/slog"

	"github.com/lxc/incus-os/incus-osd/api"

	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/internal/util/logger"
)

// SecureBootCertificateSourcePortWithSlog implements provisioning.SecureBootCertificateSourcePort that is instrumented with slog logger.
type SecureBootCertificateSourcePortWithSlog struct {
	_base                 provisioning.SecureBootCertificateSourcePort
	_isInformativeErrFunc func(error) bool
}

type SecureBootCertificateSourcePortWithSlogOption func(s *SecureBootCertificateSourcePortWithSlog)

func SecureBootCertificateSourcePortWithSlogWithInformativeErrFunc(isInformativeErrFunc func(error) bool) SecureBootCertificateSourcePortWithSlogOption {
	return func(_base *SecureBootCertificateSourcePortWithSlog) {
		_base._isInformativeErrFunc = isInformativeErrFunc
	}
}

// NewSecureBootCertificateSourcePortWithSlog instruments an implementation of the provisioning.SecureBootCertificateSourcePort with simple logging.
func NewSecureBootCertificateSourcePortWithSlog(base provisioning.SecureBootCertificateSourcePort, opts ...SecureBootCertificateSourcePortWithSlogOption) SecureBootCertificateSourcePortWithSlog {
	this := SecureBootCertificateSourcePortWithSlog{
		_base:                 base,
		_isInformativeErrFunc: func(error) bool { return false },
	}

	for _, opt := range opts {
		opt(&this)
	}

	return this
}

// GetSecureBootCertificates implements provisioning.SecureBootCertificateSourcePort.
func (_d SecureBootCertificateSourcePortWithSlog) GetSecureBootCertificates(ctx context.Context) (internalSecureBootCertificates api.InternalSecureBootCertificates, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
		)
	}
	log.DebugContext(ctx, "=> calling GetSecureBootCertificates")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("internalSecureBootCertificates", internalSecureBootCertificates),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetSecureBootCertificates returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetSecureBootCertificates returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetSecureBootCertificates finished")
		}
	}()
	return _d._base.GetSecureBootCertificates(ctx)
}
