// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/metrics/prometheus.gotmpl

package middleware

import (
	"context"
	"time"

	"github.com/lxc/incus-os/incus-osd/api/images"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"

	"github.com/FuturFusion/operations-center/internal/provisioning"
)

// SecureBootMediaPortWithPrometheus implements provisioning.SecureBootMediaPort interface with all methods wrapped
// with Prometheus metrics.
type SecureBootMediaPortWithPrometheus struct {
	base         provisioning.SecureBootMediaPort
	instanceName string
}

var secureBootMediaPortDurationSummaryVec = promauto.NewSummaryVec(
	prometheus.SummaryOpts{
		Name:       "secure_boot_media_port_duration_seconds",
		Help:       "secureBootMediaPort runtime duration and result",
		MaxAge:     time.Minute,
		Objectives: map[float64]float64{0.5: 0.05, 0.9: 0.01, 0.99: 0.001},
	},
	[]string{"instance_name", "method", "result"},
)

// NewSecureBootMediaPortWithPrometheus returns an instance of the provisioning.SecureBootMediaPort decorated with prometheus summary metric.
func NewSecureBootMediaPortWithPrometheus(base provisioning.SecureBootMediaPort, instanceName string) SecureBootMediaPortWithPrometheus {
	return SecureBootMediaPortWithPrometheus{
		base:         base,
		instanceName: instanceName,
	}
}

// Generate implements provisioning.SecureBootMediaPort.
func (_d SecureBootMediaPortWithPrometheus) Generate(ctx context.Context, architecture images.UpdateFileArchitecture, certificates provisioning.SecureBootCertificates) (s string, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		secureBootMediaPortDurationSummaryVec.WithLabelValues(_d.instanceName, "Generate", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Generate(ctx, architecture, certificates)
}

// Open implements provisioning.SecureBootMediaPort.
func (_d SecureBootMediaPortWithPrometheus) Open(ctx context.Context, id string) (secureBootMediaImage *provisioning.SecureBootMediaImage, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		secureBootMediaPortDurationSummaryVec.WithLabelValues(_d.instanceName, "Open", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Open(ctx, id)
}

// Prune implements provisioning.SecureBootMediaPort.
func (_d SecureBootMediaPortWithPrometheus) Prune(ctx context.Context, ttl time.Duration) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		secureBootMediaPortDurationSummaryVec.WithLabelValues(_d.instanceName, "Prune", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Prune(ctx, ttl)
}
