// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/util/logger/slog.gotmpl

package middleware

import (
	"context"
	"log/slog"

	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/internal/util/logger"
)

// SecureBootCertificateCataloguePortWithSlog implements provisioning.SecureBootCertificateCataloguePort that is instrumented with slog logger.
type SecureBootCertificateCataloguePortWithSlog struct {
	_base                 provisioning.SecureBootCertificateCataloguePort
	_isInformativeErrFunc func(error) bool
}

type SecureBootCertificateCataloguePortWithSlogOption func(s *SecureBootCertificateCataloguePortWithSlog)

func SecureBootCertificateCataloguePortWithSlogWithInformativeErrFunc(isInformativeErrFunc func(error) bool) SecureBootCertificateCataloguePortWithSlogOption {
	return func(_base *SecureBootCertificateCataloguePortWithSlog) {
		_base._isInformativeErrFunc = isInformativeErrFunc
	}
}

// NewSecureBootCertificateCataloguePortWithSlog instruments an implementation of the provisioning.SecureBootCertificateCataloguePort with simple logging.
func NewSecureBootCertificateCataloguePortWithSlog(base provisioning.SecureBootCertificateCataloguePort, opts ...SecureBootCertificateCataloguePortWithSlogOption) SecureBootCertificateCataloguePortWithSlog {
	this := SecureBootCertificateCataloguePortWithSlog{
		_base:                 base,
		_isInformativeErrFunc: func(error) bool { return false },
	}

	for _, opt := range opts {
		opt(&this)
	}

	return this
}

// CertificatesByFingerprint implements provisioning.SecureBootCertificateCataloguePort.
func (_d SecureBootCertificateCataloguePortWithSlog) CertificatesByFingerprint(fingerprints []string) (certificates []string, unknown []string) {
	ctx := context.Background()
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("fingerprints", fingerprints),
		)
	}
	log.DebugContext(ctx, "=> calling CertificatesByFingerprint")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("certificates", certificates),
				slog.Any("unknown", unknown),
			)
		} else {
		}
		log.DebugContext(ctx, "<= method CertificatesByFingerprint finished")
	}()
	return _d._base.CertificatesByFingerprint(fingerprints)
}
