// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/util/logger/slog.gotmpl

package middleware

import (
	"context"
	"log/slog"
	"time"

	"github.com/lxc/incus-os/incus-osd/api/images"

	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/internal/util/logger"
)

// SecureBootMediaPortWithSlog implements provisioning.SecureBootMediaPort that is instrumented with slog logger.
type SecureBootMediaPortWithSlog struct {
	_base                 provisioning.SecureBootMediaPort
	_isInformativeErrFunc func(error) bool
}

type SecureBootMediaPortWithSlogOption func(s *SecureBootMediaPortWithSlog)

func SecureBootMediaPortWithSlogWithInformativeErrFunc(isInformativeErrFunc func(error) bool) SecureBootMediaPortWithSlogOption {
	return func(_base *SecureBootMediaPortWithSlog) {
		_base._isInformativeErrFunc = isInformativeErrFunc
	}
}

// NewSecureBootMediaPortWithSlog instruments an implementation of the provisioning.SecureBootMediaPort with simple logging.
func NewSecureBootMediaPortWithSlog(base provisioning.SecureBootMediaPort, opts ...SecureBootMediaPortWithSlogOption) SecureBootMediaPortWithSlog {
	this := SecureBootMediaPortWithSlog{
		_base:                 base,
		_isInformativeErrFunc: func(error) bool { return false },
	}

	for _, opt := range opts {
		opt(&this)
	}

	return this
}

// Generate implements provisioning.SecureBootMediaPort.
func (_d SecureBootMediaPortWithSlog) Generate(ctx context.Context, architecture images.UpdateFileArchitecture, certificates provisioning.SecureBootCertificates) (s string, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("architecture", architecture),
			slog.Any("certificates", certificates),
		)
	}
	log.DebugContext(ctx, "=> calling Generate")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.String("s", s),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method Generate returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method Generate returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method Generate finished")
		}
	}()
	return _d._base.Generate(ctx, architecture, certificates)
}

// Open implements provisioning.SecureBootMediaPort.
func (_d SecureBootMediaPortWithSlog) Open(ctx context.Context, id string) (secureBootMediaImage *provisioning.SecureBootMediaImage, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("id", id),
		)
	}
	log.DebugContext(ctx, "=> calling Open")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("secureBootMediaImage", secureBootMediaImage),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method Open returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method Open returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method Open finished")
		}
	}()
	return _d._base.Open(ctx, id)
}

// Prune implements provisioning.SecureBootMediaPort.
func (_d SecureBootMediaPortWithSlog) Prune(ctx context.Context, ttl time.Duration) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Duration("ttl", ttl),
		)
	}
	log.DebugContext(ctx, "=> calling Prune")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method Prune returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method Prune returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method Prune finished")
		}
	}()
	return _d._base.Prune(ctx, ttl)
}
