// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/metrics/prometheus.gotmpl

package middleware

import (
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"

	"github.com/FuturFusion/operations-center/internal/provisioning"
)

// SecureBootCertificateCataloguePortWithPrometheus implements provisioning.SecureBootCertificateCataloguePort interface with all methods wrapped
// with Prometheus metrics.
type SecureBootCertificateCataloguePortWithPrometheus struct {
	base         provisioning.SecureBootCertificateCataloguePort
	instanceName string
}

var secureBootCertificateCataloguePortDurationSummaryVec = promauto.NewSummaryVec(
	prometheus.SummaryOpts{
		Name:       "secure_boot_certificate_catalogue_port_duration_seconds",
		Help:       "secureBootCertificateCataloguePort runtime duration and result",
		MaxAge:     time.Minute,
		Objectives: map[float64]float64{0.5: 0.05, 0.9: 0.01, 0.99: 0.001},
	},
	[]string{"instance_name", "method", "result"},
)

// NewSecureBootCertificateCataloguePortWithPrometheus returns an instance of the provisioning.SecureBootCertificateCataloguePort decorated with prometheus summary metric.
func NewSecureBootCertificateCataloguePortWithPrometheus(base provisioning.SecureBootCertificateCataloguePort, instanceName string) SecureBootCertificateCataloguePortWithPrometheus {
	return SecureBootCertificateCataloguePortWithPrometheus{
		base:         base,
		instanceName: instanceName,
	}
}

// CertificatesByFingerprint implements provisioning.SecureBootCertificateCataloguePort.
func (_d SecureBootCertificateCataloguePortWithPrometheus) CertificatesByFingerprint(fingerprints []string) (certificates []string, unknown []string) {
	_since := time.Now()
	defer func() {
		result := "ok"
		secureBootCertificateCataloguePortDurationSummaryVec.WithLabelValues(_d.instanceName, "CertificatesByFingerprint", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.CertificatesByFingerprint(fingerprints)
}
