// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/metrics/prometheus.gotmpl

package middleware

import (
	"context"
	"time"

	"github.com/lxc/incus-os/incus-osd/api"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"

	"github.com/FuturFusion/operations-center/internal/provisioning"
)

// SecureBootCertificateSourcePortWithPrometheus implements provisioning.SecureBootCertificateSourcePort interface with all methods wrapped
// with Prometheus metrics.
type SecureBootCertificateSourcePortWithPrometheus struct {
	base         provisioning.SecureBootCertificateSourcePort
	instanceName string
}

var secureBootCertificateSourcePortDurationSummaryVec = promauto.NewSummaryVec(
	prometheus.SummaryOpts{
		Name:       "secure_boot_certificate_source_port_duration_seconds",
		Help:       "secureBootCertificateSourcePort runtime duration and result",
		MaxAge:     time.Minute,
		Objectives: map[float64]float64{0.5: 0.05, 0.9: 0.01, 0.99: 0.001},
	},
	[]string{"instance_name", "method", "result"},
)

// NewSecureBootCertificateSourcePortWithPrometheus returns an instance of the provisioning.SecureBootCertificateSourcePort decorated with prometheus summary metric.
func NewSecureBootCertificateSourcePortWithPrometheus(base provisioning.SecureBootCertificateSourcePort, instanceName string) SecureBootCertificateSourcePortWithPrometheus {
	return SecureBootCertificateSourcePortWithPrometheus{
		base:         base,
		instanceName: instanceName,
	}
}

// GetSecureBootCertificates implements provisioning.SecureBootCertificateSourcePort.
func (_d SecureBootCertificateSourcePortWithPrometheus) GetSecureBootCertificates(ctx context.Context) (internalSecureBootCertificates api.InternalSecureBootCertificates, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		secureBootCertificateSourcePortDurationSummaryVec.WithLabelValues(_d.instanceName, "GetSecureBootCertificates", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetSecureBootCertificates(ctx)
}
