// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/metrics/prometheus.gotmpl

package middleware

import (
	"context"
	"io"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"

	"github.com/FuturFusion/operations-center/internal/provisioning"
)

// SeedImageProgressPortWithPrometheus implements provisioning.SeedImageProgressPort interface with all methods wrapped
// with Prometheus metrics.
type SeedImageProgressPortWithPrometheus struct {
	base         provisioning.SeedImageProgressPort
	instanceName string
}

var seedImageProgressPortDurationSummaryVec = promauto.NewSummaryVec(
	prometheus.SummaryOpts{
		Name:       "seed_image_progress_port_duration_seconds",
		Help:       "seedImageProgressPort runtime duration and result",
		MaxAge:     time.Minute,
		Objectives: map[float64]float64{0.5: 0.05, 0.9: 0.01, 0.99: 0.001},
	},
	[]string{"instance_name", "method", "result"},
)

// NewSeedImageProgressPortWithPrometheus returns an instance of the provisioning.SeedImageProgressPort decorated with prometheus summary metric.
func NewSeedImageProgressPortWithPrometheus(base provisioning.SeedImageProgressPort, instanceName string) SeedImageProgressPortWithPrometheus {
	return SeedImageProgressPortWithPrometheus{
		base:         base,
		instanceName: instanceName,
	}
}

// Get implements provisioning.SeedImageProgressPort.
func (_d SeedImageProgressPortWithPrometheus) Get(ctx context.Context, deploymentID string) (seedImageProgress provisioning.SeedImageProgress, b bool) {
	_since := time.Now()
	defer func() {
		result := "ok"
		seedImageProgressPortDurationSummaryVec.WithLabelValues(_d.instanceName, "Get", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Get(ctx, deploymentID)
}

// Reset implements provisioning.SeedImageProgressPort.
func (_d SeedImageProgressPortWithPrometheus) Reset(ctx context.Context, deploymentID string) {
	_since := time.Now()
	defer func() {
		result := "ok"
		seedImageProgressPortDurationSummaryVec.WithLabelValues(_d.instanceName, "Reset", result).Observe(time.Since(_since).Seconds())
	}()
	_d.base.Reset(ctx, deploymentID)
}

// Track implements provisioning.SeedImageProgressPort.
func (_d SeedImageProgressPortWithPrometheus) Track(ctx context.Context, deploymentID string, info provisioning.SeedImageInfo, content io.ReadSeekCloser) (readSeekCloser io.ReadSeekCloser) {
	_since := time.Now()
	defer func() {
		result := "ok"
		seedImageProgressPortDurationSummaryVec.WithLabelValues(_d.instanceName, "Track", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Track(ctx, deploymentID, info, content)
}
