// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/util/logger/slog.gotmpl

package middleware

import (
	"context"
	"io"
	"log/slog"

	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/internal/util/logger"
)

// SeedImageProgressPortWithSlog implements provisioning.SeedImageProgressPort that is instrumented with slog logger.
type SeedImageProgressPortWithSlog struct {
	_base                 provisioning.SeedImageProgressPort
	_isInformativeErrFunc func(error) bool
}

type SeedImageProgressPortWithSlogOption func(s *SeedImageProgressPortWithSlog)

func SeedImageProgressPortWithSlogWithInformativeErrFunc(isInformativeErrFunc func(error) bool) SeedImageProgressPortWithSlogOption {
	return func(_base *SeedImageProgressPortWithSlog) {
		_base._isInformativeErrFunc = isInformativeErrFunc
	}
}

// NewSeedImageProgressPortWithSlog instruments an implementation of the provisioning.SeedImageProgressPort with simple logging.
func NewSeedImageProgressPortWithSlog(base provisioning.SeedImageProgressPort, opts ...SeedImageProgressPortWithSlogOption) SeedImageProgressPortWithSlog {
	this := SeedImageProgressPortWithSlog{
		_base:                 base,
		_isInformativeErrFunc: func(error) bool { return false },
	}

	for _, opt := range opts {
		opt(&this)
	}

	return this
}

// Get implements provisioning.SeedImageProgressPort.
func (_d SeedImageProgressPortWithSlog) Get(ctx context.Context, deploymentID string) (seedImageProgress provisioning.SeedImageProgress, b bool) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("deploymentID", deploymentID),
		)
	}
	log.DebugContext(ctx, "=> calling Get")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("seedImageProgress", seedImageProgress),
				slog.Bool("b", b),
			)
		} else {
		}
		log.DebugContext(ctx, "<= method Get finished")
	}()
	return _d._base.Get(ctx, deploymentID)
}

// Reset implements provisioning.SeedImageProgressPort.
func (_d SeedImageProgressPortWithSlog) Reset(ctx context.Context, deploymentID string) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("deploymentID", deploymentID),
		)
	}
	log.DebugContext(ctx, "=> calling Reset")
	defer func() {
		log := slog.With()
		log.DebugContext(ctx, "<= method Reset finished")
	}()
	_d._base.Reset(ctx, deploymentID)
}

// Track implements provisioning.SeedImageProgressPort.
func (_d SeedImageProgressPortWithSlog) Track(ctx context.Context, deploymentID string, info provisioning.SeedImageInfo, content io.ReadSeekCloser) (readSeekCloser io.ReadSeekCloser) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("deploymentID", deploymentID),
			slog.Any("info", info),
			slog.Any("content", content),
		)
	}
	log.DebugContext(ctx, "=> calling Track")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("readSeekCloser", readSeekCloser),
			)
		} else {
		}
		log.DebugContext(ctx, "<= method Track finished")
	}()
	return _d._base.Track(ctx, deploymentID, info, content)
}
