// Code generated by generate-database from the incus project - DO NOT EDIT.

package entities

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/FuturFusion/operations-center/internal/provisioning"
)

var serverObjects = RegisterStmt(`
SELECT servers.id, clusters.name AS cluster, servers.name, servers.type, servers.connection_url, servers.public_connection_url, servers.certificate, clusters.certificate AS cluster_certificate, clusters.connection_url AS cluster_connection_url, servers.hardware_data, servers.os_data, servers.status, servers.last_updated, servers.last_seen
  FROM servers
  LEFT JOIN clusters ON servers.cluster_id = clusters.id
  ORDER BY servers.name
`)

var serverObjectsByName = RegisterStmt(`
SELECT servers.id, clusters.name AS cluster, servers.name, servers.type, servers.connection_url, servers.public_connection_url, servers.certificate, clusters.certificate AS cluster_certificate, clusters.connection_url AS cluster_connection_url, servers.hardware_data, servers.os_data, servers.status, servers.last_updated, servers.last_seen
  FROM servers
  LEFT JOIN clusters ON servers.cluster_id = clusters.id
  WHERE ( servers.name = ? )
  ORDER BY servers.name
`)

var serverObjectsByCluster = RegisterStmt(`
SELECT servers.id, clusters.name AS cluster, servers.name, servers.type, servers.connection_url, servers.public_connection_url, servers.certificate, clusters.certificate AS cluster_certificate, clusters.connection_url AS cluster_connection_url, servers.hardware_data, servers.os_data, servers.status, servers.last_updated, servers.last_seen
  FROM servers
  LEFT JOIN clusters ON servers.cluster_id = clusters.id
  WHERE ( cluster = ? )
  ORDER BY servers.name
`)

var serverObjectsByClusterAndStatus = RegisterStmt(`
SELECT servers.id, clusters.name AS cluster, servers.name, servers.type, servers.connection_url, servers.public_connection_url, servers.certificate, clusters.certificate AS cluster_certificate, clusters.connection_url AS cluster_connection_url, servers.hardware_data, servers.os_data, servers.status, servers.last_updated, servers.last_seen
  FROM servers
  LEFT JOIN clusters ON servers.cluster_id = clusters.id
  WHERE ( cluster = ? AND servers.status = ? )
  ORDER BY servers.name
`)

var serverObjectsByStatus = RegisterStmt(`
SELECT servers.id, clusters.name AS cluster, servers.name, servers.type, servers.connection_url, servers.public_connection_url, servers.certificate, clusters.certificate AS cluster_certificate, clusters.connection_url AS cluster_connection_url, servers.hardware_data, servers.os_data, servers.status, servers.last_updated, servers.last_seen
  FROM servers
  LEFT JOIN clusters ON servers.cluster_id = clusters.id
  WHERE ( servers.status = ? )
  ORDER BY servers.name
`)

var serverObjectsByCertificate = RegisterStmt(`
SELECT servers.id, clusters.name AS cluster, servers.name, servers.type, servers.connection_url, servers.public_connection_url, servers.certificate, clusters.certificate AS cluster_certificate, clusters.connection_url AS cluster_connection_url, servers.hardware_data, servers.os_data, servers.status, servers.last_updated, servers.last_seen
  FROM servers
  LEFT JOIN clusters ON servers.cluster_id = clusters.id
  WHERE ( servers.certificate = ? )
  ORDER BY servers.name
`)

var serverObjectsByType = RegisterStmt(`
SELECT servers.id, clusters.name AS cluster, servers.name, servers.type, servers.connection_url, servers.public_connection_url, servers.certificate, clusters.certificate AS cluster_certificate, clusters.connection_url AS cluster_connection_url, servers.hardware_data, servers.os_data, servers.status, servers.last_updated, servers.last_seen
  FROM servers
  LEFT JOIN clusters ON servers.cluster_id = clusters.id
  WHERE ( servers.type = ? )
  ORDER BY servers.name
`)

var serverNames = RegisterStmt(`
SELECT servers.name
  FROM servers
  ORDER BY servers.name
`)

var serverNamesByCluster = RegisterStmt(`
SELECT servers.name
  FROM servers
  LEFT JOIN clusters ON servers.cluster_id = clusters.id
  WHERE ( clusters.name = ? )
  ORDER BY servers.name
`)

var serverID = RegisterStmt(`
SELECT servers.id FROM servers
  WHERE servers.name = ?
`)

var serverCreate = RegisterStmt(`
INSERT INTO servers (cluster_id, name, type, connection_url, public_connection_url, certificate, hardware_data, os_data, status, last_updated, last_seen)
  VALUES ((SELECT clusters.id FROM clusters WHERE clusters.name = ?), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`)

var serverUpdate = RegisterStmt(`
UPDATE servers
  SET cluster_id = (SELECT clusters.id FROM clusters WHERE clusters.name = ?), name = ?, type = ?, connection_url = ?, public_connection_url = ?, certificate = ?, hardware_data = ?, os_data = ?, status = ?, last_updated = ?, last_seen = ?
 WHERE id = ?
`)

var serverRename = RegisterStmt(`
UPDATE servers SET name = ?, last_updated = ? WHERE name = ?
`)

var serverDeleteByName = RegisterStmt(`
DELETE FROM servers WHERE name = ?
`)

// GetServerID return the ID of the server with the given key.
// generator: server ID
func GetServerID(ctx context.Context, db tx, name string) (_ int64, _err error) {
	defer func() {
		_err = mapErr(_err, "Server")
	}()

	stmt, err := Stmt(db, serverID)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"serverID\" prepared statement: %w", err)
	}

	row := stmt.QueryRowContext(ctx, name)
	var id int64
	err = row.Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return -1, ErrNotFound
	}

	if err != nil {
		return -1, fmt.Errorf("Failed to get \"servers\" ID: %w", err)
	}

	return id, nil
}

// ServerExists checks if a server with the given key exists.
// generator: server Exists
func ServerExists(ctx context.Context, db dbtx, name string) (_ bool, _err error) {
	defer func() {
		_err = mapErr(_err, "Server")
	}()

	stmt, err := Stmt(db, serverID)
	if err != nil {
		return false, fmt.Errorf("Failed to get \"serverID\" prepared statement: %w", err)
	}

	row := stmt.QueryRowContext(ctx, name)
	var id int64
	err = row.Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return false, nil
	}

	if err != nil {
		return false, fmt.Errorf("Failed to get \"servers\" ID: %w", err)
	}

	return true, nil
}

// GetServer returns the server with the given key.
// generator: server GetOne
func GetServer(ctx context.Context, db dbtx, name string) (_ *provisioning.Server, _err error) {
	defer func() {
		_err = mapErr(_err, "Server")
	}()

	filter := provisioning.ServerFilter{}
	filter.Name = &name

	objects, err := GetServers(ctx, db, filter)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"servers\" table: %w", err)
	}

	switch len(objects) {
	case 0:
		return nil, ErrNotFound
	case 1:
		return &objects[0], nil
	default:
		return nil, fmt.Errorf("More than one \"servers\" entry matches")
	}
}

// serverColumns returns a string of column names to be used with a SELECT statement for the entity.
// Use this function when building statements to retrieve database entries matching the Server entity.
func serverColumns() string {
	return "servers.id, clusters.name AS cluster, servers.name, servers.type, servers.connection_url, servers.public_connection_url, servers.certificate, clusters.certificate AS cluster_certificate, clusters.connection_url AS cluster_connection_url, servers.hardware_data, servers.os_data, servers.status, servers.last_updated, servers.last_seen"
}

// getServers can be used to run handwritten sql.Stmts to return a slice of objects.
func getServers(ctx context.Context, stmt *sql.Stmt, args ...any) ([]provisioning.Server, error) {
	objects := make([]provisioning.Server, 0)

	dest := func(scan func(dest ...any) error) error {
		s := provisioning.Server{}
		err := scan(&s.ID, &s.Cluster, &s.Name, &s.Type, &s.ConnectionURL, &s.PublicConnectionURL, &s.Certificate, &s.ClusterCertificate, &s.ClusterConnectionURL, &s.HardwareData, &s.OSData, &s.Status, &s.LastUpdated, &s.LastSeen)
		if err != nil {
			return err
		}

		objects = append(objects, s)

		return nil
	}

	err := selectObjects(ctx, stmt, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"servers\" table: %w", err)
	}

	return objects, nil
}

// getServersRaw can be used to run handwritten query strings to return a slice of objects.
func getServersRaw(ctx context.Context, db dbtx, sql string, args ...any) ([]provisioning.Server, error) {
	objects := make([]provisioning.Server, 0)

	dest := func(scan func(dest ...any) error) error {
		s := provisioning.Server{}
		err := scan(&s.ID, &s.Cluster, &s.Name, &s.Type, &s.ConnectionURL, &s.PublicConnectionURL, &s.Certificate, &s.ClusterCertificate, &s.ClusterConnectionURL, &s.HardwareData, &s.OSData, &s.Status, &s.LastUpdated, &s.LastSeen)
		if err != nil {
			return err
		}

		objects = append(objects, s)

		return nil
	}

	err := scan(ctx, db, sql, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"servers\" table: %w", err)
	}

	return objects, nil
}

// GetServers returns all available servers.
// generator: server GetMany
func GetServers(ctx context.Context, db dbtx, filters ...provisioning.ServerFilter) (_ []provisioning.Server, _err error) {
	defer func() {
		_err = mapErr(_err, "Server")
	}()

	var err error

	// Result slice.
	objects := make([]provisioning.Server, 0)

	// Pick the prepared statement and arguments to use based on active criteria.
	var sqlStmt *sql.Stmt
	args := []any{}
	queryParts := [2]string{}

	if len(filters) == 0 {
		sqlStmt, err = Stmt(db, serverObjects)
		if err != nil {
			return nil, fmt.Errorf("Failed to get \"serverObjects\" prepared statement: %w", err)
		}
	}

	for i, filter := range filters {
		if filter.Cluster != nil && filter.Status != nil && filter.Name == nil && filter.Certificate == nil && filter.Type == nil {
			args = append(args, []any{filter.Cluster, filter.Status}...)
			if len(filters) == 1 {
				sqlStmt, err = Stmt(db, serverObjectsByClusterAndStatus)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"serverObjectsByClusterAndStatus\" prepared statement: %w", err)
				}

				break
			}

			query, err := StmtString(serverObjectsByClusterAndStatus)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"serverObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.Type != nil && filter.Name == nil && filter.Cluster == nil && filter.Status == nil && filter.Certificate == nil {
			args = append(args, []any{filter.Type}...)
			if len(filters) == 1 {
				sqlStmt, err = Stmt(db, serverObjectsByType)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"serverObjectsByType\" prepared statement: %w", err)
				}

				break
			}

			query, err := StmtString(serverObjectsByType)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"serverObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.Status != nil && filter.Name == nil && filter.Cluster == nil && filter.Certificate == nil && filter.Type == nil {
			args = append(args, []any{filter.Status}...)
			if len(filters) == 1 {
				sqlStmt, err = Stmt(db, serverObjectsByStatus)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"serverObjectsByStatus\" prepared statement: %w", err)
				}

				break
			}

			query, err := StmtString(serverObjectsByStatus)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"serverObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.Name != nil && filter.Cluster == nil && filter.Status == nil && filter.Certificate == nil && filter.Type == nil {
			args = append(args, []any{filter.Name}...)
			if len(filters) == 1 {
				sqlStmt, err = Stmt(db, serverObjectsByName)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"serverObjectsByName\" prepared statement: %w", err)
				}

				break
			}

			query, err := StmtString(serverObjectsByName)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"serverObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.Cluster != nil && filter.Name == nil && filter.Status == nil && filter.Certificate == nil && filter.Type == nil {
			args = append(args, []any{filter.Cluster}...)
			if len(filters) == 1 {
				sqlStmt, err = Stmt(db, serverObjectsByCluster)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"serverObjectsByCluster\" prepared statement: %w", err)
				}

				break
			}

			query, err := StmtString(serverObjectsByCluster)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"serverObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.Certificate != nil && filter.Name == nil && filter.Cluster == nil && filter.Status == nil && filter.Type == nil {
			args = append(args, []any{filter.Certificate}...)
			if len(filters) == 1 {
				sqlStmt, err = Stmt(db, serverObjectsByCertificate)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"serverObjectsByCertificate\" prepared statement: %w", err)
				}

				break
			}

			query, err := StmtString(serverObjectsByCertificate)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"serverObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.Name == nil && filter.Cluster == nil && filter.Status == nil && filter.Certificate == nil && filter.Type == nil {
			return nil, fmt.Errorf("Cannot filter on empty ServerFilter")
		} else {
			return nil, errors.New("No statement exists for the given Filter")
		}
	}

	// Select.
	if sqlStmt != nil {
		objects, err = getServers(ctx, sqlStmt, args...)
	} else {
		queryStr := strings.Join(queryParts[:], "ORDER BY")
		objects, err = getServersRaw(ctx, db, queryStr, args...)
	}

	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"servers\" table: %w", err)
	}

	return objects, nil
}

// GetServerNames returns the identifying field of server.
// generator: server GetNames
func GetServerNames(ctx context.Context, db dbtx, filters ...provisioning.ServerFilter) (_ []string, _err error) {
	defer func() {
		_err = mapErr(_err, "Server")
	}()

	var err error

	// Result slice.
	names := make([]string, 0)

	// Pick the prepared statement and arguments to use based on active criteria.
	var sqlStmt *sql.Stmt
	args := []any{}
	queryParts := [2]string{}

	if len(filters) == 0 {
		sqlStmt, err = Stmt(db, serverNames)
		if err != nil {
			return nil, fmt.Errorf("Failed to get \"serverNames\" prepared statement: %w", err)
		}
	}

	for i, filter := range filters {
		if filter.Cluster != nil && filter.Name == nil && filter.Status == nil && filter.Certificate == nil && filter.Type == nil {
			args = append(args, []any{filter.Cluster}...)
			if len(filters) == 1 {
				sqlStmt, err = Stmt(db, serverNamesByCluster)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"serverNamesByCluster\" prepared statement: %w", err)
				}

				break
			}

			query, err := StmtString(serverNamesByCluster)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"serverNames\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.Name == nil && filter.Cluster == nil && filter.Status == nil && filter.Certificate == nil && filter.Type == nil {
			return nil, fmt.Errorf("Cannot filter on empty ServerFilter")
		} else {
			return nil, errors.New("No statement exists for the given Filter")
		}
	}

	// Select.
	var rows *sql.Rows
	if sqlStmt != nil {
		rows, err = sqlStmt.QueryContext(ctx, args...)
	} else {
		queryStr := strings.Join(queryParts[:], "ORDER BY")
		rows, err = db.QueryContext(ctx, queryStr, args...)
	}

	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()
	for rows.Next() {
		var identifier string
		err := rows.Scan(&identifier)
		if err != nil {
			return nil, err
		}

		names = append(names, identifier)
	}

	err = rows.Err()
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"servers\" table: %w", err)
	}

	return names, nil
}

// CreateServer adds a new server to the database.
// generator: server Create
func CreateServer(ctx context.Context, db dbtx, object provisioning.Server) (_ int64, _err error) {
	defer func() {
		_err = mapErr(_err, "Server")
	}()

	args := make([]any, 11)

	// Populate the statement arguments.
	args[0] = object.Cluster
	args[1] = object.Name
	args[2] = object.Type
	args[3] = object.ConnectionURL
	args[4] = object.PublicConnectionURL
	args[5] = object.Certificate
	args[6] = object.HardwareData
	args[7] = object.OSData
	args[8] = object.Status
	args[9] = time.Now().UTC().Format(time.RFC3339)
	args[10] = object.LastSeen

	// Prepared statement to use.
	stmt, err := Stmt(db, serverCreate)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"serverCreate\" prepared statement: %w", err)
	}

	// Execute the statement.
	result, err := stmt.Exec(args...)
	if err != nil && strings.HasPrefix(err.Error(), "UNIQUE constraint failed:") {
		return -1, ErrConflict
	}

	if err != nil {
		return -1, fmt.Errorf("Failed to create \"servers\" entry: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return -1, fmt.Errorf("Failed to fetch \"servers\" entry ID: %w", err)
	}

	return id, nil
}

// UpdateServer updates the server matching the given key parameters.
// generator: server Update
func UpdateServer(ctx context.Context, db tx, name string, object provisioning.Server) (_err error) {
	defer func() {
		_err = mapErr(_err, "Server")
	}()

	id, err := GetServerID(ctx, db, name)
	if err != nil {
		return err
	}

	stmt, err := Stmt(db, serverUpdate)
	if err != nil {
		return fmt.Errorf("Failed to get \"serverUpdate\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(object.Cluster, object.Name, object.Type, object.ConnectionURL, object.PublicConnectionURL, object.Certificate, object.HardwareData, object.OSData, object.Status, time.Now().UTC().Format(time.RFC3339), object.LastSeen, id)
	if err != nil {
		return fmt.Errorf("Update \"servers\" entry failed: %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n != 1 {
		return fmt.Errorf("Query updated %d rows instead of 1", n)
	}

	return nil
}

// RenameServer renames the server matching the given key parameters.
// generator: server Rename
func RenameServer(ctx context.Context, db dbtx, name string, to string) (_err error) {
	defer func() {
		_err = mapErr(_err, "Server")
	}()

	stmt, err := Stmt(db, serverRename)
	if err != nil {
		return fmt.Errorf("Failed to get \"serverRename\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(to, time.Now().UTC().Format(time.RFC3339), name)
	if err != nil {
		return fmt.Errorf("Rename Server failed: %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows failed: %w", err)
	}

	if n != 1 {
		return fmt.Errorf("Query affected %d rows instead of 1", n)
	}

	return nil
}

// DeleteServer deletes the server matching the given key parameters.
// generator: server DeleteOne-by-Name
func DeleteServer(ctx context.Context, db dbtx, name string) (_err error) {
	defer func() {
		_err = mapErr(_err, "Server")
	}()

	stmt, err := Stmt(db, serverDeleteByName)
	if err != nil {
		return fmt.Errorf("Failed to get \"serverDeleteByName\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(name)
	if err != nil {
		return fmt.Errorf("Delete \"servers\": %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n == 0 {
		return ErrNotFound
	} else if n > 1 {
		return fmt.Errorf("Query deleted %d Server rows instead of 1", n)
	}

	return nil
}
