// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package mock

import (
	"context"
	"sync"

	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/shared/api"
)

// Ensure that BMCServerClientPortMock does implement provisioning.BMCServerClientPort.
// If this is not the case, regenerate this file with mockery.
var _ provisioning.BMCServerClientPort = &BMCServerClientPortMock{}

// BMCServerClientPortMock is a mock implementation of provisioning.BMCServerClientPort.
//
//	func TestSomethingThatUsesBMCServerClientPort(t *testing.T) {
//
//		// make and configure a mocked provisioning.BMCServerClientPort
//		mockedBMCServerClientPort := &BMCServerClientPortMock{
//			ApplyBIOSAttributesFunc: func(ctx context.Context, server provisioning.Server, attributes map[string]any) (*provisioning.BMCTaskMonitor, error) {
//				panic("mock out the ApplyBIOSAttributes method")
//			},
//			ApplySecureBootCertificatesFunc: func(ctx context.Context, server provisioning.Server, secureBoot api.BIOSSecureBoot) (bool, error) {
//				panic("mock out the ApplySecureBootCertificates method")
//			},
//			AttachMediaFunc: func(ctx context.Context, server provisioning.Server, virtualMediaID string, mediaURL string, setBootDevice bool) (*provisioning.BMCTaskMonitor, error) {
//				panic("mock out the AttachMedia method")
//			},
//			BIOSAttributeFunc: func(ctx context.Context, server provisioning.Server, attributeName string) (api.BIOSAttribute, error) {
//				panic("mock out the BIOSAttribute method")
//			},
//			BIOSAttributesFunc: func(ctx context.Context, server provisioning.Server) ([]api.BIOSAttribute, error) {
//				panic("mock out the BIOSAttributes method")
//			},
//			ConnectionTestFunc: func(ctx context.Context, server provisioning.Server) (string, error) {
//				panic("mock out the ConnectionTest method")
//			},
//			DetachMediaFunc: func(ctx context.Context, server provisioning.Server, virtualMediaID string) (*provisioning.BMCTaskMonitor, error) {
//				panic("mock out the DetachMedia method")
//			},
//			DumpFunc: func(ctx context.Context, server provisioning.Server, additionalEndpoints []string, skipPredefined bool, trace bool) (api.BMCDump, error) {
//				panic("mock out the Dump method")
//			},
//			GetDataFunc: func(ctx context.Context, server provisioning.Server) (api.BMCData, error) {
//				panic("mock out the GetData method")
//			},
//			LogEntriesBySourceFunc: func(ctx context.Context, server provisioning.Server, logSource string) ([]api.BMCLogEvent, error) {
//				panic("mock out the LogEntriesBySource method")
//			},
//			LogSourcesFunc: func(ctx context.Context, server provisioning.Server) ([]string, error) {
//				panic("mock out the LogSources method")
//			},
//			ResetSecureBootKeysFunc: func(ctx context.Context, server provisioning.Server) (bool, *provisioning.BMCTaskMonitor, error) {
//				panic("mock out the ResetSecureBootKeys method")
//			},
//			ServerPowerOffFunc: func(ctx context.Context, server provisioning.Server, force bool) (*provisioning.BMCTaskMonitor, error) {
//				panic("mock out the ServerPowerOff method")
//			},
//			ServerPowerOnFunc: func(ctx context.Context, server provisioning.Server, force bool) (*provisioning.BMCTaskMonitor, error) {
//				panic("mock out the ServerPowerOn method")
//			},
//			ServerRestartFunc: func(ctx context.Context, server provisioning.Server, force bool) (*provisioning.BMCTaskMonitor, error) {
//				panic("mock out the ServerRestart method")
//			},
//			ServerSetLocationIndicatorFunc: func(ctx context.Context, server provisioning.Server, active bool) error {
//				panic("mock out the ServerSetLocationIndicator method")
//			},
//			TaskStateFunc: func(ctx context.Context, server provisioning.Server, taskMonitor *provisioning.BMCTaskMonitor) (api.BMCTaskState, error) {
//				panic("mock out the TaskState method")
//			},
//			WaitForTaskFunc: func(ctx context.Context, server provisioning.Server, taskMonitor *provisioning.BMCTaskMonitor) error {
//				panic("mock out the WaitForTask method")
//			},
//		}
//
//		// use mockedBMCServerClientPort in code that requires provisioning.BMCServerClientPort
//		// and then make assertions.
//
//	}
type BMCServerClientPortMock struct {
	// ApplyBIOSAttributesFunc mocks the ApplyBIOSAttributes method.
	ApplyBIOSAttributesFunc func(ctx context.Context, server provisioning.Server, attributes map[string]any) (*provisioning.BMCTaskMonitor, error)

	// ApplySecureBootCertificatesFunc mocks the ApplySecureBootCertificates method.
	ApplySecureBootCertificatesFunc func(ctx context.Context, server provisioning.Server, secureBoot api.BIOSSecureBoot) (bool, error)

	// AttachMediaFunc mocks the AttachMedia method.
	AttachMediaFunc func(ctx context.Context, server provisioning.Server, virtualMediaID string, mediaURL string, setBootDevice bool) (*provisioning.BMCTaskMonitor, error)

	// BIOSAttributeFunc mocks the BIOSAttribute method.
	BIOSAttributeFunc func(ctx context.Context, server provisioning.Server, attributeName string) (api.BIOSAttribute, error)

	// BIOSAttributesFunc mocks the BIOSAttributes method.
	BIOSAttributesFunc func(ctx context.Context, server provisioning.Server) ([]api.BIOSAttribute, error)

	// ConnectionTestFunc mocks the ConnectionTest method.
	ConnectionTestFunc func(ctx context.Context, server provisioning.Server) (string, error)

	// DetachMediaFunc mocks the DetachMedia method.
	DetachMediaFunc func(ctx context.Context, server provisioning.Server, virtualMediaID string) (*provisioning.BMCTaskMonitor, error)

	// DumpFunc mocks the Dump method.
	DumpFunc func(ctx context.Context, server provisioning.Server, additionalEndpoints []string, skipPredefined bool, trace bool) (api.BMCDump, error)

	// GetDataFunc mocks the GetData method.
	GetDataFunc func(ctx context.Context, server provisioning.Server) (api.BMCData, error)

	// LogEntriesBySourceFunc mocks the LogEntriesBySource method.
	LogEntriesBySourceFunc func(ctx context.Context, server provisioning.Server, logSource string) ([]api.BMCLogEvent, error)

	// LogSourcesFunc mocks the LogSources method.
	LogSourcesFunc func(ctx context.Context, server provisioning.Server) ([]string, error)

	// ResetSecureBootKeysFunc mocks the ResetSecureBootKeys method.
	ResetSecureBootKeysFunc func(ctx context.Context, server provisioning.Server) (bool, *provisioning.BMCTaskMonitor, error)

	// ServerPowerOffFunc mocks the ServerPowerOff method.
	ServerPowerOffFunc func(ctx context.Context, server provisioning.Server, force bool) (*provisioning.BMCTaskMonitor, error)

	// ServerPowerOnFunc mocks the ServerPowerOn method.
	ServerPowerOnFunc func(ctx context.Context, server provisioning.Server, force bool) (*provisioning.BMCTaskMonitor, error)

	// ServerRestartFunc mocks the ServerRestart method.
	ServerRestartFunc func(ctx context.Context, server provisioning.Server, force bool) (*provisioning.BMCTaskMonitor, error)

	// ServerSetLocationIndicatorFunc mocks the ServerSetLocationIndicator method.
	ServerSetLocationIndicatorFunc func(ctx context.Context, server provisioning.Server, active bool) error

	// TaskStateFunc mocks the TaskState method.
	TaskStateFunc func(ctx context.Context, server provisioning.Server, taskMonitor *provisioning.BMCTaskMonitor) (api.BMCTaskState, error)

	// WaitForTaskFunc mocks the WaitForTask method.
	WaitForTaskFunc func(ctx context.Context, server provisioning.Server, taskMonitor *provisioning.BMCTaskMonitor) error

	// calls tracks calls to the methods.
	calls struct {
		// ApplyBIOSAttributes holds details about calls to the ApplyBIOSAttributes method.
		ApplyBIOSAttributes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
			// Attributes is the attributes argument value.
			Attributes map[string]any
		}
		// ApplySecureBootCertificates holds details about calls to the ApplySecureBootCertificates method.
		ApplySecureBootCertificates []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
			// SecureBoot is the secureBoot argument value.
			SecureBoot api.BIOSSecureBoot
		}
		// AttachMedia holds details about calls to the AttachMedia method.
		AttachMedia []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
			// VirtualMediaID is the virtualMediaID argument value.
			VirtualMediaID string
			// MediaURL is the mediaURL argument value.
			MediaURL string
			// SetBootDevice is the setBootDevice argument value.
			SetBootDevice bool
		}
		// BIOSAttribute holds details about calls to the BIOSAttribute method.
		BIOSAttribute []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
			// AttributeName is the attributeName argument value.
			AttributeName string
		}
		// BIOSAttributes holds details about calls to the BIOSAttributes method.
		BIOSAttributes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
		}
		// ConnectionTest holds details about calls to the ConnectionTest method.
		ConnectionTest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
		}
		// DetachMedia holds details about calls to the DetachMedia method.
		DetachMedia []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
			// VirtualMediaID is the virtualMediaID argument value.
			VirtualMediaID string
		}
		// Dump holds details about calls to the Dump method.
		Dump []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
			// AdditionalEndpoints is the additionalEndpoints argument value.
			AdditionalEndpoints []string
			// SkipPredefined is the skipPredefined argument value.
			SkipPredefined bool
			// Trace is the trace argument value.
			Trace bool
		}
		// GetData holds details about calls to the GetData method.
		GetData []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
		}
		// LogEntriesBySource holds details about calls to the LogEntriesBySource method.
		LogEntriesBySource []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
			// LogSource is the logSource argument value.
			LogSource string
		}
		// LogSources holds details about calls to the LogSources method.
		LogSources []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
		}
		// ResetSecureBootKeys holds details about calls to the ResetSecureBootKeys method.
		ResetSecureBootKeys []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
		}
		// ServerPowerOff holds details about calls to the ServerPowerOff method.
		ServerPowerOff []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
			// Force is the force argument value.
			Force bool
		}
		// ServerPowerOn holds details about calls to the ServerPowerOn method.
		ServerPowerOn []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
			// Force is the force argument value.
			Force bool
		}
		// ServerRestart holds details about calls to the ServerRestart method.
		ServerRestart []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
			// Force is the force argument value.
			Force bool
		}
		// ServerSetLocationIndicator holds details about calls to the ServerSetLocationIndicator method.
		ServerSetLocationIndicator []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
			// Active is the active argument value.
			Active bool
		}
		// TaskState holds details about calls to the TaskState method.
		TaskState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
			// TaskMonitor is the taskMonitor argument value.
			TaskMonitor *provisioning.BMCTaskMonitor
		}
		// WaitForTask holds details about calls to the WaitForTask method.
		WaitForTask []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
			// TaskMonitor is the taskMonitor argument value.
			TaskMonitor *provisioning.BMCTaskMonitor
		}
	}
	lockApplyBIOSAttributes         sync.RWMutex
	lockApplySecureBootCertificates sync.RWMutex
	lockAttachMedia                 sync.RWMutex
	lockBIOSAttribute               sync.RWMutex
	lockBIOSAttributes              sync.RWMutex
	lockConnectionTest              sync.RWMutex
	lockDetachMedia                 sync.RWMutex
	lockDump                        sync.RWMutex
	lockGetData                     sync.RWMutex
	lockLogEntriesBySource          sync.RWMutex
	lockLogSources                  sync.RWMutex
	lockResetSecureBootKeys         sync.RWMutex
	lockServerPowerOff              sync.RWMutex
	lockServerPowerOn               sync.RWMutex
	lockServerRestart               sync.RWMutex
	lockServerSetLocationIndicator  sync.RWMutex
	lockTaskState                   sync.RWMutex
	lockWaitForTask                 sync.RWMutex
}

// ApplyBIOSAttributes calls ApplyBIOSAttributesFunc.
func (mock *BMCServerClientPortMock) ApplyBIOSAttributes(ctx context.Context, server provisioning.Server, attributes map[string]any) (*provisioning.BMCTaskMonitor, error) {
	if mock.ApplyBIOSAttributesFunc == nil {
		panic("BMCServerClientPortMock.ApplyBIOSAttributesFunc: method is nil but BMCServerClientPort.ApplyBIOSAttributes was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Server     provisioning.Server
		Attributes map[string]any
	}{
		Ctx:        ctx,
		Server:     server,
		Attributes: attributes,
	}
	mock.lockApplyBIOSAttributes.Lock()
	mock.calls.ApplyBIOSAttributes = append(mock.calls.ApplyBIOSAttributes, callInfo)
	mock.lockApplyBIOSAttributes.Unlock()
	return mock.ApplyBIOSAttributesFunc(ctx, server, attributes)
}

// ApplyBIOSAttributesCalls gets all the calls that were made to ApplyBIOSAttributes.
// Check the length with:
//
//	len(mockedBMCServerClientPort.ApplyBIOSAttributesCalls())
func (mock *BMCServerClientPortMock) ApplyBIOSAttributesCalls() []struct {
	Ctx        context.Context
	Server     provisioning.Server
	Attributes map[string]any
} {
	var calls []struct {
		Ctx        context.Context
		Server     provisioning.Server
		Attributes map[string]any
	}
	mock.lockApplyBIOSAttributes.RLock()
	calls = mock.calls.ApplyBIOSAttributes
	mock.lockApplyBIOSAttributes.RUnlock()
	return calls
}

// ApplySecureBootCertificates calls ApplySecureBootCertificatesFunc.
func (mock *BMCServerClientPortMock) ApplySecureBootCertificates(ctx context.Context, server provisioning.Server, secureBoot api.BIOSSecureBoot) (bool, error) {
	if mock.ApplySecureBootCertificatesFunc == nil {
		panic("BMCServerClientPortMock.ApplySecureBootCertificatesFunc: method is nil but BMCServerClientPort.ApplySecureBootCertificates was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Server     provisioning.Server
		SecureBoot api.BIOSSecureBoot
	}{
		Ctx:        ctx,
		Server:     server,
		SecureBoot: secureBoot,
	}
	mock.lockApplySecureBootCertificates.Lock()
	mock.calls.ApplySecureBootCertificates = append(mock.calls.ApplySecureBootCertificates, callInfo)
	mock.lockApplySecureBootCertificates.Unlock()
	return mock.ApplySecureBootCertificatesFunc(ctx, server, secureBoot)
}

// ApplySecureBootCertificatesCalls gets all the calls that were made to ApplySecureBootCertificates.
// Check the length with:
//
//	len(mockedBMCServerClientPort.ApplySecureBootCertificatesCalls())
func (mock *BMCServerClientPortMock) ApplySecureBootCertificatesCalls() []struct {
	Ctx        context.Context
	Server     provisioning.Server
	SecureBoot api.BIOSSecureBoot
} {
	var calls []struct {
		Ctx        context.Context
		Server     provisioning.Server
		SecureBoot api.BIOSSecureBoot
	}
	mock.lockApplySecureBootCertificates.RLock()
	calls = mock.calls.ApplySecureBootCertificates
	mock.lockApplySecureBootCertificates.RUnlock()
	return calls
}

// AttachMedia calls AttachMediaFunc.
func (mock *BMCServerClientPortMock) AttachMedia(ctx context.Context, server provisioning.Server, virtualMediaID string, mediaURL string, setBootDevice bool) (*provisioning.BMCTaskMonitor, error) {
	if mock.AttachMediaFunc == nil {
		panic("BMCServerClientPortMock.AttachMediaFunc: method is nil but BMCServerClientPort.AttachMedia was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Server         provisioning.Server
		VirtualMediaID string
		MediaURL       string
		SetBootDevice  bool
	}{
		Ctx:            ctx,
		Server:         server,
		VirtualMediaID: virtualMediaID,
		MediaURL:       mediaURL,
		SetBootDevice:  setBootDevice,
	}
	mock.lockAttachMedia.Lock()
	mock.calls.AttachMedia = append(mock.calls.AttachMedia, callInfo)
	mock.lockAttachMedia.Unlock()
	return mock.AttachMediaFunc(ctx, server, virtualMediaID, mediaURL, setBootDevice)
}

// AttachMediaCalls gets all the calls that were made to AttachMedia.
// Check the length with:
//
//	len(mockedBMCServerClientPort.AttachMediaCalls())
func (mock *BMCServerClientPortMock) AttachMediaCalls() []struct {
	Ctx            context.Context
	Server         provisioning.Server
	VirtualMediaID string
	MediaURL       string
	SetBootDevice  bool
} {
	var calls []struct {
		Ctx            context.Context
		Server         provisioning.Server
		VirtualMediaID string
		MediaURL       string
		SetBootDevice  bool
	}
	mock.lockAttachMedia.RLock()
	calls = mock.calls.AttachMedia
	mock.lockAttachMedia.RUnlock()
	return calls
}

// BIOSAttribute calls BIOSAttributeFunc.
func (mock *BMCServerClientPortMock) BIOSAttribute(ctx context.Context, server provisioning.Server, attributeName string) (api.BIOSAttribute, error) {
	if mock.BIOSAttributeFunc == nil {
		panic("BMCServerClientPortMock.BIOSAttributeFunc: method is nil but BMCServerClientPort.BIOSAttribute was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		Server        provisioning.Server
		AttributeName string
	}{
		Ctx:           ctx,
		Server:        server,
		AttributeName: attributeName,
	}
	mock.lockBIOSAttribute.Lock()
	mock.calls.BIOSAttribute = append(mock.calls.BIOSAttribute, callInfo)
	mock.lockBIOSAttribute.Unlock()
	return mock.BIOSAttributeFunc(ctx, server, attributeName)
}

// BIOSAttributeCalls gets all the calls that were made to BIOSAttribute.
// Check the length with:
//
//	len(mockedBMCServerClientPort.BIOSAttributeCalls())
func (mock *BMCServerClientPortMock) BIOSAttributeCalls() []struct {
	Ctx           context.Context
	Server        provisioning.Server
	AttributeName string
} {
	var calls []struct {
		Ctx           context.Context
		Server        provisioning.Server
		AttributeName string
	}
	mock.lockBIOSAttribute.RLock()
	calls = mock.calls.BIOSAttribute
	mock.lockBIOSAttribute.RUnlock()
	return calls
}

// BIOSAttributes calls BIOSAttributesFunc.
func (mock *BMCServerClientPortMock) BIOSAttributes(ctx context.Context, server provisioning.Server) ([]api.BIOSAttribute, error) {
	if mock.BIOSAttributesFunc == nil {
		panic("BMCServerClientPortMock.BIOSAttributesFunc: method is nil but BMCServerClientPort.BIOSAttributes was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
	}{
		Ctx:    ctx,
		Server: server,
	}
	mock.lockBIOSAttributes.Lock()
	mock.calls.BIOSAttributes = append(mock.calls.BIOSAttributes, callInfo)
	mock.lockBIOSAttributes.Unlock()
	return mock.BIOSAttributesFunc(ctx, server)
}

// BIOSAttributesCalls gets all the calls that were made to BIOSAttributes.
// Check the length with:
//
//	len(mockedBMCServerClientPort.BIOSAttributesCalls())
func (mock *BMCServerClientPortMock) BIOSAttributesCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
	}
	mock.lockBIOSAttributes.RLock()
	calls = mock.calls.BIOSAttributes
	mock.lockBIOSAttributes.RUnlock()
	return calls
}

// ConnectionTest calls ConnectionTestFunc.
func (mock *BMCServerClientPortMock) ConnectionTest(ctx context.Context, server provisioning.Server) (string, error) {
	if mock.ConnectionTestFunc == nil {
		panic("BMCServerClientPortMock.ConnectionTestFunc: method is nil but BMCServerClientPort.ConnectionTest was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
	}{
		Ctx:    ctx,
		Server: server,
	}
	mock.lockConnectionTest.Lock()
	mock.calls.ConnectionTest = append(mock.calls.ConnectionTest, callInfo)
	mock.lockConnectionTest.Unlock()
	return mock.ConnectionTestFunc(ctx, server)
}

// ConnectionTestCalls gets all the calls that were made to ConnectionTest.
// Check the length with:
//
//	len(mockedBMCServerClientPort.ConnectionTestCalls())
func (mock *BMCServerClientPortMock) ConnectionTestCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
	}
	mock.lockConnectionTest.RLock()
	calls = mock.calls.ConnectionTest
	mock.lockConnectionTest.RUnlock()
	return calls
}

// DetachMedia calls DetachMediaFunc.
func (mock *BMCServerClientPortMock) DetachMedia(ctx context.Context, server provisioning.Server, virtualMediaID string) (*provisioning.BMCTaskMonitor, error) {
	if mock.DetachMediaFunc == nil {
		panic("BMCServerClientPortMock.DetachMediaFunc: method is nil but BMCServerClientPort.DetachMedia was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Server         provisioning.Server
		VirtualMediaID string
	}{
		Ctx:            ctx,
		Server:         server,
		VirtualMediaID: virtualMediaID,
	}
	mock.lockDetachMedia.Lock()
	mock.calls.DetachMedia = append(mock.calls.DetachMedia, callInfo)
	mock.lockDetachMedia.Unlock()
	return mock.DetachMediaFunc(ctx, server, virtualMediaID)
}

// DetachMediaCalls gets all the calls that were made to DetachMedia.
// Check the length with:
//
//	len(mockedBMCServerClientPort.DetachMediaCalls())
func (mock *BMCServerClientPortMock) DetachMediaCalls() []struct {
	Ctx            context.Context
	Server         provisioning.Server
	VirtualMediaID string
} {
	var calls []struct {
		Ctx            context.Context
		Server         provisioning.Server
		VirtualMediaID string
	}
	mock.lockDetachMedia.RLock()
	calls = mock.calls.DetachMedia
	mock.lockDetachMedia.RUnlock()
	return calls
}

// Dump calls DumpFunc.
func (mock *BMCServerClientPortMock) Dump(ctx context.Context, server provisioning.Server, additionalEndpoints []string, skipPredefined bool, trace bool) (api.BMCDump, error) {
	if mock.DumpFunc == nil {
		panic("BMCServerClientPortMock.DumpFunc: method is nil but BMCServerClientPort.Dump was just called")
	}
	callInfo := struct {
		Ctx                 context.Context
		Server              provisioning.Server
		AdditionalEndpoints []string
		SkipPredefined      bool
		Trace               bool
	}{
		Ctx:                 ctx,
		Server:              server,
		AdditionalEndpoints: additionalEndpoints,
		SkipPredefined:      skipPredefined,
		Trace:               trace,
	}
	mock.lockDump.Lock()
	mock.calls.Dump = append(mock.calls.Dump, callInfo)
	mock.lockDump.Unlock()
	return mock.DumpFunc(ctx, server, additionalEndpoints, skipPredefined, trace)
}

// DumpCalls gets all the calls that were made to Dump.
// Check the length with:
//
//	len(mockedBMCServerClientPort.DumpCalls())
func (mock *BMCServerClientPortMock) DumpCalls() []struct {
	Ctx                 context.Context
	Server              provisioning.Server
	AdditionalEndpoints []string
	SkipPredefined      bool
	Trace               bool
} {
	var calls []struct {
		Ctx                 context.Context
		Server              provisioning.Server
		AdditionalEndpoints []string
		SkipPredefined      bool
		Trace               bool
	}
	mock.lockDump.RLock()
	calls = mock.calls.Dump
	mock.lockDump.RUnlock()
	return calls
}

// GetData calls GetDataFunc.
func (mock *BMCServerClientPortMock) GetData(ctx context.Context, server provisioning.Server) (api.BMCData, error) {
	if mock.GetDataFunc == nil {
		panic("BMCServerClientPortMock.GetDataFunc: method is nil but BMCServerClientPort.GetData was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
	}{
		Ctx:    ctx,
		Server: server,
	}
	mock.lockGetData.Lock()
	mock.calls.GetData = append(mock.calls.GetData, callInfo)
	mock.lockGetData.Unlock()
	return mock.GetDataFunc(ctx, server)
}

// GetDataCalls gets all the calls that were made to GetData.
// Check the length with:
//
//	len(mockedBMCServerClientPort.GetDataCalls())
func (mock *BMCServerClientPortMock) GetDataCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
	}
	mock.lockGetData.RLock()
	calls = mock.calls.GetData
	mock.lockGetData.RUnlock()
	return calls
}

// LogEntriesBySource calls LogEntriesBySourceFunc.
func (mock *BMCServerClientPortMock) LogEntriesBySource(ctx context.Context, server provisioning.Server, logSource string) ([]api.BMCLogEvent, error) {
	if mock.LogEntriesBySourceFunc == nil {
		panic("BMCServerClientPortMock.LogEntriesBySourceFunc: method is nil but BMCServerClientPort.LogEntriesBySource was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Server    provisioning.Server
		LogSource string
	}{
		Ctx:       ctx,
		Server:    server,
		LogSource: logSource,
	}
	mock.lockLogEntriesBySource.Lock()
	mock.calls.LogEntriesBySource = append(mock.calls.LogEntriesBySource, callInfo)
	mock.lockLogEntriesBySource.Unlock()
	return mock.LogEntriesBySourceFunc(ctx, server, logSource)
}

// LogEntriesBySourceCalls gets all the calls that were made to LogEntriesBySource.
// Check the length with:
//
//	len(mockedBMCServerClientPort.LogEntriesBySourceCalls())
func (mock *BMCServerClientPortMock) LogEntriesBySourceCalls() []struct {
	Ctx       context.Context
	Server    provisioning.Server
	LogSource string
} {
	var calls []struct {
		Ctx       context.Context
		Server    provisioning.Server
		LogSource string
	}
	mock.lockLogEntriesBySource.RLock()
	calls = mock.calls.LogEntriesBySource
	mock.lockLogEntriesBySource.RUnlock()
	return calls
}

// LogSources calls LogSourcesFunc.
func (mock *BMCServerClientPortMock) LogSources(ctx context.Context, server provisioning.Server) ([]string, error) {
	if mock.LogSourcesFunc == nil {
		panic("BMCServerClientPortMock.LogSourcesFunc: method is nil but BMCServerClientPort.LogSources was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
	}{
		Ctx:    ctx,
		Server: server,
	}
	mock.lockLogSources.Lock()
	mock.calls.LogSources = append(mock.calls.LogSources, callInfo)
	mock.lockLogSources.Unlock()
	return mock.LogSourcesFunc(ctx, server)
}

// LogSourcesCalls gets all the calls that were made to LogSources.
// Check the length with:
//
//	len(mockedBMCServerClientPort.LogSourcesCalls())
func (mock *BMCServerClientPortMock) LogSourcesCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
	}
	mock.lockLogSources.RLock()
	calls = mock.calls.LogSources
	mock.lockLogSources.RUnlock()
	return calls
}

// ResetSecureBootKeys calls ResetSecureBootKeysFunc.
func (mock *BMCServerClientPortMock) ResetSecureBootKeys(ctx context.Context, server provisioning.Server) (bool, *provisioning.BMCTaskMonitor, error) {
	if mock.ResetSecureBootKeysFunc == nil {
		panic("BMCServerClientPortMock.ResetSecureBootKeysFunc: method is nil but BMCServerClientPort.ResetSecureBootKeys was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
	}{
		Ctx:    ctx,
		Server: server,
	}
	mock.lockResetSecureBootKeys.Lock()
	mock.calls.ResetSecureBootKeys = append(mock.calls.ResetSecureBootKeys, callInfo)
	mock.lockResetSecureBootKeys.Unlock()
	return mock.ResetSecureBootKeysFunc(ctx, server)
}

// ResetSecureBootKeysCalls gets all the calls that were made to ResetSecureBootKeys.
// Check the length with:
//
//	len(mockedBMCServerClientPort.ResetSecureBootKeysCalls())
func (mock *BMCServerClientPortMock) ResetSecureBootKeysCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
	}
	mock.lockResetSecureBootKeys.RLock()
	calls = mock.calls.ResetSecureBootKeys
	mock.lockResetSecureBootKeys.RUnlock()
	return calls
}

// ServerPowerOff calls ServerPowerOffFunc.
func (mock *BMCServerClientPortMock) ServerPowerOff(ctx context.Context, server provisioning.Server, force bool) (*provisioning.BMCTaskMonitor, error) {
	if mock.ServerPowerOffFunc == nil {
		panic("BMCServerClientPortMock.ServerPowerOffFunc: method is nil but BMCServerClientPort.ServerPowerOff was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
		Force  bool
	}{
		Ctx:    ctx,
		Server: server,
		Force:  force,
	}
	mock.lockServerPowerOff.Lock()
	mock.calls.ServerPowerOff = append(mock.calls.ServerPowerOff, callInfo)
	mock.lockServerPowerOff.Unlock()
	return mock.ServerPowerOffFunc(ctx, server, force)
}

// ServerPowerOffCalls gets all the calls that were made to ServerPowerOff.
// Check the length with:
//
//	len(mockedBMCServerClientPort.ServerPowerOffCalls())
func (mock *BMCServerClientPortMock) ServerPowerOffCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
	Force  bool
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
		Force  bool
	}
	mock.lockServerPowerOff.RLock()
	calls = mock.calls.ServerPowerOff
	mock.lockServerPowerOff.RUnlock()
	return calls
}

// ServerPowerOn calls ServerPowerOnFunc.
func (mock *BMCServerClientPortMock) ServerPowerOn(ctx context.Context, server provisioning.Server, force bool) (*provisioning.BMCTaskMonitor, error) {
	if mock.ServerPowerOnFunc == nil {
		panic("BMCServerClientPortMock.ServerPowerOnFunc: method is nil but BMCServerClientPort.ServerPowerOn was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
		Force  bool
	}{
		Ctx:    ctx,
		Server: server,
		Force:  force,
	}
	mock.lockServerPowerOn.Lock()
	mock.calls.ServerPowerOn = append(mock.calls.ServerPowerOn, callInfo)
	mock.lockServerPowerOn.Unlock()
	return mock.ServerPowerOnFunc(ctx, server, force)
}

// ServerPowerOnCalls gets all the calls that were made to ServerPowerOn.
// Check the length with:
//
//	len(mockedBMCServerClientPort.ServerPowerOnCalls())
func (mock *BMCServerClientPortMock) ServerPowerOnCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
	Force  bool
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
		Force  bool
	}
	mock.lockServerPowerOn.RLock()
	calls = mock.calls.ServerPowerOn
	mock.lockServerPowerOn.RUnlock()
	return calls
}

// ServerRestart calls ServerRestartFunc.
func (mock *BMCServerClientPortMock) ServerRestart(ctx context.Context, server provisioning.Server, force bool) (*provisioning.BMCTaskMonitor, error) {
	if mock.ServerRestartFunc == nil {
		panic("BMCServerClientPortMock.ServerRestartFunc: method is nil but BMCServerClientPort.ServerRestart was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
		Force  bool
	}{
		Ctx:    ctx,
		Server: server,
		Force:  force,
	}
	mock.lockServerRestart.Lock()
	mock.calls.ServerRestart = append(mock.calls.ServerRestart, callInfo)
	mock.lockServerRestart.Unlock()
	return mock.ServerRestartFunc(ctx, server, force)
}

// ServerRestartCalls gets all the calls that were made to ServerRestart.
// Check the length with:
//
//	len(mockedBMCServerClientPort.ServerRestartCalls())
func (mock *BMCServerClientPortMock) ServerRestartCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
	Force  bool
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
		Force  bool
	}
	mock.lockServerRestart.RLock()
	calls = mock.calls.ServerRestart
	mock.lockServerRestart.RUnlock()
	return calls
}

// ServerSetLocationIndicator calls ServerSetLocationIndicatorFunc.
func (mock *BMCServerClientPortMock) ServerSetLocationIndicator(ctx context.Context, server provisioning.Server, active bool) error {
	if mock.ServerSetLocationIndicatorFunc == nil {
		panic("BMCServerClientPortMock.ServerSetLocationIndicatorFunc: method is nil but BMCServerClientPort.ServerSetLocationIndicator was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
		Active bool
	}{
		Ctx:    ctx,
		Server: server,
		Active: active,
	}
	mock.lockServerSetLocationIndicator.Lock()
	mock.calls.ServerSetLocationIndicator = append(mock.calls.ServerSetLocationIndicator, callInfo)
	mock.lockServerSetLocationIndicator.Unlock()
	return mock.ServerSetLocationIndicatorFunc(ctx, server, active)
}

// ServerSetLocationIndicatorCalls gets all the calls that were made to ServerSetLocationIndicator.
// Check the length with:
//
//	len(mockedBMCServerClientPort.ServerSetLocationIndicatorCalls())
func (mock *BMCServerClientPortMock) ServerSetLocationIndicatorCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
	Active bool
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
		Active bool
	}
	mock.lockServerSetLocationIndicator.RLock()
	calls = mock.calls.ServerSetLocationIndicator
	mock.lockServerSetLocationIndicator.RUnlock()
	return calls
}

// TaskState calls TaskStateFunc.
func (mock *BMCServerClientPortMock) TaskState(ctx context.Context, server provisioning.Server, taskMonitor *provisioning.BMCTaskMonitor) (api.BMCTaskState, error) {
	if mock.TaskStateFunc == nil {
		panic("BMCServerClientPortMock.TaskStateFunc: method is nil but BMCServerClientPort.TaskState was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Server      provisioning.Server
		TaskMonitor *provisioning.BMCTaskMonitor
	}{
		Ctx:         ctx,
		Server:      server,
		TaskMonitor: taskMonitor,
	}
	mock.lockTaskState.Lock()
	mock.calls.TaskState = append(mock.calls.TaskState, callInfo)
	mock.lockTaskState.Unlock()
	return mock.TaskStateFunc(ctx, server, taskMonitor)
}

// TaskStateCalls gets all the calls that were made to TaskState.
// Check the length with:
//
//	len(mockedBMCServerClientPort.TaskStateCalls())
func (mock *BMCServerClientPortMock) TaskStateCalls() []struct {
	Ctx         context.Context
	Server      provisioning.Server
	TaskMonitor *provisioning.BMCTaskMonitor
} {
	var calls []struct {
		Ctx         context.Context
		Server      provisioning.Server
		TaskMonitor *provisioning.BMCTaskMonitor
	}
	mock.lockTaskState.RLock()
	calls = mock.calls.TaskState
	mock.lockTaskState.RUnlock()
	return calls
}

// WaitForTask calls WaitForTaskFunc.
func (mock *BMCServerClientPortMock) WaitForTask(ctx context.Context, server provisioning.Server, taskMonitor *provisioning.BMCTaskMonitor) error {
	if mock.WaitForTaskFunc == nil {
		panic("BMCServerClientPortMock.WaitForTaskFunc: method is nil but BMCServerClientPort.WaitForTask was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Server      provisioning.Server
		TaskMonitor *provisioning.BMCTaskMonitor
	}{
		Ctx:         ctx,
		Server:      server,
		TaskMonitor: taskMonitor,
	}
	mock.lockWaitForTask.Lock()
	mock.calls.WaitForTask = append(mock.calls.WaitForTask, callInfo)
	mock.lockWaitForTask.Unlock()
	return mock.WaitForTaskFunc(ctx, server, taskMonitor)
}

// WaitForTaskCalls gets all the calls that were made to WaitForTask.
// Check the length with:
//
//	len(mockedBMCServerClientPort.WaitForTaskCalls())
func (mock *BMCServerClientPortMock) WaitForTaskCalls() []struct {
	Ctx         context.Context
	Server      provisioning.Server
	TaskMonitor *provisioning.BMCTaskMonitor
} {
	var calls []struct {
		Ctx         context.Context
		Server      provisioning.Server
		TaskMonitor *provisioning.BMCTaskMonitor
	}
	mock.lockWaitForTask.RLock()
	calls = mock.calls.WaitForTask
	mock.lockWaitForTask.RUnlock()
	return calls
}
