// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package mock

import (
	"sync"

	"github.com/FuturFusion/operations-center/internal/provisioning"
)

// Ensure that SecureBootCertificateCataloguePortMock does implement provisioning.SecureBootCertificateCataloguePort.
// If this is not the case, regenerate this file with mockery.
var _ provisioning.SecureBootCertificateCataloguePort = &SecureBootCertificateCataloguePortMock{}

// SecureBootCertificateCataloguePortMock is a mock implementation of provisioning.SecureBootCertificateCataloguePort.
//
//	func TestSomethingThatUsesSecureBootCertificateCataloguePort(t *testing.T) {
//
//		// make and configure a mocked provisioning.SecureBootCertificateCataloguePort
//		mockedSecureBootCertificateCataloguePort := &SecureBootCertificateCataloguePortMock{
//			CertificatesByFingerprintFunc: func(fingerprints []string) ([]string, []string) {
//				panic("mock out the CertificatesByFingerprint method")
//			},
//		}
//
//		// use mockedSecureBootCertificateCataloguePort in code that requires provisioning.SecureBootCertificateCataloguePort
//		// and then make assertions.
//
//	}
type SecureBootCertificateCataloguePortMock struct {
	// CertificatesByFingerprintFunc mocks the CertificatesByFingerprint method.
	CertificatesByFingerprintFunc func(fingerprints []string) ([]string, []string)

	// calls tracks calls to the methods.
	calls struct {
		// CertificatesByFingerprint holds details about calls to the CertificatesByFingerprint method.
		CertificatesByFingerprint []struct {
			// Fingerprints is the fingerprints argument value.
			Fingerprints []string
		}
	}
	lockCertificatesByFingerprint sync.RWMutex
}

// CertificatesByFingerprint calls CertificatesByFingerprintFunc.
func (mock *SecureBootCertificateCataloguePortMock) CertificatesByFingerprint(fingerprints []string) ([]string, []string) {
	if mock.CertificatesByFingerprintFunc == nil {
		panic("SecureBootCertificateCataloguePortMock.CertificatesByFingerprintFunc: method is nil but SecureBootCertificateCataloguePort.CertificatesByFingerprint was just called")
	}
	callInfo := struct {
		Fingerprints []string
	}{
		Fingerprints: fingerprints,
	}
	mock.lockCertificatesByFingerprint.Lock()
	mock.calls.CertificatesByFingerprint = append(mock.calls.CertificatesByFingerprint, callInfo)
	mock.lockCertificatesByFingerprint.Unlock()
	return mock.CertificatesByFingerprintFunc(fingerprints)
}

// CertificatesByFingerprintCalls gets all the calls that were made to CertificatesByFingerprint.
// Check the length with:
//
//	len(mockedSecureBootCertificateCataloguePort.CertificatesByFingerprintCalls())
func (mock *SecureBootCertificateCataloguePortMock) CertificatesByFingerprintCalls() []struct {
	Fingerprints []string
} {
	var calls []struct {
		Fingerprints []string
	}
	mock.lockCertificatesByFingerprint.RLock()
	calls = mock.calls.CertificatesByFingerprint
	mock.lockCertificatesByFingerprint.RUnlock()
	return calls
}
