// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package mock

import (
	"context"
	"sync"

	"github.com/lxc/incus-os/incus-osd/api"

	"github.com/FuturFusion/operations-center/internal/provisioning"
)

// Ensure that SecureBootCertificateSourcePortMock does implement provisioning.SecureBootCertificateSourcePort.
// If this is not the case, regenerate this file with mockery.
var _ provisioning.SecureBootCertificateSourcePort = &SecureBootCertificateSourcePortMock{}

// SecureBootCertificateSourcePortMock is a mock implementation of provisioning.SecureBootCertificateSourcePort.
//
//	func TestSomethingThatUsesSecureBootCertificateSourcePort(t *testing.T) {
//
//		// make and configure a mocked provisioning.SecureBootCertificateSourcePort
//		mockedSecureBootCertificateSourcePort := &SecureBootCertificateSourcePortMock{
//			GetSecureBootCertificatesFunc: func(ctx context.Context) (api.InternalSecureBootCertificates, error) {
//				panic("mock out the GetSecureBootCertificates method")
//			},
//		}
//
//		// use mockedSecureBootCertificateSourcePort in code that requires provisioning.SecureBootCertificateSourcePort
//		// and then make assertions.
//
//	}
type SecureBootCertificateSourcePortMock struct {
	// GetSecureBootCertificatesFunc mocks the GetSecureBootCertificates method.
	GetSecureBootCertificatesFunc func(ctx context.Context) (api.InternalSecureBootCertificates, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetSecureBootCertificates holds details about calls to the GetSecureBootCertificates method.
		GetSecureBootCertificates []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockGetSecureBootCertificates sync.RWMutex
}

// GetSecureBootCertificates calls GetSecureBootCertificatesFunc.
func (mock *SecureBootCertificateSourcePortMock) GetSecureBootCertificates(ctx context.Context) (api.InternalSecureBootCertificates, error) {
	if mock.GetSecureBootCertificatesFunc == nil {
		panic("SecureBootCertificateSourcePortMock.GetSecureBootCertificatesFunc: method is nil but SecureBootCertificateSourcePort.GetSecureBootCertificates was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetSecureBootCertificates.Lock()
	mock.calls.GetSecureBootCertificates = append(mock.calls.GetSecureBootCertificates, callInfo)
	mock.lockGetSecureBootCertificates.Unlock()
	return mock.GetSecureBootCertificatesFunc(ctx)
}

// GetSecureBootCertificatesCalls gets all the calls that were made to GetSecureBootCertificates.
// Check the length with:
//
//	len(mockedSecureBootCertificateSourcePort.GetSecureBootCertificatesCalls())
func (mock *SecureBootCertificateSourcePortMock) GetSecureBootCertificatesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetSecureBootCertificates.RLock()
	calls = mock.calls.GetSecureBootCertificates
	mock.lockGetSecureBootCertificates.RUnlock()
	return calls
}
