// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package mock

import (
	"context"
	"sync"
	"time"

	"github.com/lxc/incus-os/incus-osd/api/images"

	"github.com/FuturFusion/operations-center/internal/provisioning"
)

// Ensure that SecureBootMediaPortMock does implement provisioning.SecureBootMediaPort.
// If this is not the case, regenerate this file with mockery.
var _ provisioning.SecureBootMediaPort = &SecureBootMediaPortMock{}

// SecureBootMediaPortMock is a mock implementation of provisioning.SecureBootMediaPort.
//
//	func TestSomethingThatUsesSecureBootMediaPort(t *testing.T) {
//
//		// make and configure a mocked provisioning.SecureBootMediaPort
//		mockedSecureBootMediaPort := &SecureBootMediaPortMock{
//			GenerateFunc: func(ctx context.Context, architecture images.UpdateFileArchitecture, certificates provisioning.SecureBootCertificates) (string, error) {
//				panic("mock out the Generate method")
//			},
//			OpenFunc: func(ctx context.Context, id string) (*provisioning.SecureBootMediaImage, error) {
//				panic("mock out the Open method")
//			},
//			PruneFunc: func(ctx context.Context, ttl time.Duration) error {
//				panic("mock out the Prune method")
//			},
//		}
//
//		// use mockedSecureBootMediaPort in code that requires provisioning.SecureBootMediaPort
//		// and then make assertions.
//
//	}
type SecureBootMediaPortMock struct {
	// GenerateFunc mocks the Generate method.
	GenerateFunc func(ctx context.Context, architecture images.UpdateFileArchitecture, certificates provisioning.SecureBootCertificates) (string, error)

	// OpenFunc mocks the Open method.
	OpenFunc func(ctx context.Context, id string) (*provisioning.SecureBootMediaImage, error)

	// PruneFunc mocks the Prune method.
	PruneFunc func(ctx context.Context, ttl time.Duration) error

	// calls tracks calls to the methods.
	calls struct {
		// Generate holds details about calls to the Generate method.
		Generate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Architecture is the architecture argument value.
			Architecture images.UpdateFileArchitecture
			// Certificates is the certificates argument value.
			Certificates provisioning.SecureBootCertificates
		}
		// Open holds details about calls to the Open method.
		Open []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// Prune holds details about calls to the Prune method.
		Prune []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TTL is the ttl argument value.
			TTL time.Duration
		}
	}
	lockGenerate sync.RWMutex
	lockOpen     sync.RWMutex
	lockPrune    sync.RWMutex
}

// Generate calls GenerateFunc.
func (mock *SecureBootMediaPortMock) Generate(ctx context.Context, architecture images.UpdateFileArchitecture, certificates provisioning.SecureBootCertificates) (string, error) {
	if mock.GenerateFunc == nil {
		panic("SecureBootMediaPortMock.GenerateFunc: method is nil but SecureBootMediaPort.Generate was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Architecture images.UpdateFileArchitecture
		Certificates provisioning.SecureBootCertificates
	}{
		Ctx:          ctx,
		Architecture: architecture,
		Certificates: certificates,
	}
	mock.lockGenerate.Lock()
	mock.calls.Generate = append(mock.calls.Generate, callInfo)
	mock.lockGenerate.Unlock()
	return mock.GenerateFunc(ctx, architecture, certificates)
}

// GenerateCalls gets all the calls that were made to Generate.
// Check the length with:
//
//	len(mockedSecureBootMediaPort.GenerateCalls())
func (mock *SecureBootMediaPortMock) GenerateCalls() []struct {
	Ctx          context.Context
	Architecture images.UpdateFileArchitecture
	Certificates provisioning.SecureBootCertificates
} {
	var calls []struct {
		Ctx          context.Context
		Architecture images.UpdateFileArchitecture
		Certificates provisioning.SecureBootCertificates
	}
	mock.lockGenerate.RLock()
	calls = mock.calls.Generate
	mock.lockGenerate.RUnlock()
	return calls
}

// Open calls OpenFunc.
func (mock *SecureBootMediaPortMock) Open(ctx context.Context, id string) (*provisioning.SecureBootMediaImage, error) {
	if mock.OpenFunc == nil {
		panic("SecureBootMediaPortMock.OpenFunc: method is nil but SecureBootMediaPort.Open was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockOpen.Lock()
	mock.calls.Open = append(mock.calls.Open, callInfo)
	mock.lockOpen.Unlock()
	return mock.OpenFunc(ctx, id)
}

// OpenCalls gets all the calls that were made to Open.
// Check the length with:
//
//	len(mockedSecureBootMediaPort.OpenCalls())
func (mock *SecureBootMediaPortMock) OpenCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockOpen.RLock()
	calls = mock.calls.Open
	mock.lockOpen.RUnlock()
	return calls
}

// Prune calls PruneFunc.
func (mock *SecureBootMediaPortMock) Prune(ctx context.Context, ttl time.Duration) error {
	if mock.PruneFunc == nil {
		panic("SecureBootMediaPortMock.PruneFunc: method is nil but SecureBootMediaPort.Prune was just called")
	}
	callInfo := struct {
		Ctx context.Context
		TTL time.Duration
	}{
		Ctx: ctx,
		TTL: ttl,
	}
	mock.lockPrune.Lock()
	mock.calls.Prune = append(mock.calls.Prune, callInfo)
	mock.lockPrune.Unlock()
	return mock.PruneFunc(ctx, ttl)
}

// PruneCalls gets all the calls that were made to Prune.
// Check the length with:
//
//	len(mockedSecureBootMediaPort.PruneCalls())
func (mock *SecureBootMediaPortMock) PruneCalls() []struct {
	Ctx context.Context
	TTL time.Duration
} {
	var calls []struct {
		Ctx context.Context
		TTL time.Duration
	}
	mock.lockPrune.RLock()
	calls = mock.calls.Prune
	mock.lockPrune.RUnlock()
	return calls
}
