// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package mock

import (
	"context"
	"io"
	"sync"

	"github.com/FuturFusion/operations-center/internal/provisioning"
)

// Ensure that SeedImageProgressPortMock does implement provisioning.SeedImageProgressPort.
// If this is not the case, regenerate this file with mockery.
var _ provisioning.SeedImageProgressPort = &SeedImageProgressPortMock{}

// SeedImageProgressPortMock is a mock implementation of provisioning.SeedImageProgressPort.
//
//	func TestSomethingThatUsesSeedImageProgressPort(t *testing.T) {
//
//		// make and configure a mocked provisioning.SeedImageProgressPort
//		mockedSeedImageProgressPort := &SeedImageProgressPortMock{
//			GetFunc: func(ctx context.Context, deploymentID string) (provisioning.SeedImageProgress, bool) {
//				panic("mock out the Get method")
//			},
//			ResetFunc: func(ctx context.Context, deploymentID string)  {
//				panic("mock out the Reset method")
//			},
//			TrackFunc: func(ctx context.Context, deploymentID string, info provisioning.SeedImageInfo, content io.ReadSeekCloser) io.ReadSeekCloser {
//				panic("mock out the Track method")
//			},
//		}
//
//		// use mockedSeedImageProgressPort in code that requires provisioning.SeedImageProgressPort
//		// and then make assertions.
//
//	}
type SeedImageProgressPortMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, deploymentID string) (provisioning.SeedImageProgress, bool)

	// ResetFunc mocks the Reset method.
	ResetFunc func(ctx context.Context, deploymentID string)

	// TrackFunc mocks the Track method.
	TrackFunc func(ctx context.Context, deploymentID string, info provisioning.SeedImageInfo, content io.ReadSeekCloser) io.ReadSeekCloser

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeploymentID is the deploymentID argument value.
			DeploymentID string
		}
		// Reset holds details about calls to the Reset method.
		Reset []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeploymentID is the deploymentID argument value.
			DeploymentID string
		}
		// Track holds details about calls to the Track method.
		Track []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeploymentID is the deploymentID argument value.
			DeploymentID string
			// Info is the info argument value.
			Info provisioning.SeedImageInfo
			// Content is the content argument value.
			Content io.ReadSeekCloser
		}
	}
	lockGet   sync.RWMutex
	lockReset sync.RWMutex
	lockTrack sync.RWMutex
}

// Get calls GetFunc.
func (mock *SeedImageProgressPortMock) Get(ctx context.Context, deploymentID string) (provisioning.SeedImageProgress, bool) {
	if mock.GetFunc == nil {
		panic("SeedImageProgressPortMock.GetFunc: method is nil but SeedImageProgressPort.Get was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		DeploymentID string
	}{
		Ctx:          ctx,
		DeploymentID: deploymentID,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, deploymentID)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedSeedImageProgressPort.GetCalls())
func (mock *SeedImageProgressPortMock) GetCalls() []struct {
	Ctx          context.Context
	DeploymentID string
} {
	var calls []struct {
		Ctx          context.Context
		DeploymentID string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Reset calls ResetFunc.
func (mock *SeedImageProgressPortMock) Reset(ctx context.Context, deploymentID string) {
	if mock.ResetFunc == nil {
		panic("SeedImageProgressPortMock.ResetFunc: method is nil but SeedImageProgressPort.Reset was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		DeploymentID string
	}{
		Ctx:          ctx,
		DeploymentID: deploymentID,
	}
	mock.lockReset.Lock()
	mock.calls.Reset = append(mock.calls.Reset, callInfo)
	mock.lockReset.Unlock()
	mock.ResetFunc(ctx, deploymentID)
}

// ResetCalls gets all the calls that were made to Reset.
// Check the length with:
//
//	len(mockedSeedImageProgressPort.ResetCalls())
func (mock *SeedImageProgressPortMock) ResetCalls() []struct {
	Ctx          context.Context
	DeploymentID string
} {
	var calls []struct {
		Ctx          context.Context
		DeploymentID string
	}
	mock.lockReset.RLock()
	calls = mock.calls.Reset
	mock.lockReset.RUnlock()
	return calls
}

// Track calls TrackFunc.
func (mock *SeedImageProgressPortMock) Track(ctx context.Context, deploymentID string, info provisioning.SeedImageInfo, content io.ReadSeekCloser) io.ReadSeekCloser {
	if mock.TrackFunc == nil {
		panic("SeedImageProgressPortMock.TrackFunc: method is nil but SeedImageProgressPort.Track was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		DeploymentID string
		Info         provisioning.SeedImageInfo
		Content      io.ReadSeekCloser
	}{
		Ctx:          ctx,
		DeploymentID: deploymentID,
		Info:         info,
		Content:      content,
	}
	mock.lockTrack.Lock()
	mock.calls.Track = append(mock.calls.Track, callInfo)
	mock.lockTrack.Unlock()
	return mock.TrackFunc(ctx, deploymentID, info, content)
}

// TrackCalls gets all the calls that were made to Track.
// Check the length with:
//
//	len(mockedSeedImageProgressPort.TrackCalls())
func (mock *SeedImageProgressPortMock) TrackCalls() []struct {
	Ctx          context.Context
	DeploymentID string
	Info         provisioning.SeedImageInfo
	Content      io.ReadSeekCloser
} {
	var calls []struct {
		Ctx          context.Context
		DeploymentID string
		Info         provisioning.SeedImageInfo
		Content      io.ReadSeekCloser
	}
	mock.lockTrack.RLock()
	calls = mock.calls.Track
	mock.lockTrack.RUnlock()
	return calls
}
