// Code generated by generate-inventory; DO NOT EDIT.

package client

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"path"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/shared/api"
)

func (c OperationsCenterClient) GetWithFilterNetworkIntegrations(ctx context.Context, filter inventory.NetworkIntegrationFilter) ([]api.NetworkIntegration, error) {
	query := url.Values{}
	query.Add("recursion", "1")
	query = filter.AppendToURLValues(query)

	response, err := c.DoRequest(ctx, http.MethodGet, "/inventory/network_integrations", query, nil)
	if err != nil {
		return nil, err
	}

	network_integrations := []api.NetworkIntegration{}
	err = json.Unmarshal(response.Metadata, &network_integrations)
	if err != nil {
		return nil, err
	}

	return network_integrations, nil
}

func (c OperationsCenterClient) GetNetworkIntegration(ctx context.Context, id string) (api.NetworkIntegration, error) {
	response, err := c.DoRequest(ctx, http.MethodGet, path.Join("/inventory/network_integrations", id), nil, nil)
	if err != nil {
		return api.NetworkIntegration{}, err
	}

	network_integration := api.NetworkIntegration{}
	err = json.Unmarshal(response.Metadata, &network_integration)
	if err != nil {
		return api.NetworkIntegration{}, err
	}

	return network_integration, nil
}

func (c OperationsCenterClient) ResyncNetworkIntegration(ctx context.Context, id string) error {
	_, err := c.DoRequest(ctx, http.MethodPost, path.Join("/inventory/network_integrations", id, ":resync"), nil, nil)
	if err != nil {
		return err
	}

	return nil
}
