// Code generated by generate-inventory; DO NOT EDIT.

package client

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"path"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/shared/api"
)

func (c OperationsCenterClient) GetWithFilterInstances(ctx context.Context, filter inventory.InstanceFilter) ([]api.Instance, error) {
	query := url.Values{}
	query.Add("recursion", "1")
	query = filter.AppendToURLValues(query)

	response, err := c.DoRequest(ctx, http.MethodGet, "/inventory/instances", query, nil)
	if err != nil {
		return nil, err
	}

	instances := []api.Instance{}
	err = json.Unmarshal(response.Metadata, &instances)
	if err != nil {
		return nil, err
	}

	return instances, nil
}

func (c OperationsCenterClient) GetInstance(ctx context.Context, id string) (api.Instance, error) {
	response, err := c.DoRequest(ctx, http.MethodGet, path.Join("/inventory/instances", id), nil, nil)
	if err != nil {
		return api.Instance{}, err
	}

	instance := api.Instance{}
	err = json.Unmarshal(response.Metadata, &instance)
	if err != nil {
		return api.Instance{}, err
	}

	return instance, nil
}

func (c OperationsCenterClient) ResyncInstance(ctx context.Context, id string) error {
	_, err := c.DoRequest(ctx, http.MethodPost, path.Join("/inventory/instances", id, ":resync"), nil, nil)
	if err != nil {
		return err
	}

	return nil
}
