// Code generated by generate-inventory; DO NOT EDIT.

package client

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"path"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/shared/api"
)

func (c OperationsCenterClient) GetWithFilterNetworkForwards(ctx context.Context, filter inventory.NetworkForwardFilter) ([]api.NetworkForward, error) {
	query := url.Values{}
	query.Add("recursion", "1")
	query = filter.AppendToURLValues(query)

	response, err := c.DoRequest(ctx, http.MethodGet, "/inventory/network_forwards", query, nil)
	if err != nil {
		return nil, err
	}

	network_forwards := []api.NetworkForward{}
	err = json.Unmarshal(response.Metadata, &network_forwards)
	if err != nil {
		return nil, err
	}

	return network_forwards, nil
}

func (c OperationsCenterClient) GetNetworkForward(ctx context.Context, id string) (api.NetworkForward, error) {
	response, err := c.DoRequest(ctx, http.MethodGet, path.Join("/inventory/network_forwards", id), nil, nil)
	if err != nil {
		return api.NetworkForward{}, err
	}

	network_forward := api.NetworkForward{}
	err = json.Unmarshal(response.Metadata, &network_forward)
	if err != nil {
		return api.NetworkForward{}, err
	}

	return network_forward, nil
}

func (c OperationsCenterClient) ResyncNetworkForward(ctx context.Context, id string) error {
	_, err := c.DoRequest(ctx, http.MethodPost, path.Join("/inventory/network_forwards", id, ":resync"), nil, nil)
	if err != nil {
		return err
	}

	return nil
}
