// Code generated by generate-inventory; DO NOT EDIT.

package client

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"path"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/shared/api"
)

func (c OperationsCenterClient) GetWithFilterNetworks(ctx context.Context, filter inventory.NetworkFilter) ([]api.Network, error) {
	query := url.Values{}
	query.Add("recursion", "1")
	query = filter.AppendToURLValues(query)

	response, err := c.DoRequest(ctx, http.MethodGet, "/inventory/networks", query, nil)
	if err != nil {
		return nil, err
	}

	networks := []api.Network{}
	err = json.Unmarshal(response.Metadata, &networks)
	if err != nil {
		return nil, err
	}

	return networks, nil
}

func (c OperationsCenterClient) GetNetwork(ctx context.Context, id string) (api.Network, error) {
	response, err := c.DoRequest(ctx, http.MethodGet, path.Join("/inventory/networks", id), nil, nil)
	if err != nil {
		return api.Network{}, err
	}

	network := api.Network{}
	err = json.Unmarshal(response.Metadata, &network)
	if err != nil {
		return api.Network{}, err
	}

	return network, nil
}

func (c OperationsCenterClient) ResyncNetwork(ctx context.Context, id string) error {
	_, err := c.DoRequest(ctx, http.MethodPost, path.Join("/inventory/networks", id, ":resync"), nil, nil)
	if err != nil {
		return err
	}

	return nil
}
