// Code generated by generate-inventory; DO NOT EDIT.

package client

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"path"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/shared/api"
)

func (c OperationsCenterClient) GetWithFilterImages(ctx context.Context, filter inventory.ImageFilter) ([]api.Image, error) {
	query := url.Values{}
	query.Add("recursion", "1")
	query = filter.AppendToURLValues(query)

	response, err := c.DoRequest(ctx, http.MethodGet, "/inventory/images", query, nil)
	if err != nil {
		return nil, err
	}

	images := []api.Image{}
	err = json.Unmarshal(response.Metadata, &images)
	if err != nil {
		return nil, err
	}

	return images, nil
}

func (c OperationsCenterClient) GetImage(ctx context.Context, id string) (api.Image, error) {
	response, err := c.DoRequest(ctx, http.MethodGet, path.Join("/inventory/images", id), nil, nil)
	if err != nil {
		return api.Image{}, err
	}

	image := api.Image{}
	err = json.Unmarshal(response.Metadata, &image)
	if err != nil {
		return api.Image{}, err
	}

	return image, nil
}

func (c OperationsCenterClient) ResyncImage(ctx context.Context, id string) error {
	_, err := c.DoRequest(ctx, http.MethodPost, path.Join("/inventory/images", id, ":resync"), nil, nil)
	if err != nil {
		return err
	}

	return nil
}
