// Code generated by generate-inventory; DO NOT EDIT.

package client

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"path"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/shared/api"
)

func (c OperationsCenterClient) GetWithFilterStoragePools(ctx context.Context, filter inventory.StoragePoolFilter) ([]api.StoragePool, error) {
	query := url.Values{}
	query.Add("recursion", "1")
	query = filter.AppendToURLValues(query)

	response, err := c.DoRequest(ctx, http.MethodGet, "/inventory/storage_pools", query, nil)
	if err != nil {
		return nil, err
	}

	storage_pools := []api.StoragePool{}
	err = json.Unmarshal(response.Metadata, &storage_pools)
	if err != nil {
		return nil, err
	}

	return storage_pools, nil
}

func (c OperationsCenterClient) GetStoragePool(ctx context.Context, id string) (api.StoragePool, error) {
	response, err := c.DoRequest(ctx, http.MethodGet, path.Join("/inventory/storage_pools", id), nil, nil)
	if err != nil {
		return api.StoragePool{}, err
	}

	storage_pool := api.StoragePool{}
	err = json.Unmarshal(response.Metadata, &storage_pool)
	if err != nil {
		return api.StoragePool{}, err
	}

	return storage_pool, nil
}

func (c OperationsCenterClient) ResyncStoragePool(ctx context.Context, id string) error {
	_, err := c.DoRequest(ctx, http.MethodPost, path.Join("/inventory/storage_pools", id, ":resync"), nil, nil)
	if err != nil {
		return err
	}

	return nil
}
