// Code generated by generate-inventory; DO NOT EDIT.

package client_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/FuturFusion/operations-center/internal/client"
	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/internal/inventory/repo/sqlite/entities"
	"github.com/FuturFusion/operations-center/internal/provisioning"
	provisioningEntities "github.com/FuturFusion/operations-center/internal/provisioning/repo/sqlite/entities"
	"github.com/FuturFusion/operations-center/internal/util/testing/uuidgen"
	"github.com/FuturFusion/operations-center/shared/api"
)

func Test_GetWithFilterNetworkForwards(t *testing.T) {
	d := daemonSetup(t)

	tests := []struct {
		name       string
		client     client.OperationsCenterClient
		dbSeedFunc func(t *testing.T)

		assertErr  require.ErrorAssertionFunc
		assertFunc func(t *testing.T, result []api.NetworkForward)
	}{
		{
			name:       "success - empty list",
			client:     d.socketClient,
			dbSeedFunc: noop,

			assertErr: require.NoError,
			assertFunc: func(t *testing.T, result []api.NetworkForward) {
				t.Helper()

				require.Empty(t, result)
			},
		},
		{
			name:   "success - one record",
			client: d.socketClient,

			dbSeedFunc: func(t *testing.T) {
				t.Helper()

				_, err := provisioningEntities.CreateCluster(t.Context(), d.db, provisioning.Cluster{
					Name:    "clusterOne",
					Channel: "stable",
				})
				require.NoError(t, err)

				_, err = entities.CreateNetworkForward(t.Context(), d.db, inventory.NetworkForward{
					UUID:    uuidgen.FromPattern(t, "1"),
					Name:    "one",
					Cluster: "clusterOne",
				})
				require.NoError(t, err)
			},

			assertErr: require.NoError,
			assertFunc: func(t *testing.T, result []api.NetworkForward) {
				t.Helper()

				require.Len(t, result, 1)
				require.Equal(t, "one", result[0].Name)
			},
		},
		{
			name:       "error - not authorized",
			client:     d.unauthorizedHTTPClient,
			dbSeedFunc: noop,

			assertErr: func(tt require.TestingT, err error, a ...any) {
				require.ErrorIs(tt, err, domain.ErrNotAuthenticated)
			},
			assertFunc: func(t *testing.T, result []api.NetworkForward) {
				t.Helper()
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			tc.dbSeedFunc(t)

			result, err := tc.client.GetWithFilterNetworkForwards(t.Context(), inventory.NetworkForwardFilter{})

			tc.assertErr(t, err)
			tc.assertFunc(t, result)
		})
	}
}

func Test_GetNetworkForward(t *testing.T) {
	d := daemonSetup(t)

	tests := []struct {
		name       string
		client     client.OperationsCenterClient
		dbSeedFunc func(t *testing.T)

		tcNameArg string

		assertErr  require.ErrorAssertionFunc
		assertFunc func(t *testing.T, result api.NetworkForward)
	}{
		{
			name:   "success - one record",
			client: d.socketClient,
			dbSeedFunc: func(t *testing.T) {
				t.Helper()

				_, err := provisioningEntities.CreateCluster(t.Context(), d.db, provisioning.Cluster{
					Name:    "clusterOne",
					Channel: "stable",
				})
				require.NoError(t, err)

				_, err = entities.CreateNetworkForward(t.Context(), d.db, inventory.NetworkForward{
					UUID:    uuidgen.FromPattern(t, "1"),
					Name:    "foo",
					Cluster: "clusterOne",
				})
				require.NoError(t, err)
			},

			tcNameArg: uuidgen.FromPattern(t, "1").String(),

			assertErr: require.NoError,
			assertFunc: func(t *testing.T, result api.NetworkForward) {
				t.Helper()

				require.Equal(t, "foo", result.Name)
			},
		},
		{
			name:       "error - not authorized",
			client:     d.unauthorizedHTTPClient,
			dbSeedFunc: noop,

			tcNameArg: "foo",

			assertErr: func(tt require.TestingT, err error, a ...any) {
				require.ErrorIs(tt, err, domain.ErrNotAuthenticated)
			},
			assertFunc: func(t *testing.T, result api.NetworkForward) {
				t.Helper()
			},
		},
		{
			name:       "error - not found",
			client:     d.socketClient,
			dbSeedFunc: noop,

			tcNameArg: uuidgen.FromPattern(t, "2").String(),

			assertErr: func(t require.TestingT, err error, a ...any) {
				require.ErrorIs(t, err, domain.ErrNotFound)
			},
			assertFunc: func(t *testing.T, result api.NetworkForward) {
				t.Helper()
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			tc.dbSeedFunc(t)

			result, err := tc.client.GetNetworkForward(t.Context(), tc.tcNameArg)

			tc.assertErr(t, err)
			tc.assertFunc(t, result)
		})
	}
}
