// Code generated by generate-inventory; DO NOT EDIT.

package client

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"path"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/shared/api"
)

func (c OperationsCenterClient) GetWithFilterStorageVolumes(ctx context.Context, filter inventory.StorageVolumeFilter) ([]api.StorageVolume, error) {
	query := url.Values{}
	query.Add("recursion", "1")
	query = filter.AppendToURLValues(query)

	response, err := c.DoRequest(ctx, http.MethodGet, "/inventory/storage_volumes", query, nil)
	if err != nil {
		return nil, err
	}

	storage_volumes := []api.StorageVolume{}
	err = json.Unmarshal(response.Metadata, &storage_volumes)
	if err != nil {
		return nil, err
	}

	return storage_volumes, nil
}

func (c OperationsCenterClient) GetStorageVolume(ctx context.Context, id string) (api.StorageVolume, error) {
	response, err := c.DoRequest(ctx, http.MethodGet, path.Join("/inventory/storage_volumes", id), nil, nil)
	if err != nil {
		return api.StorageVolume{}, err
	}

	storage_volume := api.StorageVolume{}
	err = json.Unmarshal(response.Metadata, &storage_volume)
	if err != nil {
		return api.StorageVolume{}, err
	}

	return storage_volume, nil
}

func (c OperationsCenterClient) ResyncStorageVolume(ctx context.Context, id string) error {
	_, err := c.DoRequest(ctx, http.MethodPost, path.Join("/inventory/storage_volumes", id, ":resync"), nil, nil)
	if err != nil {
		return err
	}

	return nil
}
