// Code generated by generate-inventory; DO NOT EDIT.

package client

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"path"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/shared/api"
)

func (c OperationsCenterClient) GetWithFilterProfiles(ctx context.Context, filter inventory.ProfileFilter) ([]api.Profile, error) {
	query := url.Values{}
	query.Add("recursion", "1")
	query = filter.AppendToURLValues(query)

	response, err := c.DoRequest(ctx, http.MethodGet, "/inventory/profiles", query, nil)
	if err != nil {
		return nil, err
	}

	profiles := []api.Profile{}
	err = json.Unmarshal(response.Metadata, &profiles)
	if err != nil {
		return nil, err
	}

	return profiles, nil
}

func (c OperationsCenterClient) GetProfile(ctx context.Context, id string) (api.Profile, error) {
	response, err := c.DoRequest(ctx, http.MethodGet, path.Join("/inventory/profiles", id), nil, nil)
	if err != nil {
		return api.Profile{}, err
	}

	profile := api.Profile{}
	err = json.Unmarshal(response.Metadata, &profile)
	if err != nil {
		return api.Profile{}, err
	}

	return profile, nil
}

func (c OperationsCenterClient) ResyncProfile(ctx context.Context, id string) error {
	_, err := c.DoRequest(ctx, http.MethodPost, path.Join("/inventory/profiles", id, ":resync"), nil, nil)
	if err != nil {
		return err
	}

	return nil
}
