// Code generated by generate-inventory; DO NOT EDIT.

package client

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"path"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/shared/api"
)

func (c OperationsCenterClient) GetWithFilterStorageBuckets(ctx context.Context, filter inventory.StorageBucketFilter) ([]api.StorageBucket, error) {
	query := url.Values{}
	query.Add("recursion", "1")
	query = filter.AppendToURLValues(query)

	response, err := c.DoRequest(ctx, http.MethodGet, "/inventory/storage_buckets", query, nil)
	if err != nil {
		return nil, err
	}

	storage_buckets := []api.StorageBucket{}
	err = json.Unmarshal(response.Metadata, &storage_buckets)
	if err != nil {
		return nil, err
	}

	return storage_buckets, nil
}

func (c OperationsCenterClient) GetStorageBucket(ctx context.Context, id string) (api.StorageBucket, error) {
	response, err := c.DoRequest(ctx, http.MethodGet, path.Join("/inventory/storage_buckets", id), nil, nil)
	if err != nil {
		return api.StorageBucket{}, err
	}

	storage_bucket := api.StorageBucket{}
	err = json.Unmarshal(response.Metadata, &storage_bucket)
	if err != nil {
		return api.StorageBucket{}, err
	}

	return storage_bucket, nil
}

func (c OperationsCenterClient) ResyncStorageBucket(ctx context.Context, id string) error {
	_, err := c.DoRequest(ctx, http.MethodPost, path.Join("/inventory/storage_buckets", id, ":resync"), nil, nil)
	if err != nil {
		return err
	}

	return nil
}
