// Code generated by generate-inventory; DO NOT EDIT.

package client

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"path"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/shared/api"
)

func (c OperationsCenterClient) GetWithFilterNetworkAddressSets(ctx context.Context, filter inventory.NetworkAddressSetFilter) ([]api.NetworkAddressSet, error) {
	query := url.Values{}
	query.Add("recursion", "1")
	query = filter.AppendToURLValues(query)

	response, err := c.DoRequest(ctx, http.MethodGet, "/inventory/network_address_sets", query, nil)
	if err != nil {
		return nil, err
	}

	network_address_sets := []api.NetworkAddressSet{}
	err = json.Unmarshal(response.Metadata, &network_address_sets)
	if err != nil {
		return nil, err
	}

	return network_address_sets, nil
}

func (c OperationsCenterClient) GetNetworkAddressSet(ctx context.Context, id string) (api.NetworkAddressSet, error) {
	response, err := c.DoRequest(ctx, http.MethodGet, path.Join("/inventory/network_address_sets", id), nil, nil)
	if err != nil {
		return api.NetworkAddressSet{}, err
	}

	network_address_set := api.NetworkAddressSet{}
	err = json.Unmarshal(response.Metadata, &network_address_set)
	if err != nil {
		return api.NetworkAddressSet{}, err
	}

	return network_address_set, nil
}

func (c OperationsCenterClient) ResyncNetworkAddressSet(ctx context.Context, id string) error {
	_, err := c.DoRequest(ctx, http.MethodPost, path.Join("/inventory/network_address_sets", id, ":resync"), nil, nil)
	if err != nil {
		return err
	}

	return nil
}
