// Code generated by generate-inventory; DO NOT EDIT.

package client

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"path"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/shared/api"
)

func (c OperationsCenterClient) GetWithFilterNetworkZones(ctx context.Context, filter inventory.NetworkZoneFilter) ([]api.NetworkZone, error) {
	query := url.Values{}
	query.Add("recursion", "1")
	query = filter.AppendToURLValues(query)

	response, err := c.DoRequest(ctx, http.MethodGet, "/inventory/network_zones", query, nil)
	if err != nil {
		return nil, err
	}

	network_zones := []api.NetworkZone{}
	err = json.Unmarshal(response.Metadata, &network_zones)
	if err != nil {
		return nil, err
	}

	return network_zones, nil
}

func (c OperationsCenterClient) GetNetworkZone(ctx context.Context, id string) (api.NetworkZone, error) {
	response, err := c.DoRequest(ctx, http.MethodGet, path.Join("/inventory/network_zones", id), nil, nil)
	if err != nil {
		return api.NetworkZone{}, err
	}

	network_zone := api.NetworkZone{}
	err = json.Unmarshal(response.Metadata, &network_zone)
	if err != nil {
		return api.NetworkZone{}, err
	}

	return network_zone, nil
}

func (c OperationsCenterClient) ResyncNetworkZone(ctx context.Context, id string) error {
	_, err := c.DoRequest(ctx, http.MethodPost, path.Join("/inventory/network_zones", id, ":resync"), nil, nil)
	if err != nil {
		return err
	}

	return nil
}
