// Code generated by generate-inventory; DO NOT EDIT.

package client

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"path"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/shared/api"
)

func (c OperationsCenterClient) GetWithFilterNetworkPeers(ctx context.Context, filter inventory.NetworkPeerFilter) ([]api.NetworkPeer, error) {
	query := url.Values{}
	query.Add("recursion", "1")
	query = filter.AppendToURLValues(query)

	response, err := c.DoRequest(ctx, http.MethodGet, "/inventory/network_peers", query, nil)
	if err != nil {
		return nil, err
	}

	network_peers := []api.NetworkPeer{}
	err = json.Unmarshal(response.Metadata, &network_peers)
	if err != nil {
		return nil, err
	}

	return network_peers, nil
}

func (c OperationsCenterClient) GetNetworkPeer(ctx context.Context, id string) (api.NetworkPeer, error) {
	response, err := c.DoRequest(ctx, http.MethodGet, path.Join("/inventory/network_peers", id), nil, nil)
	if err != nil {
		return api.NetworkPeer{}, err
	}

	network_peer := api.NetworkPeer{}
	err = json.Unmarshal(response.Metadata, &network_peer)
	if err != nil {
		return api.NetworkPeer{}, err
	}

	return network_peer, nil
}

func (c OperationsCenterClient) ResyncNetworkPeer(ctx context.Context, id string) error {
	_, err := c.DoRequest(ctx, http.MethodPost, path.Join("/inventory/network_peers", id, ":resync"), nil, nil)
	if err != nil {
		return err
	}

	return nil
}
