// Code generated by generate-inventory; DO NOT EDIT.

package client

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"path"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/shared/api"
)

func (c OperationsCenterClient) GetWithFilterNetworkLoadBalancers(ctx context.Context, filter inventory.NetworkLoadBalancerFilter) ([]api.NetworkLoadBalancer, error) {
	query := url.Values{}
	query.Add("recursion", "1")
	query = filter.AppendToURLValues(query)

	response, err := c.DoRequest(ctx, http.MethodGet, "/inventory/network_load_balancers", query, nil)
	if err != nil {
		return nil, err
	}

	network_load_balancers := []api.NetworkLoadBalancer{}
	err = json.Unmarshal(response.Metadata, &network_load_balancers)
	if err != nil {
		return nil, err
	}

	return network_load_balancers, nil
}

func (c OperationsCenterClient) GetNetworkLoadBalancer(ctx context.Context, id string) (api.NetworkLoadBalancer, error) {
	response, err := c.DoRequest(ctx, http.MethodGet, path.Join("/inventory/network_load_balancers", id), nil, nil)
	if err != nil {
		return api.NetworkLoadBalancer{}, err
	}

	network_load_balancer := api.NetworkLoadBalancer{}
	err = json.Unmarshal(response.Metadata, &network_load_balancer)
	if err != nil {
		return api.NetworkLoadBalancer{}, err
	}

	return network_load_balancer, nil
}

func (c OperationsCenterClient) ResyncNetworkLoadBalancer(ctx context.Context, id string) error {
	_, err := c.DoRequest(ctx, http.MethodPost, path.Join("/inventory/network_load_balancers", id, ":resync"), nil, nil)
	if err != nil {
		return err
	}

	return nil
}
