// Code generated by generate-inventory; DO NOT EDIT.

package client

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"path"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/shared/api"
)

func (c OperationsCenterClient) GetWithFilterProjects(ctx context.Context, filter inventory.ProjectFilter) ([]api.Project, error) {
	query := url.Values{}
	query.Add("recursion", "1")
	query = filter.AppendToURLValues(query)

	response, err := c.DoRequest(ctx, http.MethodGet, "/inventory/projects", query, nil)
	if err != nil {
		return nil, err
	}

	projects := []api.Project{}
	err = json.Unmarshal(response.Metadata, &projects)
	if err != nil {
		return nil, err
	}

	return projects, nil
}

func (c OperationsCenterClient) GetProject(ctx context.Context, id string) (api.Project, error) {
	response, err := c.DoRequest(ctx, http.MethodGet, path.Join("/inventory/projects", id), nil, nil)
	if err != nil {
		return api.Project{}, err
	}

	project := api.Project{}
	err = json.Unmarshal(response.Metadata, &project)
	if err != nil {
		return api.Project{}, err
	}

	return project, nil
}

func (c OperationsCenterClient) ResyncProject(ctx context.Context, id string) error {
	_, err := c.DoRequest(ctx, http.MethodPost, path.Join("/inventory/projects", id, ":resync"), nil, nil)
	if err != nil {
		return err
	}

	return nil
}
