// Code generated by generate-inventory; DO NOT EDIT.

package client

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"path"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/shared/api"
)

func (c OperationsCenterClient) GetWithFilterNetworkACLs(ctx context.Context, filter inventory.NetworkACLFilter) ([]api.NetworkACL, error) {
	query := url.Values{}
	query.Add("recursion", "1")
	query = filter.AppendToURLValues(query)

	response, err := c.DoRequest(ctx, http.MethodGet, "/inventory/network_acls", query, nil)
	if err != nil {
		return nil, err
	}

	network_acls := []api.NetworkACL{}
	err = json.Unmarshal(response.Metadata, &network_acls)
	if err != nil {
		return nil, err
	}

	return network_acls, nil
}

func (c OperationsCenterClient) GetNetworkACL(ctx context.Context, id string) (api.NetworkACL, error) {
	response, err := c.DoRequest(ctx, http.MethodGet, path.Join("/inventory/network_acls", id), nil, nil)
	if err != nil {
		return api.NetworkACL{}, err
	}

	network_acl := api.NetworkACL{}
	err = json.Unmarshal(response.Metadata, &network_acl)
	if err != nil {
		return api.NetworkACL{}, err
	}

	return network_acl, nil
}

func (c OperationsCenterClient) ResyncNetworkACL(ctx context.Context, id string) error {
	_, err := c.DoRequest(ctx, http.MethodPost, path.Join("/inventory/network_acls", id, ":resync"), nil, nil)
	if err != nil {
		return err
	}

	return nil
}
