// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package mock

import (
	"context"
	"sync"

	"github.com/FuturFusion/operations-center/internal/provisioning"
)

// Ensure that ServerRepoMock does implement provisioning.ServerRepo.
// If this is not the case, regenerate this file with mockery.
var _ provisioning.ServerRepo = &ServerRepoMock{}

// ServerRepoMock is a mock implementation of provisioning.ServerRepo.
//
//	func TestSomethingThatUsesServerRepo(t *testing.T) {
//
//		// make and configure a mocked provisioning.ServerRepo
//		mockedServerRepo := &ServerRepoMock{
//			CreateFunc: func(ctx context.Context, server provisioning.Server) (int64, error) {
//				panic("mock out the Create method")
//			},
//			DeleteByNameFunc: func(ctx context.Context, name string) error {
//				panic("mock out the DeleteByName method")
//			},
//			GetAllFunc: func(ctx context.Context) (provisioning.Servers, error) {
//				panic("mock out the GetAll method")
//			},
//			GetAllNamesFunc: func(ctx context.Context) ([]string, error) {
//				panic("mock out the GetAllNames method")
//			},
//			GetAllNamesWithActiveDeploymentFunc: func(ctx context.Context) ([]string, error) {
//				panic("mock out the GetAllNamesWithActiveDeployment method")
//			},
//			GetAllNamesWithFilterFunc: func(ctx context.Context, filter provisioning.ServerFilter) ([]string, error) {
//				panic("mock out the GetAllNamesWithFilter method")
//			},
//			GetAllWithFilterFunc: func(ctx context.Context, filter provisioning.ServerFilter) (provisioning.Servers, error) {
//				panic("mock out the GetAllWithFilter method")
//			},
//			GetByCertificateFunc: func(ctx context.Context, certificatePEM string) (*provisioning.Server, error) {
//				panic("mock out the GetByCertificate method")
//			},
//			GetByMachineIDFunc: func(ctx context.Context, machineID string) (*provisioning.Server, error) {
//				panic("mock out the GetByMachineID method")
//			},
//			GetByNameFunc: func(ctx context.Context, name string) (*provisioning.Server, error) {
//				panic("mock out the GetByName method")
//			},
//			GetBySystemUUIDFunc: func(ctx context.Context, systemUUID string) (*provisioning.Server, error) {
//				panic("mock out the GetBySystemUUID method")
//			},
//			RenameFunc: func(ctx context.Context, oldName string, newName string) error {
//				panic("mock out the Rename method")
//			},
//			UpdateFunc: func(ctx context.Context, server provisioning.Server) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedServerRepo in code that requires provisioning.ServerRepo
//		// and then make assertions.
//
//	}
type ServerRepoMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, server provisioning.Server) (int64, error)

	// DeleteByNameFunc mocks the DeleteByName method.
	DeleteByNameFunc func(ctx context.Context, name string) error

	// GetAllFunc mocks the GetAll method.
	GetAllFunc func(ctx context.Context) (provisioning.Servers, error)

	// GetAllNamesFunc mocks the GetAllNames method.
	GetAllNamesFunc func(ctx context.Context) ([]string, error)

	// GetAllNamesWithActiveDeploymentFunc mocks the GetAllNamesWithActiveDeployment method.
	GetAllNamesWithActiveDeploymentFunc func(ctx context.Context) ([]string, error)

	// GetAllNamesWithFilterFunc mocks the GetAllNamesWithFilter method.
	GetAllNamesWithFilterFunc func(ctx context.Context, filter provisioning.ServerFilter) ([]string, error)

	// GetAllWithFilterFunc mocks the GetAllWithFilter method.
	GetAllWithFilterFunc func(ctx context.Context, filter provisioning.ServerFilter) (provisioning.Servers, error)

	// GetByCertificateFunc mocks the GetByCertificate method.
	GetByCertificateFunc func(ctx context.Context, certificatePEM string) (*provisioning.Server, error)

	// GetByMachineIDFunc mocks the GetByMachineID method.
	GetByMachineIDFunc func(ctx context.Context, machineID string) (*provisioning.Server, error)

	// GetByNameFunc mocks the GetByName method.
	GetByNameFunc func(ctx context.Context, name string) (*provisioning.Server, error)

	// GetBySystemUUIDFunc mocks the GetBySystemUUID method.
	GetBySystemUUIDFunc func(ctx context.Context, systemUUID string) (*provisioning.Server, error)

	// RenameFunc mocks the Rename method.
	RenameFunc func(ctx context.Context, oldName string, newName string) error

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, server provisioning.Server) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
		}
		// DeleteByName holds details about calls to the DeleteByName method.
		DeleteByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetAllNames holds details about calls to the GetAllNames method.
		GetAllNames []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetAllNamesWithActiveDeployment holds details about calls to the GetAllNamesWithActiveDeployment method.
		GetAllNamesWithActiveDeployment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetAllNamesWithFilter holds details about calls to the GetAllNamesWithFilter method.
		GetAllNamesWithFilter []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter provisioning.ServerFilter
		}
		// GetAllWithFilter holds details about calls to the GetAllWithFilter method.
		GetAllWithFilter []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter provisioning.ServerFilter
		}
		// GetByCertificate holds details about calls to the GetByCertificate method.
		GetByCertificate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CertificatePEM is the certificatePEM argument value.
			CertificatePEM string
		}
		// GetByMachineID holds details about calls to the GetByMachineID method.
		GetByMachineID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MachineID is the machineID argument value.
			MachineID string
		}
		// GetByName holds details about calls to the GetByName method.
		GetByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// GetBySystemUUID holds details about calls to the GetBySystemUUID method.
		GetBySystemUUID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SystemUUID is the systemUUID argument value.
			SystemUUID string
		}
		// Rename holds details about calls to the Rename method.
		Rename []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OldName is the oldName argument value.
			OldName string
			// NewName is the newName argument value.
			NewName string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
		}
	}
	lockCreate                          sync.RWMutex
	lockDeleteByName                    sync.RWMutex
	lockGetAll                          sync.RWMutex
	lockGetAllNames                     sync.RWMutex
	lockGetAllNamesWithActiveDeployment sync.RWMutex
	lockGetAllNamesWithFilter           sync.RWMutex
	lockGetAllWithFilter                sync.RWMutex
	lockGetByCertificate                sync.RWMutex
	lockGetByMachineID                  sync.RWMutex
	lockGetByName                       sync.RWMutex
	lockGetBySystemUUID                 sync.RWMutex
	lockRename                          sync.RWMutex
	lockUpdate                          sync.RWMutex
}

// Create calls CreateFunc.
func (mock *ServerRepoMock) Create(ctx context.Context, server provisioning.Server) (int64, error) {
	if mock.CreateFunc == nil {
		panic("ServerRepoMock.CreateFunc: method is nil but ServerRepo.Create was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
	}{
		Ctx:    ctx,
		Server: server,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, server)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedServerRepo.CreateCalls())
func (mock *ServerRepoMock) CreateCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// DeleteByName calls DeleteByNameFunc.
func (mock *ServerRepoMock) DeleteByName(ctx context.Context, name string) error {
	if mock.DeleteByNameFunc == nil {
		panic("ServerRepoMock.DeleteByNameFunc: method is nil but ServerRepo.DeleteByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockDeleteByName.Lock()
	mock.calls.DeleteByName = append(mock.calls.DeleteByName, callInfo)
	mock.lockDeleteByName.Unlock()
	return mock.DeleteByNameFunc(ctx, name)
}

// DeleteByNameCalls gets all the calls that were made to DeleteByName.
// Check the length with:
//
//	len(mockedServerRepo.DeleteByNameCalls())
func (mock *ServerRepoMock) DeleteByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockDeleteByName.RLock()
	calls = mock.calls.DeleteByName
	mock.lockDeleteByName.RUnlock()
	return calls
}

// GetAll calls GetAllFunc.
func (mock *ServerRepoMock) GetAll(ctx context.Context) (provisioning.Servers, error) {
	if mock.GetAllFunc == nil {
		panic("ServerRepoMock.GetAllFunc: method is nil but ServerRepo.GetAll was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc(ctx)
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//
//	len(mockedServerRepo.GetAllCalls())
func (mock *ServerRepoMock) GetAllCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// GetAllNames calls GetAllNamesFunc.
func (mock *ServerRepoMock) GetAllNames(ctx context.Context) ([]string, error) {
	if mock.GetAllNamesFunc == nil {
		panic("ServerRepoMock.GetAllNamesFunc: method is nil but ServerRepo.GetAllNames was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAllNames.Lock()
	mock.calls.GetAllNames = append(mock.calls.GetAllNames, callInfo)
	mock.lockGetAllNames.Unlock()
	return mock.GetAllNamesFunc(ctx)
}

// GetAllNamesCalls gets all the calls that were made to GetAllNames.
// Check the length with:
//
//	len(mockedServerRepo.GetAllNamesCalls())
func (mock *ServerRepoMock) GetAllNamesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAllNames.RLock()
	calls = mock.calls.GetAllNames
	mock.lockGetAllNames.RUnlock()
	return calls
}

// GetAllNamesWithActiveDeployment calls GetAllNamesWithActiveDeploymentFunc.
func (mock *ServerRepoMock) GetAllNamesWithActiveDeployment(ctx context.Context) ([]string, error) {
	if mock.GetAllNamesWithActiveDeploymentFunc == nil {
		panic("ServerRepoMock.GetAllNamesWithActiveDeploymentFunc: method is nil but ServerRepo.GetAllNamesWithActiveDeployment was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAllNamesWithActiveDeployment.Lock()
	mock.calls.GetAllNamesWithActiveDeployment = append(mock.calls.GetAllNamesWithActiveDeployment, callInfo)
	mock.lockGetAllNamesWithActiveDeployment.Unlock()
	return mock.GetAllNamesWithActiveDeploymentFunc(ctx)
}

// GetAllNamesWithActiveDeploymentCalls gets all the calls that were made to GetAllNamesWithActiveDeployment.
// Check the length with:
//
//	len(mockedServerRepo.GetAllNamesWithActiveDeploymentCalls())
func (mock *ServerRepoMock) GetAllNamesWithActiveDeploymentCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAllNamesWithActiveDeployment.RLock()
	calls = mock.calls.GetAllNamesWithActiveDeployment
	mock.lockGetAllNamesWithActiveDeployment.RUnlock()
	return calls
}

// GetAllNamesWithFilter calls GetAllNamesWithFilterFunc.
func (mock *ServerRepoMock) GetAllNamesWithFilter(ctx context.Context, filter provisioning.ServerFilter) ([]string, error) {
	if mock.GetAllNamesWithFilterFunc == nil {
		panic("ServerRepoMock.GetAllNamesWithFilterFunc: method is nil but ServerRepo.GetAllNamesWithFilter was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Filter provisioning.ServerFilter
	}{
		Ctx:    ctx,
		Filter: filter,
	}
	mock.lockGetAllNamesWithFilter.Lock()
	mock.calls.GetAllNamesWithFilter = append(mock.calls.GetAllNamesWithFilter, callInfo)
	mock.lockGetAllNamesWithFilter.Unlock()
	return mock.GetAllNamesWithFilterFunc(ctx, filter)
}

// GetAllNamesWithFilterCalls gets all the calls that were made to GetAllNamesWithFilter.
// Check the length with:
//
//	len(mockedServerRepo.GetAllNamesWithFilterCalls())
func (mock *ServerRepoMock) GetAllNamesWithFilterCalls() []struct {
	Ctx    context.Context
	Filter provisioning.ServerFilter
} {
	var calls []struct {
		Ctx    context.Context
		Filter provisioning.ServerFilter
	}
	mock.lockGetAllNamesWithFilter.RLock()
	calls = mock.calls.GetAllNamesWithFilter
	mock.lockGetAllNamesWithFilter.RUnlock()
	return calls
}

// GetAllWithFilter calls GetAllWithFilterFunc.
func (mock *ServerRepoMock) GetAllWithFilter(ctx context.Context, filter provisioning.ServerFilter) (provisioning.Servers, error) {
	if mock.GetAllWithFilterFunc == nil {
		panic("ServerRepoMock.GetAllWithFilterFunc: method is nil but ServerRepo.GetAllWithFilter was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Filter provisioning.ServerFilter
	}{
		Ctx:    ctx,
		Filter: filter,
	}
	mock.lockGetAllWithFilter.Lock()
	mock.calls.GetAllWithFilter = append(mock.calls.GetAllWithFilter, callInfo)
	mock.lockGetAllWithFilter.Unlock()
	return mock.GetAllWithFilterFunc(ctx, filter)
}

// GetAllWithFilterCalls gets all the calls that were made to GetAllWithFilter.
// Check the length with:
//
//	len(mockedServerRepo.GetAllWithFilterCalls())
func (mock *ServerRepoMock) GetAllWithFilterCalls() []struct {
	Ctx    context.Context
	Filter provisioning.ServerFilter
} {
	var calls []struct {
		Ctx    context.Context
		Filter provisioning.ServerFilter
	}
	mock.lockGetAllWithFilter.RLock()
	calls = mock.calls.GetAllWithFilter
	mock.lockGetAllWithFilter.RUnlock()
	return calls
}

// GetByCertificate calls GetByCertificateFunc.
func (mock *ServerRepoMock) GetByCertificate(ctx context.Context, certificatePEM string) (*provisioning.Server, error) {
	if mock.GetByCertificateFunc == nil {
		panic("ServerRepoMock.GetByCertificateFunc: method is nil but ServerRepo.GetByCertificate was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		CertificatePEM string
	}{
		Ctx:            ctx,
		CertificatePEM: certificatePEM,
	}
	mock.lockGetByCertificate.Lock()
	mock.calls.GetByCertificate = append(mock.calls.GetByCertificate, callInfo)
	mock.lockGetByCertificate.Unlock()
	return mock.GetByCertificateFunc(ctx, certificatePEM)
}

// GetByCertificateCalls gets all the calls that were made to GetByCertificate.
// Check the length with:
//
//	len(mockedServerRepo.GetByCertificateCalls())
func (mock *ServerRepoMock) GetByCertificateCalls() []struct {
	Ctx            context.Context
	CertificatePEM string
} {
	var calls []struct {
		Ctx            context.Context
		CertificatePEM string
	}
	mock.lockGetByCertificate.RLock()
	calls = mock.calls.GetByCertificate
	mock.lockGetByCertificate.RUnlock()
	return calls
}

// GetByMachineID calls GetByMachineIDFunc.
func (mock *ServerRepoMock) GetByMachineID(ctx context.Context, machineID string) (*provisioning.Server, error) {
	if mock.GetByMachineIDFunc == nil {
		panic("ServerRepoMock.GetByMachineIDFunc: method is nil but ServerRepo.GetByMachineID was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		MachineID string
	}{
		Ctx:       ctx,
		MachineID: machineID,
	}
	mock.lockGetByMachineID.Lock()
	mock.calls.GetByMachineID = append(mock.calls.GetByMachineID, callInfo)
	mock.lockGetByMachineID.Unlock()
	return mock.GetByMachineIDFunc(ctx, machineID)
}

// GetByMachineIDCalls gets all the calls that were made to GetByMachineID.
// Check the length with:
//
//	len(mockedServerRepo.GetByMachineIDCalls())
func (mock *ServerRepoMock) GetByMachineIDCalls() []struct {
	Ctx       context.Context
	MachineID string
} {
	var calls []struct {
		Ctx       context.Context
		MachineID string
	}
	mock.lockGetByMachineID.RLock()
	calls = mock.calls.GetByMachineID
	mock.lockGetByMachineID.RUnlock()
	return calls
}

// GetByName calls GetByNameFunc.
func (mock *ServerRepoMock) GetByName(ctx context.Context, name string) (*provisioning.Server, error) {
	if mock.GetByNameFunc == nil {
		panic("ServerRepoMock.GetByNameFunc: method is nil but ServerRepo.GetByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetByName.Lock()
	mock.calls.GetByName = append(mock.calls.GetByName, callInfo)
	mock.lockGetByName.Unlock()
	return mock.GetByNameFunc(ctx, name)
}

// GetByNameCalls gets all the calls that were made to GetByName.
// Check the length with:
//
//	len(mockedServerRepo.GetByNameCalls())
func (mock *ServerRepoMock) GetByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetByName.RLock()
	calls = mock.calls.GetByName
	mock.lockGetByName.RUnlock()
	return calls
}

// GetBySystemUUID calls GetBySystemUUIDFunc.
func (mock *ServerRepoMock) GetBySystemUUID(ctx context.Context, systemUUID string) (*provisioning.Server, error) {
	if mock.GetBySystemUUIDFunc == nil {
		panic("ServerRepoMock.GetBySystemUUIDFunc: method is nil but ServerRepo.GetBySystemUUID was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		SystemUUID string
	}{
		Ctx:        ctx,
		SystemUUID: systemUUID,
	}
	mock.lockGetBySystemUUID.Lock()
	mock.calls.GetBySystemUUID = append(mock.calls.GetBySystemUUID, callInfo)
	mock.lockGetBySystemUUID.Unlock()
	return mock.GetBySystemUUIDFunc(ctx, systemUUID)
}

// GetBySystemUUIDCalls gets all the calls that were made to GetBySystemUUID.
// Check the length with:
//
//	len(mockedServerRepo.GetBySystemUUIDCalls())
func (mock *ServerRepoMock) GetBySystemUUIDCalls() []struct {
	Ctx        context.Context
	SystemUUID string
} {
	var calls []struct {
		Ctx        context.Context
		SystemUUID string
	}
	mock.lockGetBySystemUUID.RLock()
	calls = mock.calls.GetBySystemUUID
	mock.lockGetBySystemUUID.RUnlock()
	return calls
}

// Rename calls RenameFunc.
func (mock *ServerRepoMock) Rename(ctx context.Context, oldName string, newName string) error {
	if mock.RenameFunc == nil {
		panic("ServerRepoMock.RenameFunc: method is nil but ServerRepo.Rename was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OldName string
		NewName string
	}{
		Ctx:     ctx,
		OldName: oldName,
		NewName: newName,
	}
	mock.lockRename.Lock()
	mock.calls.Rename = append(mock.calls.Rename, callInfo)
	mock.lockRename.Unlock()
	return mock.RenameFunc(ctx, oldName, newName)
}

// RenameCalls gets all the calls that were made to Rename.
// Check the length with:
//
//	len(mockedServerRepo.RenameCalls())
func (mock *ServerRepoMock) RenameCalls() []struct {
	Ctx     context.Context
	OldName string
	NewName string
} {
	var calls []struct {
		Ctx     context.Context
		OldName string
		NewName string
	}
	mock.lockRename.RLock()
	calls = mock.calls.Rename
	mock.lockRename.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *ServerRepoMock) Update(ctx context.Context, server provisioning.Server) error {
	if mock.UpdateFunc == nil {
		panic("ServerRepoMock.UpdateFunc: method is nil but ServerRepo.Update was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
	}{
		Ctx:    ctx,
		Server: server,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, server)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedServerRepo.UpdateCalls())
func (mock *ServerRepoMock) UpdateCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
