// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/metrics/prometheus.gotmpl

package middleware

import (
	"context"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"

	"github.com/FuturFusion/operations-center/internal/provisioning"
)

// ServerRepoWithPrometheus implements provisioning.ServerRepo interface with all methods wrapped
// with Prometheus metrics.
type ServerRepoWithPrometheus struct {
	base         provisioning.ServerRepo
	instanceName string
}

var serverRepoDurationSummaryVec = promauto.NewSummaryVec(
	prometheus.SummaryOpts{
		Name:       "server_repo_duration_seconds",
		Help:       "serverRepo runtime duration and result",
		MaxAge:     time.Minute,
		Objectives: map[float64]float64{0.5: 0.05, 0.9: 0.01, 0.99: 0.001},
	},
	[]string{"instance_name", "method", "result"},
)

// NewServerRepoWithPrometheus returns an instance of the provisioning.ServerRepo decorated with prometheus summary metric.
func NewServerRepoWithPrometheus(base provisioning.ServerRepo, instanceName string) ServerRepoWithPrometheus {
	return ServerRepoWithPrometheus{
		base:         base,
		instanceName: instanceName,
	}
}

// Create implements provisioning.ServerRepo.
func (_d ServerRepoWithPrometheus) Create(ctx context.Context, server provisioning.Server) (n int64, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverRepoDurationSummaryVec.WithLabelValues(_d.instanceName, "Create", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Create(ctx, server)
}

// DeleteByName implements provisioning.ServerRepo.
func (_d ServerRepoWithPrometheus) DeleteByName(ctx context.Context, name string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverRepoDurationSummaryVec.WithLabelValues(_d.instanceName, "DeleteByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.DeleteByName(ctx, name)
}

// GetAll implements provisioning.ServerRepo.
func (_d ServerRepoWithPrometheus) GetAll(ctx context.Context) (servers provisioning.Servers, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverRepoDurationSummaryVec.WithLabelValues(_d.instanceName, "GetAll", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetAll(ctx)
}

// GetAllNames implements provisioning.ServerRepo.
func (_d ServerRepoWithPrometheus) GetAllNames(ctx context.Context) (strings []string, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverRepoDurationSummaryVec.WithLabelValues(_d.instanceName, "GetAllNames", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetAllNames(ctx)
}

// GetAllNamesWithActiveDeployment implements provisioning.ServerRepo.
func (_d ServerRepoWithPrometheus) GetAllNamesWithActiveDeployment(ctx context.Context) (strings []string, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverRepoDurationSummaryVec.WithLabelValues(_d.instanceName, "GetAllNamesWithActiveDeployment", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetAllNamesWithActiveDeployment(ctx)
}

// GetAllNamesWithFilter implements provisioning.ServerRepo.
func (_d ServerRepoWithPrometheus) GetAllNamesWithFilter(ctx context.Context, filter provisioning.ServerFilter) (strings []string, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverRepoDurationSummaryVec.WithLabelValues(_d.instanceName, "GetAllNamesWithFilter", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetAllNamesWithFilter(ctx, filter)
}

// GetAllWithFilter implements provisioning.ServerRepo.
func (_d ServerRepoWithPrometheus) GetAllWithFilter(ctx context.Context, filter provisioning.ServerFilter) (servers provisioning.Servers, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverRepoDurationSummaryVec.WithLabelValues(_d.instanceName, "GetAllWithFilter", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetAllWithFilter(ctx, filter)
}

// GetByCertificate implements provisioning.ServerRepo.
func (_d ServerRepoWithPrometheus) GetByCertificate(ctx context.Context, certificatePEM string) (server *provisioning.Server, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverRepoDurationSummaryVec.WithLabelValues(_d.instanceName, "GetByCertificate", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetByCertificate(ctx, certificatePEM)
}

// GetByMachineID implements provisioning.ServerRepo.
func (_d ServerRepoWithPrometheus) GetByMachineID(ctx context.Context, machineID string) (server *provisioning.Server, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverRepoDurationSummaryVec.WithLabelValues(_d.instanceName, "GetByMachineID", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetByMachineID(ctx, machineID)
}

// GetByName implements provisioning.ServerRepo.
func (_d ServerRepoWithPrometheus) GetByName(ctx context.Context, name string) (server *provisioning.Server, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverRepoDurationSummaryVec.WithLabelValues(_d.instanceName, "GetByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetByName(ctx, name)
}

// GetBySystemUUID implements provisioning.ServerRepo.
func (_d ServerRepoWithPrometheus) GetBySystemUUID(ctx context.Context, systemUUID string) (server *provisioning.Server, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverRepoDurationSummaryVec.WithLabelValues(_d.instanceName, "GetBySystemUUID", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetBySystemUUID(ctx, systemUUID)
}

// Rename implements provisioning.ServerRepo.
func (_d ServerRepoWithPrometheus) Rename(ctx context.Context, oldName string, newName string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverRepoDurationSummaryVec.WithLabelValues(_d.instanceName, "Rename", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Rename(ctx, oldName, newName)
}

// Update implements provisioning.ServerRepo.
func (_d ServerRepoWithPrometheus) Update(ctx context.Context, server provisioning.Server) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverRepoDurationSummaryVec.WithLabelValues(_d.instanceName, "Update", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Update(ctx, server)
}
