// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/util/logger/slog.gotmpl

package middleware

import (
	"context"
	"log/slog"

	"github.com/google/uuid"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/internal/util/logger"
	"github.com/FuturFusion/operations-center/shared/api"
)

// ServerServiceWithSlog implements provisioning.ServerService that is instrumented with slog logger.
type ServerServiceWithSlog struct {
	_base                 provisioning.ServerService
	_isInformativeErrFunc func(error) bool
}

type ServerServiceWithSlogOption func(s *ServerServiceWithSlog)

func ServerServiceWithSlogWithInformativeErrFunc(isInformativeErrFunc func(error) bool) ServerServiceWithSlogOption {
	return func(_base *ServerServiceWithSlog) {
		_base._isInformativeErrFunc = isInformativeErrFunc
	}
}

// NewServerServiceWithSlog instruments an implementation of the provisioning.ServerService with simple logging.
func NewServerServiceWithSlog(base provisioning.ServerService, opts ...ServerServiceWithSlogOption) ServerServiceWithSlog {
	this := ServerServiceWithSlog{
		_base:                 base,
		_isInformativeErrFunc: func(error) bool { return false },
	}

	for _, opt := range opts {
		opt(&this)
	}

	return this
}

// AddApplication implements provisioning.ServerService.
func (_d ServerServiceWithSlog) AddApplication(ctx context.Context, name string, applicationName string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.String("applicationName", applicationName),
		)
	}
	log.DebugContext(ctx, "=> calling AddApplication")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method AddApplication returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method AddApplication returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method AddApplication finished")
		}
	}()
	return _d._base.AddApplication(ctx, name, applicationName)
}

// ApplyBIOSAttributesByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) ApplyBIOSAttributesByName(ctx context.Context, name string, attributes map[string]any) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Any("attributes", attributes),
		)
	}
	log.DebugContext(ctx, "=> calling ApplyBIOSAttributesByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method ApplyBIOSAttributesByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method ApplyBIOSAttributesByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method ApplyBIOSAttributesByName finished")
		}
	}()
	return _d._base.ApplyBIOSAttributesByName(ctx, name, attributes)
}

// BIOSProfileByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) BIOSProfileByName(ctx context.Context, name string) (bIOSProfileResolution *provisioning.BIOSProfileResolution, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.DebugContext(ctx, "=> calling BIOSProfileByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("bIOSProfileResolution", bIOSProfileResolution),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method BIOSProfileByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method BIOSProfileByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method BIOSProfileByName finished")
		}
	}()
	return _d._base.BIOSProfileByName(ctx, name)
}

// BMCApplySecureBootCertificatesByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) BMCApplySecureBootCertificatesByName(ctx context.Context, name string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.DebugContext(ctx, "=> calling BMCApplySecureBootCertificatesByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method BMCApplySecureBootCertificatesByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method BMCApplySecureBootCertificatesByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method BMCApplySecureBootCertificatesByName finished")
		}
	}()
	return _d._base.BMCApplySecureBootCertificatesByName(ctx, name)
}

// BMCAttachMediaByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) BMCAttachMediaByName(ctx context.Context, name string, media api.ServerBMCAttachMedia) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Any("media", media),
		)
	}
	log.DebugContext(ctx, "=> calling BMCAttachMediaByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method BMCAttachMediaByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method BMCAttachMediaByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method BMCAttachMediaByName finished")
		}
	}()
	return _d._base.BMCAttachMediaByName(ctx, name, media)
}

// BMCBIOSAttributeByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) BMCBIOSAttributeByName(ctx context.Context, name string, attributeName string) (bIOSAttribute api.BIOSAttribute, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.String("attributeName", attributeName),
		)
	}
	log.DebugContext(ctx, "=> calling BMCBIOSAttributeByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("bIOSAttribute", bIOSAttribute),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method BMCBIOSAttributeByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method BMCBIOSAttributeByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method BMCBIOSAttributeByName finished")
		}
	}()
	return _d._base.BMCBIOSAttributeByName(ctx, name, attributeName)
}

// BMCBIOSAttributesByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) BMCBIOSAttributesByName(ctx context.Context, name string) (bIOSAttributes []api.BIOSAttribute, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.DebugContext(ctx, "=> calling BMCBIOSAttributesByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("bIOSAttributes", bIOSAttributes),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method BMCBIOSAttributesByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method BMCBIOSAttributesByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method BMCBIOSAttributesByName finished")
		}
	}()
	return _d._base.BMCBIOSAttributesByName(ctx, name)
}

// BMCDetachMediaByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) BMCDetachMediaByName(ctx context.Context, name string, virtualMediaID string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.String("virtualMediaID", virtualMediaID),
		)
	}
	log.DebugContext(ctx, "=> calling BMCDetachMediaByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method BMCDetachMediaByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method BMCDetachMediaByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method BMCDetachMediaByName finished")
		}
	}()
	return _d._base.BMCDetachMediaByName(ctx, name, virtualMediaID)
}

// BMCDumpByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) BMCDumpByName(ctx context.Context, name string, additionalEndpoints []string, skipPredefined bool, trace bool) (bMCDump api.BMCDump, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Any("additionalEndpoints", additionalEndpoints),
			slog.Bool("skipPredefined", skipPredefined),
			slog.Bool("trace", trace),
		)
	}
	log.DebugContext(ctx, "=> calling BMCDumpByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("bMCDump", bMCDump),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method BMCDumpByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method BMCDumpByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method BMCDumpByName finished")
		}
	}()
	return _d._base.BMCDumpByName(ctx, name, additionalEndpoints, skipPredefined, trace)
}

// BMCLogEntriesByNameAndLogSource implements provisioning.ServerService.
func (_d ServerServiceWithSlog) BMCLogEntriesByNameAndLogSource(ctx context.Context, name string, logSource string) (bMCLogEvents []api.BMCLogEvent, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.String("logSource", logSource),
		)
	}
	log.DebugContext(ctx, "=> calling BMCLogEntriesByNameAndLogSource")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("bMCLogEvents", bMCLogEvents),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method BMCLogEntriesByNameAndLogSource returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method BMCLogEntriesByNameAndLogSource returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method BMCLogEntriesByNameAndLogSource finished")
		}
	}()
	return _d._base.BMCLogEntriesByNameAndLogSource(ctx, name, logSource)
}

// BMCLogSourcesByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) BMCLogSourcesByName(ctx context.Context, name string) (strings []string, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.DebugContext(ctx, "=> calling BMCLogSourcesByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("strings", strings),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method BMCLogSourcesByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method BMCLogSourcesByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method BMCLogSourcesByName finished")
		}
	}()
	return _d._base.BMCLogSourcesByName(ctx, name)
}

// BMCRefreshByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) BMCRefreshByName(ctx context.Context, name string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.DebugContext(ctx, "=> calling BMCRefreshByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method BMCRefreshByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method BMCRefreshByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method BMCRefreshByName finished")
		}
	}()
	return _d._base.BMCRefreshByName(ctx, name)
}

// BMCResetSecureBootKeysByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) BMCResetSecureBootKeysByName(ctx context.Context, name string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.DebugContext(ctx, "=> calling BMCResetSecureBootKeysByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method BMCResetSecureBootKeysByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method BMCResetSecureBootKeysByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method BMCResetSecureBootKeysByName finished")
		}
	}()
	return _d._base.BMCResetSecureBootKeysByName(ctx, name)
}

// BMCServerPowerOffByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) BMCServerPowerOffByName(ctx context.Context, name string, force bool) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Bool("force", force),
		)
	}
	log.DebugContext(ctx, "=> calling BMCServerPowerOffByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method BMCServerPowerOffByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method BMCServerPowerOffByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method BMCServerPowerOffByName finished")
		}
	}()
	return _d._base.BMCServerPowerOffByName(ctx, name, force)
}

// BMCServerPowerOnByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) BMCServerPowerOnByName(ctx context.Context, name string, force bool) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Bool("force", force),
		)
	}
	log.DebugContext(ctx, "=> calling BMCServerPowerOnByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method BMCServerPowerOnByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method BMCServerPowerOnByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method BMCServerPowerOnByName finished")
		}
	}()
	return _d._base.BMCServerPowerOnByName(ctx, name, force)
}

// BMCServerRestartByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) BMCServerRestartByName(ctx context.Context, name string, force bool) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Bool("force", force),
		)
	}
	log.DebugContext(ctx, "=> calling BMCServerRestartByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method BMCServerRestartByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method BMCServerRestartByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method BMCServerRestartByName finished")
		}
	}()
	return _d._base.BMCServerRestartByName(ctx, name, force)
}

// BMCServerSetLocationIndicatorByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) BMCServerSetLocationIndicatorByName(ctx context.Context, name string, active bool) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Bool("active", active),
		)
	}
	log.DebugContext(ctx, "=> calling BMCServerSetLocationIndicatorByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method BMCServerSetLocationIndicatorByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method BMCServerSetLocationIndicatorByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method BMCServerSetLocationIndicatorByName finished")
		}
	}()
	return _d._base.BMCServerSetLocationIndicatorByName(ctx, name, active)
}

// CancelDeploymentByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) CancelDeploymentByName(ctx context.Context, name string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.DebugContext(ctx, "=> calling CancelDeploymentByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method CancelDeploymentByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method CancelDeploymentByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method CancelDeploymentByName finished")
		}
	}()
	return _d._base.CancelDeploymentByName(ctx, name)
}

// DeleteByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) DeleteByName(ctx context.Context, name string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.DebugContext(ctx, "=> calling DeleteByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method DeleteByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method DeleteByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method DeleteByName finished")
		}
	}()
	return _d._base.DeleteByName(ctx, name)
}

// DeployByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) DeployByName(ctx context.Context, name string, request provisioning.ServerDeploymentRequest) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Any("request", request),
		)
	}
	log.DebugContext(ctx, "=> calling DeployByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method DeployByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method DeployByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method DeployByName finished")
		}
	}()
	return _d._base.DeployByName(ctx, name, request)
}

// DeploymentControlLoop implements provisioning.ServerService.
func (_d ServerServiceWithSlog) DeploymentControlLoop(ctx context.Context, serverNameFilter *string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("serverNameFilter", serverNameFilter),
		)
	}
	log.DebugContext(ctx, "=> calling DeploymentControlLoop")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method DeploymentControlLoop returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method DeploymentControlLoop returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method DeploymentControlLoop finished")
		}
	}()
	return _d._base.DeploymentControlLoop(ctx, serverNameFilter)
}

// EvacuateSystemByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) EvacuateSystemByName(ctx context.Context, name string, clusterUpdate bool, force bool) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Bool("clusterUpdate", clusterUpdate),
			slog.Bool("force", force),
		)
	}
	log.DebugContext(ctx, "=> calling EvacuateSystemByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method EvacuateSystemByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method EvacuateSystemByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method EvacuateSystemByName finished")
		}
	}()
	return _d._base.EvacuateSystemByName(ctx, name, clusterUpdate, force)
}

// FactoryResetByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) FactoryResetByName(ctx context.Context, name string, tokenID *uuid.UUID, tokenSeedName *string, force bool) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Any("tokenID", tokenID),
			slog.Any("tokenSeedName", tokenSeedName),
			slog.Bool("force", force),
		)
	}
	log.DebugContext(ctx, "=> calling FactoryResetByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method FactoryResetByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method FactoryResetByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method FactoryResetByName finished")
		}
	}()
	return _d._base.FactoryResetByName(ctx, name, tokenID, tokenSeedName, force)
}

// GetAll implements provisioning.ServerService.
func (_d ServerServiceWithSlog) GetAll(ctx context.Context) (servers provisioning.Servers, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
		)
	}
	log.DebugContext(ctx, "=> calling GetAll")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("servers", servers),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetAll returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetAll returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetAll finished")
		}
	}()
	return _d._base.GetAll(ctx)
}

// GetAllNames implements provisioning.ServerService.
func (_d ServerServiceWithSlog) GetAllNames(ctx context.Context) (strings []string, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
		)
	}
	log.DebugContext(ctx, "=> calling GetAllNames")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("strings", strings),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetAllNames returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetAllNames returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetAllNames finished")
		}
	}()
	return _d._base.GetAllNames(ctx)
}

// GetAllNamesWithFilter implements provisioning.ServerService.
func (_d ServerServiceWithSlog) GetAllNamesWithFilter(ctx context.Context, filter provisioning.ServerFilter) (strings []string, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("filter", filter),
		)
	}
	log.DebugContext(ctx, "=> calling GetAllNamesWithFilter")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("strings", strings),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetAllNamesWithFilter returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetAllNamesWithFilter returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetAllNamesWithFilter finished")
		}
	}()
	return _d._base.GetAllNamesWithFilter(ctx, filter)
}

// GetAllWithFilter implements provisioning.ServerService.
func (_d ServerServiceWithSlog) GetAllWithFilter(ctx context.Context, filter provisioning.ServerFilter) (servers provisioning.Servers, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("filter", filter),
		)
	}
	log.DebugContext(ctx, "=> calling GetAllWithFilter")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("servers", servers),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetAllWithFilter returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetAllWithFilter returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetAllWithFilter finished")
		}
	}()
	return _d._base.GetAllWithFilter(ctx, filter)
}

// GetByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) GetByName(ctx context.Context, name string) (server *provisioning.Server, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.DebugContext(ctx, "=> calling GetByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("server", server),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetByName finished")
		}
	}()
	return _d._base.GetByName(ctx, name)
}

// GetChangelogByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) GetChangelogByName(ctx context.Context, name string) (updateChangelog api.UpdateChangelog, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.DebugContext(ctx, "=> calling GetChangelogByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("updateChangelog", updateChangelog),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetChangelogByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetChangelogByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetChangelogByName finished")
		}
	}()
	return _d._base.GetChangelogByName(ctx, name)
}

// GetSystemKernel implements provisioning.ServerService.
func (_d ServerServiceWithSlog) GetSystemKernel(ctx context.Context, name string) (serverSystemKernel provisioning.ServerSystemKernel, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.DebugContext(ctx, "=> calling GetSystemKernel")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("serverSystemKernel", serverSystemKernel),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetSystemKernel returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetSystemKernel returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetSystemKernel finished")
		}
	}()
	return _d._base.GetSystemKernel(ctx, name)
}

// GetSystemLogging implements provisioning.ServerService.
func (_d ServerServiceWithSlog) GetSystemLogging(ctx context.Context, name string) (serverSystemLogging provisioning.ServerSystemLogging, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.DebugContext(ctx, "=> calling GetSystemLogging")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("serverSystemLogging", serverSystemLogging),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetSystemLogging returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetSystemLogging returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetSystemLogging finished")
		}
	}()
	return _d._base.GetSystemLogging(ctx, name)
}

// GetSystemProvider implements provisioning.ServerService.
func (_d ServerServiceWithSlog) GetSystemProvider(ctx context.Context, name string) (serverSystemProvider provisioning.ServerSystemProvider, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.DebugContext(ctx, "=> calling GetSystemProvider")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("serverSystemProvider", serverSystemProvider),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetSystemProvider returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetSystemProvider returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetSystemProvider finished")
		}
	}()
	return _d._base.GetSystemProvider(ctx, name)
}

// GetSystemUpdate implements provisioning.ServerService.
func (_d ServerServiceWithSlog) GetSystemUpdate(ctx context.Context, name string) (serverSystemUpdate provisioning.ServerSystemUpdate, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.DebugContext(ctx, "=> calling GetSystemUpdate")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("serverSystemUpdate", serverSystemUpdate),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetSystemUpdate returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetSystemUpdate returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetSystemUpdate finished")
		}
	}()
	return _d._base.GetSystemUpdate(ctx, name)
}

// PollServer implements provisioning.ServerService.
func (_d ServerServiceWithSlog) PollServer(ctx context.Context, server provisioning.Server, updateServerConfiguration bool) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.Bool("updateServerConfiguration", updateServerConfiguration),
		)
	}
	log.DebugContext(ctx, "=> calling PollServer")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method PollServer returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method PollServer returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method PollServer finished")
		}
	}()
	return _d._base.PollServer(ctx, server, updateServerConfiguration)
}

// PollServers implements provisioning.ServerService.
func (_d ServerServiceWithSlog) PollServers(ctx context.Context, serverFilter provisioning.ServerFilter, updateServerConfiguration bool) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("serverFilter", serverFilter),
			slog.Bool("updateServerConfiguration", updateServerConfiguration),
		)
	}
	log.DebugContext(ctx, "=> calling PollServers")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method PollServers returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method PollServers returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method PollServers finished")
		}
	}()
	return _d._base.PollServers(ctx, serverFilter, updateServerConfiguration)
}

// PostRestoreSystemDoneByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) PostRestoreSystemDoneByName(ctx context.Context, name string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.DebugContext(ctx, "=> calling PostRestoreSystemDoneByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method PostRestoreSystemDoneByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method PostRestoreSystemDoneByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method PostRestoreSystemDoneByName finished")
		}
	}()
	return _d._base.PostRestoreSystemDoneByName(ctx, name)
}

// PoweroffSystemByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) PoweroffSystemByName(ctx context.Context, name string, force bool) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Bool("force", force),
		)
	}
	log.DebugContext(ctx, "=> calling PoweroffSystemByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method PoweroffSystemByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method PoweroffSystemByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method PoweroffSystemByName finished")
		}
	}()
	return _d._base.PoweroffSystemByName(ctx, name, force)
}

// PreRegister implements provisioning.ServerService.
func (_d ServerServiceWithSlog) PreRegister(ctx context.Context, server provisioning.Server) (server1 provisioning.Server, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
		)
	}
	log.DebugContext(ctx, "=> calling PreRegister")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("server1", server1),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method PreRegister returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method PreRegister returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method PreRegister finished")
		}
	}()
	return _d._base.PreRegister(ctx, server)
}

// RebootSystemByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) RebootSystemByName(ctx context.Context, name string, force bool) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Bool("force", force),
		)
	}
	log.DebugContext(ctx, "=> calling RebootSystemByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method RebootSystemByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method RebootSystemByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method RebootSystemByName finished")
		}
	}()
	return _d._base.RebootSystemByName(ctx, name, force)
}

// Register implements provisioning.ServerService.
func (_d ServerServiceWithSlog) Register(ctx context.Context, token uuid.UUID, server provisioning.Server) (server1 provisioning.Server, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("token", token),
			slog.Any("server", server),
		)
	}
	log.DebugContext(ctx, "=> calling Register")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("server1", server1),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method Register returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method Register returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method Register finished")
		}
	}()
	return _d._base.Register(ctx, token, server)
}

// Rename implements provisioning.ServerService.
func (_d ServerServiceWithSlog) Rename(ctx context.Context, oldName string, newName string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("oldName", oldName),
			slog.String("newName", newName),
		)
	}
	log.DebugContext(ctx, "=> calling Rename")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method Rename returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method Rename returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method Rename finished")
		}
	}()
	return _d._base.Rename(ctx, oldName, newName)
}

// RestartApplication implements provisioning.ServerService.
func (_d ServerServiceWithSlog) RestartApplication(ctx context.Context, name string, applicationName string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.String("applicationName", applicationName),
		)
	}
	log.DebugContext(ctx, "=> calling RestartApplication")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method RestartApplication returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method RestartApplication returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method RestartApplication finished")
		}
	}()
	return _d._base.RestartApplication(ctx, name, applicationName)
}

// RestoreSystemByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) RestoreSystemByName(ctx context.Context, name string, clusterUpdate bool, force bool, restoreModeSkip bool) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Bool("clusterUpdate", clusterUpdate),
			slog.Bool("force", force),
			slog.Bool("restoreModeSkip", restoreModeSkip),
		)
	}
	log.DebugContext(ctx, "=> calling RestoreSystemByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method RestoreSystemByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method RestoreSystemByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method RestoreSystemByName finished")
		}
	}()
	return _d._base.RestoreSystemByName(ctx, name, clusterUpdate, force, restoreModeSkip)
}

// ResyncBMCData implements provisioning.ServerService.
func (_d ServerServiceWithSlog) ResyncBMCData(ctx context.Context) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
		)
	}
	log.DebugContext(ctx, "=> calling ResyncBMCData")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method ResyncBMCData returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method ResyncBMCData returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method ResyncBMCData finished")
		}
	}()
	return _d._base.ResyncBMCData(ctx)
}

// ResyncByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) ResyncByName(ctx context.Context, clusterName string, event domain.LifecycleEvent) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("clusterName", clusterName),
			slog.Any("event", event),
		)
	}
	log.DebugContext(ctx, "=> calling ResyncByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method ResyncByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method ResyncByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method ResyncByName finished")
		}
	}()
	return _d._base.ResyncByName(ctx, clusterName, event)
}

// SelfRegisterOperationsCenter implements provisioning.ServerService.
func (_d ServerServiceWithSlog) SelfRegisterOperationsCenter(ctx context.Context) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
		)
	}
	log.DebugContext(ctx, "=> calling SelfRegisterOperationsCenter")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method SelfRegisterOperationsCenter returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method SelfRegisterOperationsCenter returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method SelfRegisterOperationsCenter finished")
		}
	}()
	return _d._base.SelfRegisterOperationsCenter(ctx)
}

// SelfUpdate implements provisioning.ServerService.
func (_d ServerServiceWithSlog) SelfUpdate(ctx context.Context, serverUpdate provisioning.ServerSelfUpdate) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("serverUpdate", serverUpdate),
		)
	}
	log.DebugContext(ctx, "=> calling SelfUpdate")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method SelfUpdate returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method SelfUpdate returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method SelfUpdate finished")
		}
	}()
	return _d._base.SelfUpdate(ctx, serverUpdate)
}

// SetClusterService implements provisioning.ServerService.
func (_d ServerServiceWithSlog) SetClusterService(clusterSvc provisioning.ClusterService) {
	ctx := context.Background()
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("clusterSvc", clusterSvc),
		)
	}
	log.DebugContext(ctx, "=> calling SetClusterService")
	defer func() {
		log := slog.With()
		log.DebugContext(ctx, "<= method SetClusterService finished")
	}()
	_d._base.SetClusterService(clusterSvc)
}

// SyncCluster implements provisioning.ServerService.
func (_d ServerServiceWithSlog) SyncCluster(ctx context.Context, clusterName string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("clusterName", clusterName),
		)
	}
	log.DebugContext(ctx, "=> calling SyncCluster")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method SyncCluster returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method SyncCluster returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method SyncCluster finished")
		}
	}()
	return _d._base.SyncCluster(ctx, clusterName)
}

// Update implements provisioning.ServerService.
func (_d ServerServiceWithSlog) Update(ctx context.Context, server provisioning.Server, force bool, updateSystem bool, bmcConnectionTest bool) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.Bool("force", force),
			slog.Bool("updateSystem", updateSystem),
			slog.Bool("bmcConnectionTest", bmcConnectionTest),
		)
	}
	log.DebugContext(ctx, "=> calling Update")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method Update returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method Update returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method Update finished")
		}
	}()
	return _d._base.Update(ctx, server, force, updateSystem, bmcConnectionTest)
}

// UpdateSystemByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) UpdateSystemByName(ctx context.Context, name string, updateRequest api.ServerUpdatePost, force bool) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Any("updateRequest", updateRequest),
			slog.Bool("force", force),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateSystemByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method UpdateSystemByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method UpdateSystemByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method UpdateSystemByName finished")
		}
	}()
	return _d._base.UpdateSystemByName(ctx, name, updateRequest, force)
}

// UpdateSystemKernel implements provisioning.ServerService.
func (_d ServerServiceWithSlog) UpdateSystemKernel(ctx context.Context, name string, kernelConfig provisioning.ServerSystemKernel) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Any("kernelConfig", kernelConfig),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateSystemKernel")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method UpdateSystemKernel returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method UpdateSystemKernel returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method UpdateSystemKernel finished")
		}
	}()
	return _d._base.UpdateSystemKernel(ctx, name, kernelConfig)
}

// UpdateSystemLogging implements provisioning.ServerService.
func (_d ServerServiceWithSlog) UpdateSystemLogging(ctx context.Context, name string, loggingConfig provisioning.ServerSystemLogging) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Any("loggingConfig", loggingConfig),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateSystemLogging")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method UpdateSystemLogging returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method UpdateSystemLogging returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method UpdateSystemLogging finished")
		}
	}()
	return _d._base.UpdateSystemLogging(ctx, name, loggingConfig)
}

// UpdateSystemNetwork implements provisioning.ServerService.
func (_d ServerServiceWithSlog) UpdateSystemNetwork(ctx context.Context, name string, networkConfig provisioning.ServerSystemNetwork) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Any("networkConfig", networkConfig),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateSystemNetwork")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method UpdateSystemNetwork returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method UpdateSystemNetwork returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method UpdateSystemNetwork finished")
		}
	}()
	return _d._base.UpdateSystemNetwork(ctx, name, networkConfig)
}

// UpdateSystemProvider implements provisioning.ServerService.
func (_d ServerServiceWithSlog) UpdateSystemProvider(ctx context.Context, name string, providerConfig provisioning.ServerSystemProvider) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Any("providerConfig", providerConfig),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateSystemProvider")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method UpdateSystemProvider returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method UpdateSystemProvider returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method UpdateSystemProvider finished")
		}
	}()
	return _d._base.UpdateSystemProvider(ctx, name, providerConfig)
}

// UpdateSystemStorage implements provisioning.ServerService.
func (_d ServerServiceWithSlog) UpdateSystemStorage(ctx context.Context, name string, networkConfig provisioning.ServerSystemStorage) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Any("networkConfig", networkConfig),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateSystemStorage")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method UpdateSystemStorage returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method UpdateSystemStorage returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method UpdateSystemStorage finished")
		}
	}()
	return _d._base.UpdateSystemStorage(ctx, name, networkConfig)
}

// UpdateSystemUpdate implements provisioning.ServerService.
func (_d ServerServiceWithSlog) UpdateSystemUpdate(ctx context.Context, name string, updateConfig provisioning.ServerSystemUpdate) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Any("updateConfig", updateConfig),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateSystemUpdate")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method UpdateSystemUpdate returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method UpdateSystemUpdate returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method UpdateSystemUpdate finished")
		}
	}()
	return _d._base.UpdateSystemUpdate(ctx, name, updateConfig)
}

// ValidateBIOSProfileByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) ValidateBIOSProfileByName(ctx context.Context, name string) (bIOSProfileResolution *provisioning.BIOSProfileResolution, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.DebugContext(ctx, "=> calling ValidateBIOSProfileByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("bIOSProfileResolution", bIOSProfileResolution),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method ValidateBIOSProfileByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method ValidateBIOSProfileByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method ValidateBIOSProfileByName finished")
		}
	}()
	return _d._base.ValidateBIOSProfileByName(ctx, name)
}
