// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/metrics/prometheus.gotmpl

package middleware

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/shared/api"
)

// ServerServiceWithPrometheus implements provisioning.ServerService interface with all methods wrapped
// with Prometheus metrics.
type ServerServiceWithPrometheus struct {
	base         provisioning.ServerService
	instanceName string
}

var serverServiceDurationSummaryVec = promauto.NewSummaryVec(
	prometheus.SummaryOpts{
		Name:       "server_service_duration_seconds",
		Help:       "serverService runtime duration and result",
		MaxAge:     time.Minute,
		Objectives: map[float64]float64{0.5: 0.05, 0.9: 0.01, 0.99: 0.001},
	},
	[]string{"instance_name", "method", "result"},
)

// NewServerServiceWithPrometheus returns an instance of the provisioning.ServerService decorated with prometheus summary metric.
func NewServerServiceWithPrometheus(base provisioning.ServerService, instanceName string) ServerServiceWithPrometheus {
	return ServerServiceWithPrometheus{
		base:         base,
		instanceName: instanceName,
	}
}

// AddApplication implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) AddApplication(ctx context.Context, name string, applicationName string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "AddApplication", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.AddApplication(ctx, name, applicationName)
}

// ApplyBIOSAttributesByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) ApplyBIOSAttributesByName(ctx context.Context, name string, attributes map[string]any) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "ApplyBIOSAttributesByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.ApplyBIOSAttributesByName(ctx, name, attributes)
}

// BIOSProfileByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) BIOSProfileByName(ctx context.Context, name string) (bIOSProfileResolution *provisioning.BIOSProfileResolution, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "BIOSProfileByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.BIOSProfileByName(ctx, name)
}

// BMCApplySecureBootCertificatesByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) BMCApplySecureBootCertificatesByName(ctx context.Context, name string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "BMCApplySecureBootCertificatesByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.BMCApplySecureBootCertificatesByName(ctx, name)
}

// BMCAttachMediaByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) BMCAttachMediaByName(ctx context.Context, name string, media api.ServerBMCAttachMedia) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "BMCAttachMediaByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.BMCAttachMediaByName(ctx, name, media)
}

// BMCBIOSAttributeByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) BMCBIOSAttributeByName(ctx context.Context, name string, attributeName string) (bIOSAttribute api.BIOSAttribute, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "BMCBIOSAttributeByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.BMCBIOSAttributeByName(ctx, name, attributeName)
}

// BMCBIOSAttributesByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) BMCBIOSAttributesByName(ctx context.Context, name string) (bIOSAttributes []api.BIOSAttribute, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "BMCBIOSAttributesByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.BMCBIOSAttributesByName(ctx, name)
}

// BMCDetachMediaByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) BMCDetachMediaByName(ctx context.Context, name string, virtualMediaID string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "BMCDetachMediaByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.BMCDetachMediaByName(ctx, name, virtualMediaID)
}

// BMCDumpByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) BMCDumpByName(ctx context.Context, name string, additionalEndpoints []string, skipPredefined bool, trace bool) (bMCDump api.BMCDump, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "BMCDumpByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.BMCDumpByName(ctx, name, additionalEndpoints, skipPredefined, trace)
}

// BMCLogEntriesByNameAndLogSource implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) BMCLogEntriesByNameAndLogSource(ctx context.Context, name string, logSource string) (bMCLogEvents []api.BMCLogEvent, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "BMCLogEntriesByNameAndLogSource", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.BMCLogEntriesByNameAndLogSource(ctx, name, logSource)
}

// BMCLogSourcesByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) BMCLogSourcesByName(ctx context.Context, name string) (strings []string, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "BMCLogSourcesByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.BMCLogSourcesByName(ctx, name)
}

// BMCRefreshByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) BMCRefreshByName(ctx context.Context, name string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "BMCRefreshByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.BMCRefreshByName(ctx, name)
}

// BMCResetSecureBootKeysByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) BMCResetSecureBootKeysByName(ctx context.Context, name string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "BMCResetSecureBootKeysByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.BMCResetSecureBootKeysByName(ctx, name)
}

// BMCServerPowerOffByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) BMCServerPowerOffByName(ctx context.Context, name string, force bool) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "BMCServerPowerOffByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.BMCServerPowerOffByName(ctx, name, force)
}

// BMCServerPowerOnByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) BMCServerPowerOnByName(ctx context.Context, name string, force bool) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "BMCServerPowerOnByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.BMCServerPowerOnByName(ctx, name, force)
}

// BMCServerRestartByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) BMCServerRestartByName(ctx context.Context, name string, force bool) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "BMCServerRestartByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.BMCServerRestartByName(ctx, name, force)
}

// BMCServerSetLocationIndicatorByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) BMCServerSetLocationIndicatorByName(ctx context.Context, name string, active bool) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "BMCServerSetLocationIndicatorByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.BMCServerSetLocationIndicatorByName(ctx, name, active)
}

// CancelDeploymentByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) CancelDeploymentByName(ctx context.Context, name string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "CancelDeploymentByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.CancelDeploymentByName(ctx, name)
}

// DeleteByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) DeleteByName(ctx context.Context, name string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "DeleteByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.DeleteByName(ctx, name)
}

// DeployByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) DeployByName(ctx context.Context, name string, request provisioning.ServerDeploymentRequest) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "DeployByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.DeployByName(ctx, name, request)
}

// DeploymentControlLoop implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) DeploymentControlLoop(ctx context.Context, serverNameFilter *string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "DeploymentControlLoop", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.DeploymentControlLoop(ctx, serverNameFilter)
}

// EvacuateSystemByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) EvacuateSystemByName(ctx context.Context, name string, clusterUpdate bool, force bool) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "EvacuateSystemByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.EvacuateSystemByName(ctx, name, clusterUpdate, force)
}

// FactoryResetByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) FactoryResetByName(ctx context.Context, name string, tokenID *uuid.UUID, tokenSeedName *string, force bool) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "FactoryResetByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.FactoryResetByName(ctx, name, tokenID, tokenSeedName, force)
}

// GetAll implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) GetAll(ctx context.Context) (servers provisioning.Servers, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetAll", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetAll(ctx)
}

// GetAllNames implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) GetAllNames(ctx context.Context) (strings []string, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetAllNames", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetAllNames(ctx)
}

// GetAllNamesWithFilter implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) GetAllNamesWithFilter(ctx context.Context, filter provisioning.ServerFilter) (strings []string, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetAllNamesWithFilter", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetAllNamesWithFilter(ctx, filter)
}

// GetAllWithFilter implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) GetAllWithFilter(ctx context.Context, filter provisioning.ServerFilter) (servers provisioning.Servers, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetAllWithFilter", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetAllWithFilter(ctx, filter)
}

// GetByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) GetByName(ctx context.Context, name string) (server *provisioning.Server, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetByName(ctx, name)
}

// GetChangelogByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) GetChangelogByName(ctx context.Context, name string) (updateChangelog api.UpdateChangelog, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetChangelogByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetChangelogByName(ctx, name)
}

// GetSystemKernel implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) GetSystemKernel(ctx context.Context, name string) (serverSystemKernel provisioning.ServerSystemKernel, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetSystemKernel", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetSystemKernel(ctx, name)
}

// GetSystemLogging implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) GetSystemLogging(ctx context.Context, name string) (serverSystemLogging provisioning.ServerSystemLogging, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetSystemLogging", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetSystemLogging(ctx, name)
}

// GetSystemProvider implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) GetSystemProvider(ctx context.Context, name string) (serverSystemProvider provisioning.ServerSystemProvider, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetSystemProvider", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetSystemProvider(ctx, name)
}

// GetSystemUpdate implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) GetSystemUpdate(ctx context.Context, name string) (serverSystemUpdate provisioning.ServerSystemUpdate, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetSystemUpdate", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetSystemUpdate(ctx, name)
}

// PollServer implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) PollServer(ctx context.Context, server provisioning.Server, updateServerConfiguration bool) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "PollServer", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.PollServer(ctx, server, updateServerConfiguration)
}

// PollServers implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) PollServers(ctx context.Context, serverFilter provisioning.ServerFilter, updateServerConfiguration bool) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "PollServers", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.PollServers(ctx, serverFilter, updateServerConfiguration)
}

// PostRestoreSystemDoneByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) PostRestoreSystemDoneByName(ctx context.Context, name string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "PostRestoreSystemDoneByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.PostRestoreSystemDoneByName(ctx, name)
}

// PoweroffSystemByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) PoweroffSystemByName(ctx context.Context, name string, force bool) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "PoweroffSystemByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.PoweroffSystemByName(ctx, name, force)
}

// PreRegister implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) PreRegister(ctx context.Context, server provisioning.Server) (server1 provisioning.Server, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "PreRegister", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.PreRegister(ctx, server)
}

// RebootSystemByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) RebootSystemByName(ctx context.Context, name string, force bool) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "RebootSystemByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.RebootSystemByName(ctx, name, force)
}

// Register implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) Register(ctx context.Context, token uuid.UUID, server provisioning.Server) (server1 provisioning.Server, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "Register", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Register(ctx, token, server)
}

// Rename implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) Rename(ctx context.Context, oldName string, newName string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "Rename", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Rename(ctx, oldName, newName)
}

// RestartApplication implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) RestartApplication(ctx context.Context, name string, applicationName string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "RestartApplication", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.RestartApplication(ctx, name, applicationName)
}

// RestoreSystemByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) RestoreSystemByName(ctx context.Context, name string, clusterUpdate bool, force bool, restoreModeSkip bool) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "RestoreSystemByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.RestoreSystemByName(ctx, name, clusterUpdate, force, restoreModeSkip)
}

// ResyncBMCData implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) ResyncBMCData(ctx context.Context) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "ResyncBMCData", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.ResyncBMCData(ctx)
}

// ResyncByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) ResyncByName(ctx context.Context, clusterName string, event domain.LifecycleEvent) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "ResyncByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.ResyncByName(ctx, clusterName, event)
}

// SelfRegisterOperationsCenter implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) SelfRegisterOperationsCenter(ctx context.Context) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "SelfRegisterOperationsCenter", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.SelfRegisterOperationsCenter(ctx)
}

// SelfUpdate implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) SelfUpdate(ctx context.Context, serverUpdate provisioning.ServerSelfUpdate) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "SelfUpdate", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.SelfUpdate(ctx, serverUpdate)
}

// SetClusterService implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) SetClusterService(clusterSvc provisioning.ClusterService) {
	_since := time.Now()
	defer func() {
		result := "ok"
		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "SetClusterService", result).Observe(time.Since(_since).Seconds())
	}()
	_d.base.SetClusterService(clusterSvc)
}

// SyncCluster implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) SyncCluster(ctx context.Context, clusterName string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "SyncCluster", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.SyncCluster(ctx, clusterName)
}

// Update implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) Update(ctx context.Context, server provisioning.Server, force bool, updateSystem bool, bmcConnectionTest bool) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "Update", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Update(ctx, server, force, updateSystem, bmcConnectionTest)
}

// UpdateSystemByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) UpdateSystemByName(ctx context.Context, name string, updateRequest api.ServerUpdatePost, force bool) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateSystemByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateSystemByName(ctx, name, updateRequest, force)
}

// UpdateSystemKernel implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) UpdateSystemKernel(ctx context.Context, name string, kernelConfig provisioning.ServerSystemKernel) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateSystemKernel", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateSystemKernel(ctx, name, kernelConfig)
}

// UpdateSystemLogging implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) UpdateSystemLogging(ctx context.Context, name string, loggingConfig provisioning.ServerSystemLogging) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateSystemLogging", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateSystemLogging(ctx, name, loggingConfig)
}

// UpdateSystemNetwork implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) UpdateSystemNetwork(ctx context.Context, name string, networkConfig provisioning.ServerSystemNetwork) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateSystemNetwork", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateSystemNetwork(ctx, name, networkConfig)
}

// UpdateSystemProvider implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) UpdateSystemProvider(ctx context.Context, name string, providerConfig provisioning.ServerSystemProvider) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateSystemProvider", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateSystemProvider(ctx, name, providerConfig)
}

// UpdateSystemStorage implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) UpdateSystemStorage(ctx context.Context, name string, networkConfig provisioning.ServerSystemStorage) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateSystemStorage", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateSystemStorage(ctx, name, networkConfig)
}

// UpdateSystemUpdate implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) UpdateSystemUpdate(ctx context.Context, name string, updateConfig provisioning.ServerSystemUpdate) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateSystemUpdate", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateSystemUpdate(ctx, name, updateConfig)
}

// ValidateBIOSProfileByName implements provisioning.ServerService.
func (_d ServerServiceWithPrometheus) ValidateBIOSProfileByName(ctx context.Context, name string) (bIOSProfileResolution *provisioning.BIOSProfileResolution, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "ValidateBIOSProfileByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.ValidateBIOSProfileByName(ctx, name)
}
