---

name: Tests
on:
  push:
    branches:
      - main
      - stable-*
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-tests:
    name: Code
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        go:
          - oldstable
          - stable
          # Disabled for now, since tip is not really important for us as of now.exclude:
          # This saves us some minutes on CI.
          # - tip
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Dependency Review
        uses: actions/dependency-review-action@v5
        if: github.event_name == 'pull_request'

      - name: Install Go (${{ matrix.go }})
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
        if: matrix.go != 'tip'

      - name: Install Go (stable)
        uses: actions/setup-go@v6
        with:
          go-version: stable
        if: matrix.go == 'tip'

      - name: Install Go (tip)
        run: |
          go install golang.org/dl/gotip@latest
          gotip download
          ~/sdk/gotip/bin/go version
          echo "PATH=$HOME/go/bin:$HOME/sdk/gotip/bin/:$PATH" >> $GITHUB_ENV
        if: matrix.go == 'tip'

      - name: Check compatible min Go version
        run: |
          go mod tidy

      - name: Install dependencies
        run: |
          sudo apt-get update

          sudo apt-get install --no-install-recommends -y \
            make

      - name: Download go dependencies
        run: |
          go mod download

      - name: Run build
        run: |
          make build

      - uses: opentofu/setup-opentofu@v2

      - name: Run static analysis
        env:
          GITHUB_BEFORE: ${{ github.event.before }}
        run: |
          make static-analysis

      - name: Unit tests (all)
        env:
          # Required for github access with increased rate limiting during test
          # of github repo to access GH releases.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make test
